"""Generate BYUL Grid CFFI declarations from BYUL public C headers.

This script deliberately generates only the low-level ``ffi.cdef`` blocks.
The Python wrapper classes remain handwritten because pointer ownership and
callback lifetime cannot be inferred reliably from a C declaration.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

from byul_wrapper_generator import audit_header


ROOT = Path(__file__).resolve().parent
REPOSITORY_ROOT = ROOT.parents[2]
BYUL_ROOT = REPOSITORY_ROOT / "byul"
MODULE_ROOT = ROOT / "byul_wrapper"

# Headers are ordered so declarations used by a module are already available
# through that module's normal Python imports.  A module may use more than one
# public header when it exposes a family of C APIs.
MODULE_HEADERS: dict[str, tuple[str, ...]] = {
    "byul_tick.py": ("byul_tick/byul_tick.h",),
    "navsys_status.py": ("navsys/navsys_status.h",),
    "coord.py": ("navsys/coord/coord.h",),
    "coord_list.py": ("navsys/coord/coord_list.h",),
    "coord_hash.py": ("navsys/coord/coord_hash.h",),
    "cost_coord_pq.py": ("navsys/coord/cost_coord_pq.h",),
    "dstar_lite_key.py": ("navsys/dstar_lite/dstar_lite_key.h",),
    "dstar_lite_pqueue.py": ("navsys/dstar_lite/dstar_lite_pqueue.h",),
    "navgrid.py": (
        "navsys/navgrid/navcell.h",
        "navsys/navgrid/navgrid.h",
    ),
    "route.py": ("navsys/route/route.h",),
    "route_finder_common.py": ("navsys/route_finder/route_finder_core.h",),
    "route_finder.py": (
        "navsys/route_finder/route_finder.h",
        *tuple(
            str(path.relative_to(BYUL_ROOT)).replace("\\", "/")
            for path in sorted(
                (BYUL_ROOT / "navsys" / "route_finder").glob("*.h")
            )
            if path.name not in {"route_finder.h", "route_finder_core.h"}
        ),
    ),
    "dstar_lite.py": ("navsys/dstar_lite/dstar_lite.h",),
    "console.py": (
        "console/console.h",
        "console/dstar_lite_console.h",
    ),
}

CDEF_START = 'ffi.cdef("""'
CDEF_END = '"""'


def strip_comments(source: str) -> str:
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    return re.sub(r"//[^\n]*", "", source)


def header_to_cdef(path: Path) -> str:
    """Convert one C-compatible public header to CFFI parser input."""
    source = strip_comments(path.read_text(encoding="utf-8"))
    lines: list[str] = []
    skipping_directive = False

    for raw_line in source.splitlines():
        stripped = raw_line.strip()

        # Includes and conditional compilation are resolved by the explicit
        # module manifest and the wrapper import graph, not by CFFI.
        if skipping_directive:
            skipping_directive = raw_line.rstrip().endswith("\\")
            continue
        if stripped.startswith("#"):
            skipping_directive = raw_line.rstrip().endswith("\\")
            continue

        if stripped in {'extern "C" {', "}"}:
            continue

        line = raw_line.replace("BYUL_API", "")
        line = re.sub(
            r'BYUL_DEPRECATED\(\s*"(?:\\.|[^"\\])*"\s*\)',
            "",
            line,
        )
        line = re.sub(r"\s+$", "", line)
        lines.append(line)

    text = "\n".join(lines).strip()
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def generated_block(headers: tuple[str, ...]) -> str:
    sections = [
        "/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */",
        "/* Do not edit this ffi.cdef block by hand. */",
    ]
    for relative in headers:
        path = BYUL_ROOT / relative
        if not path.is_file():
            raise FileNotFoundError(f"BYUL public header not found: {path}")
        sections.append(f"\n/* Source: byul/{relative} */\n{header_to_cdef(path)}")
    return "\n".join(sections).strip()


def replace_cdef(module_path: Path, cdef: str) -> str:
    source = module_path.read_text(encoding="utf-8")
    start = source.find(CDEF_START)
    if start < 0:
        raise ValueError(f"ffi.cdef block not found: {module_path}")
    body_start = start + len(CDEF_START)
    end = source.find(CDEF_END, body_start)
    if end < 0:
        raise ValueError(f"ffi.cdef block is not terminated: {module_path}")
    return source[:body_start] + "\n" + cdef + "\n" + source[end:]


def generate(check: bool) -> int:
    stale: list[Path] = []
    for module_name, headers in MODULE_HEADERS.items():
        module_path = MODULE_ROOT / module_name
        expected = replace_cdef(module_path, generated_block(headers))
        current = module_path.read_text(encoding="utf-8")
        if current == expected:
            continue
        stale.append(module_path)
        if not check:
            module_path.write_text(expected, encoding="utf-8", newline="\n")
            print(f"[GENERATED] {module_path.relative_to(REPOSITORY_ROOT)}")

    if check and stale:
        print("[ERROR] Generated CFFI declarations are stale:", file=sys.stderr)
        for path in stale:
            print(f"  {path.relative_to(REPOSITORY_ROOT)}", file=sys.stderr)
        print(
            "Run: py -3 tools/python/byul_wrapper/generate_wrapper_abi.py",
            file=sys.stderr,
        )
        return 1

    if not stale:
        print("[OK] BYUL Grid CFFI declarations are up to date.")
    return 0


def registered_headers() -> tuple[str, ...]:
    """Return the deterministic set of public headers in the generation manifest."""
    return tuple(sorted({header for headers in MODULE_HEADERS.values() for header in headers}))


def public_headers() -> tuple[Path, ...]:
    """Return exported-function or explicitly registered public C headers."""
    registered = set(registered_headers())
    result = []
    for path in BYUL_ROOT.rglob("*.h"):
        relative = path.relative_to(BYUL_ROOT).as_posix()
        if (
            "BYUL_API" in path.read_text(encoding="utf-8", errors="replace")
            or relative in registered
        ):
            result.append(path)
    return tuple(sorted(result))


def audit(all_headers: bool, json_output: Path | None, verbose: bool) -> int:
    """Audit structured header contracts without guessing missing semantics."""
    paths = (
        public_headers()
        if all_headers
        else tuple(BYUL_ROOT / relative for relative in registered_headers())
    )
    reports = tuple(audit_header(path) for path in paths)
    registered = set(registered_headers())
    all_public = {
        path.relative_to(BYUL_ROOT).as_posix() for path in public_headers()
    }
    payload = {
        "headers": len(reports),
        "declarations": sum(len(report.declarations) for report in reports),
        "errors": sum(report.error_count for report in reports),
        "registered_headers": len(registered),
        "public_headers": len(all_public),
        "unregistered_headers": sorted(all_public - registered),
        "issues": [
            {
                "header": report.path.relative_to(BYUL_ROOT).as_posix(),
                "severity": issue.severity,
                "code": issue.code,
                "symbol": issue.symbol,
                "message": issue.message,
            }
            for report in reports
            for issue in report.issues
        ],
    }
    if json_output is not None:
        json_output.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
            newline="\n",
        )
    print(
        "[AUDIT] "
        f"headers={payload['headers']} declarations={payload['declarations']} "
        f"errors={payload['errors']} registered={payload['registered_headers']}/"
        f"{payload['public_headers']}"
    )
    if verbose:
        for item in payload["issues"]:
            print(
                f"[{item['severity'].upper()}] {item['header']}:"
                f"{item['symbol'] or '-'} {item['code']}: {item['message']}"
            )
    return 1 if payload["errors"] else 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate BYUL Grid ffi.cdef blocks from BYUL public headers."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="report stale generated declarations without modifying files",
    )
    parser.add_argument(
        "--audit",
        action="store_true",
        help="lint registered header declarations and structured Doxygen metadata",
    )
    parser.add_argument(
        "--all-headers",
        action="store_true",
        help="with --audit, inspect every header containing BYUL_API",
    )
    parser.add_argument(
        "--json-output",
        type=Path,
        help="with --audit, write a machine-readable coverage and lint report",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="with --audit, print every lint issue",
    )
    args = parser.parse_args()
    if args.all_headers and not args.audit:
        parser.error("--all-headers requires --audit")
    if args.json_output is not None and not args.audit:
        parser.error("--json-output requires --audit")
    if args.verbose and not args.audit:
        parser.error("--verbose requires --audit")
    if args.audit:
        return audit(
            all_headers=args.all_headers,
            json_output=args.json_output,
            verbose=args.verbose,
        )
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
