"""Generate BYUL Grid CFFI declarations from BYUL public C headers.

This script deliberately generates only the low-level ``ffi.cdef`` blocks.
The Python wrapper classes remain handwritten because pointer ownership and
callback lifetime cannot be inferred reliably from a C declaration.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parent
REPOSITORY_ROOT = ROOT.parents[2]
BYUL_ROOT = REPOSITORY_ROOT / "byul"
MODULE_ROOT = ROOT / "byul_wrapper"

# Headers are ordered so declarations used by a module are already available
# through that module's normal Python imports.  A module may use more than one
# public header when it exposes a family of C APIs.
MODULE_HEADERS: dict[str, tuple[str, ...]] = {
    "byul_tick.py": ("byul_tick/byul_tick.h",),
    "coord.py": ("navsys/coord/coord.h",),
    "coord_list.py": ("navsys/coord/coord_list.h",),
    "coord_hash.py": ("navsys/coord/coord_hash.h",),
    "cost_coord_pq.py": ("navsys/coord/cost_coord_pq.h",),
    "dstar_lite_key.py": ("navsys/dstar_lite/dstar_lite_key.h",),
    "dstar_lite_pqueue.py": ("navsys/dstar_lite/dstar_lite_pqueue.h",),
    "navgrid.py": (
        "navsys/navgrid/navcell.h",
        "navsys/navgrid/navgrid.h",
    ),
    "route.py": ("navsys/route/route.h",),
    "route_finder_common.py": ("navsys/route_finder/route_finder_core.h",),
    "route_finder.py": (
        "navsys/coord/cost_coord_pq.h",
        "navsys/route_finder/route_finder.h",
        *tuple(
            str(path.relative_to(BYUL_ROOT)).replace("\\", "/")
            for path in sorted(
                (BYUL_ROOT / "navsys" / "route_finder").glob("*.h")
            )
            if path.name not in {"route_finder.h", "route_finder_core.h"}
        ),
    ),
    "dstar_lite.py": ("navsys/dstar_lite/dstar_lite.h",),
    "console.py": (
        "console/console.h",
        "console/dstar_lite_console.h",
    ),
}

CDEF_START = 'ffi.cdef("""'
CDEF_END = '"""'


def strip_comments(source: str) -> str:
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    return re.sub(r"//[^\n]*", "", source)


def header_to_cdef(path: Path) -> str:
    """Convert one C-compatible public header to CFFI parser input."""
    source = strip_comments(path.read_text(encoding="utf-8"))
    lines: list[str] = []
    skipping_directive = False

    for raw_line in source.splitlines():
        stripped = raw_line.strip()

        # Includes and conditional compilation are resolved by the explicit
        # module manifest and the wrapper import graph, not by CFFI.
        if skipping_directive:
            skipping_directive = raw_line.rstrip().endswith("\\")
            continue
        if stripped.startswith("#"):
            skipping_directive = raw_line.rstrip().endswith("\\")
            continue

        if stripped in {'extern "C" {', "}"}:
            continue

        line = raw_line.replace("BYUL_API", "")
        line = re.sub(r"\s+$", "", line)
        lines.append(line)

    text = "\n".join(lines).strip()
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def generated_block(headers: tuple[str, ...]) -> str:
    sections = [
        "/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */",
        "/* Do not edit this ffi.cdef block by hand. */",
    ]
    for relative in headers:
        path = BYUL_ROOT / relative
        if not path.is_file():
            raise FileNotFoundError(f"BYUL public header not found: {path}")
        sections.append(f"\n/* Source: byul/{relative} */\n{header_to_cdef(path)}")
    return "\n".join(sections).strip()


def replace_cdef(module_path: Path, cdef: str) -> str:
    source = module_path.read_text(encoding="utf-8")
    start = source.find(CDEF_START)
    if start < 0:
        raise ValueError(f"ffi.cdef block not found: {module_path}")
    body_start = start + len(CDEF_START)
    end = source.find(CDEF_END, body_start)
    if end < 0:
        raise ValueError(f"ffi.cdef block is not terminated: {module_path}")
    return source[:body_start] + "\n" + cdef + "\n" + source[end:]


def generate(check: bool) -> int:
    stale: list[Path] = []
    for module_name, headers in MODULE_HEADERS.items():
        module_path = MODULE_ROOT / module_name
        expected = replace_cdef(module_path, generated_block(headers))
        current = module_path.read_text(encoding="utf-8")
        if current == expected:
            continue
        stale.append(module_path)
        if not check:
            module_path.write_text(expected, encoding="utf-8", newline="\n")
            print(f"[GENERATED] {module_path.relative_to(REPOSITORY_ROOT)}")

    if check and stale:
        print("[ERROR] Generated CFFI declarations are stale:", file=sys.stderr)
        for path in stale:
            print(f"  {path.relative_to(REPOSITORY_ROOT)}", file=sys.stderr)
        print(
            "Run: py -3 tools/python/byul_wrapper/generate_wrapper_abi.py",
            file=sys.stderr,
        )
        return 1

    if not stale:
        print("[OK] BYUL Grid CFFI declarations are up to date.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate BYUL Grid ffi.cdef blocks from BYUL public headers."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="report stale generated declarations without modifying files",
    )
    args = parser.parse_args()
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
