from .ffi_core import ffi, C
from pathlib import Path
import os
import platform

from .coord import c_coord
from .coord_list import c_coord_list
from .coord_hash import c_coord_hash
from .route import c_route
from .navgrid import c_navgrid

from .dstar_lite_pqueue import c_dstar_lite_pqueue

from .dstar_lite import c_dstar_lite

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/console/console.h */
void navgrid_print_ascii(const navgrid_t* m);

 void navgrid_print_ascii_with_route(
    const navgrid_t* m, const route_t* p, int margin);

 void navgrid_print_ascii_with_visited_count(
    const navgrid_t* m, const route_t* p, int margin);

/* Source: byul/console/dstar_lite_console.h */
void dsl_debug_print_g_table(const navgrid_t* m, coord_hash_t* g_table);

 void dsl_debug_print_rhs_table(
    const navgrid_t* m, coord_hash_t* rhs_table);

 void dsl_debug_print_full_state(
    const dstar_lite_t* dsl,
    const coord_t* goal,
    float km,
    coord_hash_t* g_table,
    coord_hash_t* rhs_table,
    dstar_lite_pqueue_t* frontier,
    int max_range,
    int retry_limit,
    bool debug_mode,
    coord_hash_t* update_counter);

 void dsl_debug_print_state(
    const dstar_lite_t* dsl,
    const coord_t* goal,
    float km,
    coord_hash_t* g_table,
    coord_hash_t* rhs_table,
    dstar_lite_pqueue_t* frontier);

 void dsl_print_info(const dstar_lite_t* dsl);

 void dsl_print_ascii_only_navgrid(const dstar_lite_t* dsl);

 void dsl_print_ascii_route(
    const dstar_lite_t* dsl, const route_t* route, int margin);

 void dsl_print_ascii_update_count(
    const dstar_lite_t* dsl, route_t* route, int margin);
""", override=True)

class c_console:
    # ───── g / rhs 테이블 출력 ─────
    @staticmethod
    def print_g_table(m: c_navgrid, g_table: c_coord_hash):
        C.dsl_debug_print_g_table(m.ptr(), g_table.ptr())

    @staticmethod
    def print_rhs_table(m: c_navgrid, rhs_table: c_coord_hash):
        C.dsl_debug_print_rhs_table(m.ptr(), rhs_table.ptr())

    # ───── D* Lite 전체 상태 출력 ─────
    @staticmethod
    def print_full_state(
        dsl: c_dstar_lite, goal: c_coord, km: float,
        g_table: c_coord_hash, rhs_table: c_coord_hash,
        frontier: c_dstar_lite_pqueue, max_range: int, retry_limit: int,
        debug_mode: bool, update_counter: c_coord_hash
    ):
        C.dsl_debug_print_full_state(
            dsl.ptr(), goal.ptr(), km,
            g_table.ptr(), rhs_table.ptr(),
            frontier.ptr(), max_range, retry_limit,
            debug_mode, update_counter.ptr()
        )

    @staticmethod
    def print_state(
        dsl: c_dstar_lite, goal: c_coord, km: float,
        g_table: c_coord_hash, rhs_table: c_coord_hash,
        frontier: c_dstar_lite_pqueue
    ):
        C.dsl_debug_print_state(
            dsl.ptr(), goal.ptr(), km,
            g_table.ptr(), rhs_table.ptr(), frontier.ptr()
        )

    # ───── D* Lite 기본 정보 출력 ─────
    @staticmethod
    def print_info(dsl: c_dstar_lite):
        C.dsl_print_info(dsl.ptr())

    # ───── 맵 ASCII 출력 (경로 없음) ─────
    @staticmethod
    def print_ascii_only_map(dsl: c_dstar_lite):
        C.dsl_print_ascii_only_navgrid(dsl.ptr())

    # ───── 맵 + 경로 출력 ─────
    @staticmethod
    def print_ascii_route(dsl: c_dstar_lite, route: c_route, margin: int = 0):
        C.dsl_print_ascii_route(dsl.ptr(), route.ptr(), margin)

    # ───── 맵 + 방문 횟수 출력 ─────
    @staticmethod
    def print_ascii_update_count(dsl: c_dstar_lite, route: c_route, margin: int = 0):
        C.dsl_print_ascii_update_count(dsl.ptr(), route.ptr(), margin)

    # ───── 단독 맵 출력 (navgrid용) ─────
    @staticmethod
    def print_ascii_navgrid_only(m):
        C.navgrid_print_ascii(m.ptr())

    # ───── 경로 포함 출력 ─────
    @staticmethod
    def print_ascii_with_route(m : c_navgrid, route: c_route, margin: int = 0):
        C.navgrid_print_ascii_with_route(m.ptr(), route.ptr(), margin)

    # ───── 방문횟수 포함 출력 ─────
    @staticmethod
    def print_ascii_with_visited_count(m : c_navgrid, route: c_route, margin: int = 0):
        C.navgrid_print_ascii_with_visited_count(m.ptr(), route.ptr(), margin)
