from .ffi_core import ffi, C
from .navsys_status import NavsysStatus, raise_for_status
import weakref

from .coord import c_coord
from .coord_list import c_coord_list

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/coord/coord_hash.h */
typedef struct s_coord_hash coord_hash_t;
typedef struct s_coord_hash_iter coord_hash_iter_t;

typedef void* (*coord_hash_copy_func)(const void* value);
typedef void  (*coord_hash_destroy_func)(void* value);

typedef navsys_status_t (*coord_hash_value_copy_func_ex)(
    const void* source, void** out_copy, void* userdata);

typedef void (*coord_hash_value_destroy_func_ex)(
    void* value, void* userdata);

typedef bool (*coord_hash_value_equal_func_ex)(
    const void* lhs, const void* rhs, void* userdata);

typedef struct s_coord_hash_create_info {
    uint32_t struct_size;
    uint32_t abi_version;
    coord_hash_value_copy_func_ex copy_value;
    coord_hash_value_destroy_func_ex destroy_value;
    coord_hash_value_equal_func_ex equal_value;
    void* userdata;
} coord_hash_create_info_t;

 navsys_status_t coord_hash_create_ex(
    const coord_hash_create_info_t* info, coord_hash_t** out_hash);

 navsys_status_t coord_hash_copy_ex(
    const coord_hash_t* source, coord_hash_t** out_hash);

 navsys_status_t coord_hash_insert_copy(
    coord_hash_t* hash, const coord_t* key, const void* value);

 navsys_status_t coord_hash_replace_copy(
    coord_hash_t* hash, const coord_t* key, const void* value);

 navsys_status_t coord_hash_upsert_copy(
    coord_hash_t* hash, const coord_t* key, const void* value,
    bool* out_inserted);

 void* coord_hash_int_copy(const void* value);

 void coord_hash_int_destroy(void* value);

 void* coord_hash_float_copy(const void* value);

 void coord_hash_float_destroy(void* value);

 void* coord_hash_double_copy(const void* value);

 void coord_hash_double_destroy(void* value);

typedef struct s_coord_hash_entry_view {
    coord_t key;
    const void* value;
} coord_hash_entry_view_t;

 size_t coord_hash_size(const coord_hash_t* hash);

 navsys_status_t coord_hash_find(
    const coord_hash_t* hash, const coord_t* key,
    const void** out_borrowed_value, bool* out_found);

 navsys_status_t coord_hash_equal_keys(
    const coord_hash_t* a, const coord_hash_t* b, bool* out_equal);

 navsys_status_t coord_hash_equal_full(
    const coord_hash_t* a, const coord_hash_t* b, bool* out_equal);

 navsys_status_t coord_hash_export_keys(
    const coord_hash_t* hash, coord_t* out_keys,
    size_t capacity, size_t* out_count);

 navsys_status_t coord_hash_export_entries(
    const coord_hash_t* hash, coord_hash_entry_view_t* out_entries,
    size_t capacity, size_t* out_count);

 navsys_status_t coord_hash_iter_next_ex(
    coord_hash_iter_t* iter, coord_t* key_out, const void** value_out);

 navsys_status_t coord_hash_format(
    const coord_hash_t* hash, char* out_buffer,
    size_t capacity, size_t* out_required);

 void* int_copy(const void* p);

 void int_destroy(void* p);

 void* scalar_copy(const void* p);

 void scalar_destroy(void* p);

 void* double_copy(const void* p);

 void double_destroy(void* p);

 coord_hash_t* coord_hash_create();

 coord_hash_t* coord_hash_create_full(coord_hash_copy_func copy_func,
                                  coord_hash_destroy_func destroy_func);

 void          coord_hash_destroy(coord_hash_t* hash);
 coord_hash_t* coord_hash_copy(const coord_hash_t* original);

 uint32_t coord_hash_hash(const coord_hash_t* h);

 int   coord_hash_length(const coord_hash_t* hash);
 bool  coord_hash_is_empty(const coord_hash_t* hash);

 void* coord_hash_get(const coord_hash_t* hash, const coord_t* key);

 void* coord_hash_get_xy(const coord_hash_t* hash, int x, int y);

 bool  coord_hash_contains(
    const coord_hash_t* hash, const coord_t* key);

 void  coord_hash_set(coord_hash_t* hash,
    const coord_t* key, void* value);

 bool  coord_hash_insert(coord_hash_t* hash,
    const coord_t* key, void* value);

 bool coord_hash_insert_xy(
    coord_hash_t* hash, int x, int y, void* value);

 bool coord_hash_replace(coord_hash_t* hash,
    const coord_t* key, void* value);

 bool coord_hash_replace_xy(
    coord_hash_t* hash, int x, int y, void* value);

 bool  coord_hash_remove(coord_hash_t* hash, const coord_t* key);
 void  coord_hash_clear(coord_hash_t* hash);
 void  coord_hash_remove_all(coord_hash_t* hash);

 bool  coord_hash_equal(const coord_hash_t* a, const coord_hash_t* b);

 coord_list_t* coord_hash_keys(const coord_hash_t* hash);

 void**        coord_hash_values(
    const coord_hash_t* hash, int* out_count);

typedef void (*coord_hash_func)(
    const coord_t* key, void* value, void* user_data);

 void  coord_hash_foreach(
    coord_hash_t* hash, coord_hash_func func, void* user_data);

 coord_list_t* coord_hash_to_list(const coord_hash_t* hash);

 void coord_hash_export(
    const coord_hash_t* hash,
    coord_list_t* keys_out,
    void** values_out,
    int* count_out);

 coord_hash_iter_t* coord_hash_iter_create(
    const coord_hash_t* hash);

 bool coord_hash_iter_next(
    coord_hash_iter_t* iter, coord_t* key_out, void** val_out);

 void coord_hash_iter_destroy(
    coord_hash_iter_t* iter);

 char* coord_hash_to_string(const coord_hash_t* hash);
 void coord_hash_print(const coord_hash_t* hash);

 void coord_hash_buffer_destroy(void* buffer);
""")

_VALUE_CODECS = {
    "int": ("int", C.coord_hash_int_copy, C.coord_hash_int_destroy),
    "float": ("float", C.coord_hash_float_copy, C.coord_hash_float_destroy),
    "double": ("double", C.coord_hash_double_copy, C.coord_hash_double_destroy),
    "none": (None, ffi.NULL, ffi.NULL),
}


class c_coord_hash:
    """Typed coord map backed by the checked coord-hash API.

    ``value_type`` is an explicit native codec: ``int``, ``float``, ``double``
    or ``none``. Borrowed maps retain their parent wrapper for their lifetime.
    """

    def __init__(
        self,
        raw_ptr=None,
        own=False,
        *,
        value_type="int",
        parent=None,
    ):
        if value_type not in _VALUE_CODECS:
            raise ValueError(
                "value_type must be 'int', 'float', 'double', or 'none'"
            )
        if raw_ptr is not None and not own and parent is None:
            raise ValueError("borrowed coord hash requires parent")

        self._c = ffi.NULL
        self._own = False
        self._finalizer = None
        self._parent = parent
        self._value_type = value_type
        self._ctype, copy_func, destroy_func = _VALUE_CODECS[value_type]

        if raw_ptr is not None:
            if raw_ptr == ffi.NULL:
                raise ValueError("raw_ptr must not be NULL")
            self._c = raw_ptr
            self._own = own
        else:
            self._c = C.coord_hash_create_full(copy_func, destroy_func)
            if self._c == ffi.NULL:
                raise MemoryError("coord_hash allocation failed")
            self._own = True

        if self._own:
            self._finalizer = weakref.finalize(
                self, C.coord_hash_destroy, self._c
            )

    def _require_open(self):
        if self._c == ffi.NULL:
            raise ReferenceError("c_coord_hash is closed")
        return self._c

    @staticmethod
    def _require_key(key):
        if not isinstance(key, c_coord):
            raise TypeError("key must be c_coord")
        return key.ptr()

    def _encode(self, value):
        if self._ctype is None:
            if value is not None:
                raise TypeError("a 'none' coord hash accepts only None values")
            return ffi.NULL
        if value is None:
            return ffi.NULL
        return ffi.new(f"{self._ctype}*", value)

    def _decode(self, value):
        if value == ffi.NULL:
            return None
        if self._ctype is None:
            raise RuntimeError("a 'none' coord hash contains a non-NULL value")
        return value and ffi.cast(f"{self._ctype}*", value)[0]

    def __len__(self):
        return int(C.coord_hash_size(self._require_open()))

    def empty(self):
        return len(self) == 0

    def get(self, key: c_coord, default=None):
        value = ffi.new("const void**")
        found = ffi.new("bool*")
        raise_for_status(
            C.coord_hash_find(
                self._require_open(), self._require_key(key), value, found
            ),
            "coord_hash_find",
        )
        return self._decode(value[0]) if found[0] else default

    def contains(self, key: c_coord):
        value = ffi.new("const void**")
        found = ffi.new("bool*")
        raise_for_status(
            C.coord_hash_find(
                self._require_open(), self._require_key(key), value, found
            ),
            "coord_hash_find",
        )
        return bool(found[0])

    def insert(self, key: c_coord, value):
        encoded = self._encode(value)
        raise_for_status(
            C.coord_hash_insert_copy(
                self._require_open(), self._require_key(key), encoded
            ),
            "coord_hash_insert_copy",
        )
        return True

    def replace(self, key: c_coord, value):
        encoded = self._encode(value)
        raise_for_status(
            C.coord_hash_replace_copy(
                self._require_open(), self._require_key(key), encoded
            ),
            "coord_hash_replace_copy",
        )
        return True

    def upsert(self, key: c_coord, value):
        encoded = self._encode(value)
        inserted = ffi.new("bool*")
        raise_for_status(
            C.coord_hash_upsert_copy(
                self._require_open(),
                self._require_key(key),
                encoded,
                inserted,
            ),
            "coord_hash_upsert_copy",
        )
        return bool(inserted[0])

    def remove(self, key: c_coord):
        return bool(
            C.coord_hash_remove(self._require_open(), self._require_key(key))
        )

    def clear(self):
        C.coord_hash_clear(self._require_open())

    def copy(self):
        output = ffi.new("coord_hash_t**")
        raise_for_status(
            C.coord_hash_copy_ex(self._require_open(), output),
            "coord_hash_copy_ex",
        )
        return c_coord_hash(
            raw_ptr=output[0], own=True, value_type=self._value_type
        )

    def equals(self, other):
        if not isinstance(other, c_coord_hash):
            return False
        equal = ffi.new("bool*")
        raise_for_status(
            C.coord_hash_equal_keys(
                self._require_open(), other._require_open(), equal
            ),
            "coord_hash_equal_keys",
        )
        return bool(equal[0])

    def entries(self):
        required = ffi.new("size_t*")
        raise_for_status(
            C.coord_hash_export_entries(
                self._require_open(), ffi.NULL, 0, required
            ),
            "coord_hash_export_entries",
        )
        if required[0] == 0:
            return []
        output = ffi.new("coord_hash_entry_view_t[]", required[0])
        raise_for_status(
            C.coord_hash_export_entries(
                self._require_open(), output, required[0], required
            ),
            "coord_hash_export_entries",
        )
        return [
            (
                c_coord(output[index].key.x, output[index].key.y),
                self._decode(output[index].value),
            )
            for index in range(required[0])
        ]

    def keys(self):
        return [key for key, _ in self.entries()]

    def values(self):
        return [value for _, value in self.entries()]

    def export(self):
        entries = self.entries()
        return [key for key, _ in entries], [value for _, value in entries]

    def foreach(self, func):
        if not callable(func):
            raise TypeError("foreach requires a callable")
        for key, value in self:
            func(key, value)

    def format(self):
        required = ffi.new("size_t*")
        raise_for_status(
            C.coord_hash_format(self._require_open(), ffi.NULL, 0, required),
            "coord_hash_format",
        )
        output = ffi.new("char[]", required[0])
        raise_for_status(
            C.coord_hash_format(
                self._require_open(), output, required[0], required
            ),
            "coord_hash_format",
        )
        return ffi.string(output).decode("utf-8")

    def __iter__(self):
        return c_coord_hash_iter(self)

    def ptr(self):
        return self._require_open()

    def close(self):
        if self._c == ffi.NULL:
            return
        if self._own and self._finalizer and self._finalizer.alive:
            self._finalizer()
        self._c = ffi.NULL
        self._parent = None

    def __del__(self):
        self.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()

    def __repr__(self):
        return f"c_coord_hash(value_type={self._value_type!r}, len={len(self)})"


class c_coord_hash_iter:
    def __init__(self, hash_obj: c_coord_hash):
        if not isinstance(hash_obj, c_coord_hash):
            raise TypeError("hash_obj must be c_coord_hash")
        self._parent = hash_obj
        self._iter = C.coord_hash_iter_create(hash_obj.ptr())
        if self._iter == ffi.NULL:
            self._parent = None
            raise MemoryError("coord_hash_iter allocation failed")

    def __iter__(self):
        return self

    def __next__(self):
        if self._iter == ffi.NULL:
            raise StopIteration
        key = ffi.new("coord_t*")
        value = ffi.new("const void**")
        status = NavsysStatus(C.coord_hash_iter_next_ex(
            self._iter, key, value
        ))
        if status is NavsysStatus.NOT_FOUND:
            self.close()
            raise StopIteration
        raise_for_status(status, "coord_hash_iter_next_ex")
        return (
            c_coord(key.x, key.y),
            self._parent._decode(value[0]),
        )

    def close(self):
        if self._iter != ffi.NULL:
            C.coord_hash_iter_destroy(self._iter)
            self._iter = ffi.NULL
        self._parent = None

    def __del__(self):
        self.close()
