from .ffi_core import ffi, C
from .navsys_status import raise_for_status
import weakref

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/coord/coord.h */
typedef struct s_coord {
    int x;
    int y;
} coord_t;

 size_t coord_sizeof(void);

 size_t coord_alignof(void);

 size_t coord_offsetof_x(void);

 size_t coord_offsetof_y(void);

 navsys_status_t coord_init_checked(
    coord_t* out_coord, int32_t x, int32_t y);

 navsys_status_t coord_create_checked(
    int32_t x, int32_t y, coord_t** out_coord);

 navsys_status_t coord_copy_checked(
    const coord_t* source, coord_t** out_coord);

 navsys_status_t coord_add_checked(
    coord_t* out, const coord_t* a, const coord_t* b);

 navsys_status_t coord_sub_checked(
    coord_t* out, const coord_t* a, const coord_t* b);

 navsys_status_t coord_mul_checked(
    coord_t* out, const coord_t* a, int32_t scalar);

 navsys_status_t coord_div_checked(
    coord_t* out, const coord_t* a, int32_t scalar);

 navsys_status_t coord_compare_canonical(
    const coord_t* a, const coord_t* b, int* out_order);

 navsys_status_t coord_distance_f64(
    const coord_t* a, const coord_t* b, double* out_distance);

 navsys_status_t coord_manhattan_distance_i64(
    const coord_t* a, const coord_t* b, int64_t* out_distance);

 navsys_status_t coord_angle_rad(
    const coord_t* from, const coord_t* to, double* out_angle);

 navsys_status_t coord_angle_deg(
    const coord_t* from, const coord_t* to, double* out_angle);

 navsys_status_t coord_step_toward(
    const coord_t* start, const coord_t* goal, coord_t* out_next);

 navsys_status_t coord_format(
    const coord_t* coord,
    char* out_buffer,
    size_t capacity,
    size_t* out_required);

 coord_t* coord_create_full(int x, int y);

 coord_t* coord_create(void);

 void coord_destroy(coord_t* c);

 coord_t* coord_copy(const coord_t* c);

 void coord_init(coord_t* c);

 void coord_init_full(coord_t* c, int x, int y);

 void coord_assign(coord_t* dst, const coord_t* src);

 void coord_add(coord_t* dst, const coord_t* a, const coord_t* b);

 void coord_sub(coord_t* dst, const coord_t* a, const coord_t* b);

 void coord_mul(coord_t* dst, const coord_t* a, int scalar);

 void coord_div(coord_t* dst, const coord_t* a, int scalar);

 void coord_iadd(coord_t* c, const coord_t* other);

 void coord_isub(coord_t* c, const coord_t* other);

 void coord_imul(coord_t* c, int scalar);

 void coord_idiv(coord_t* c, int scalar);

 unsigned coord_hash(const coord_t* c);
 bool     coord_equal(const coord_t* c1, const coord_t* c2);
 int      coord_compare(const coord_t* c1, const coord_t* c2);

 float    coord_distance(const coord_t* a, const coord_t* b);

 int      coord_manhattan_distance(const coord_t* a, const coord_t* b);

 double coord_angle(const coord_t* a, const coord_t* b);

 double coord_degree(const coord_t* a, const coord_t* b);

 void coord_next_to_goal(
    coord_t* out,
    const coord_t* start,
    const coord_t* goal);

 int      coord_get_x(const coord_t* c);
 void     coord_set_x(coord_t* c, int x);

 int      coord_get_y(const coord_t* c);
 void     coord_set_y(coord_t* c, int y);

 void     coord_set(coord_t* c, int x, int y);
 void     coord_fetch(const coord_t* c, int* out_x, int* out_y);

 coord_t make_tmp_coord(int x, int y);

 coord_t* coord_clone_next_to_goal(
    const coord_t* start, const coord_t* goal);

 char* coord_to_string(
    const coord_t* c, size_t buffer_size, char* buffer);

 void coord_print(const coord_t* c);
""")

COORD_MAX = 200000000
COORD_MIN = -200000000

class c_coord:
    """Low-level Python wrapper for the native ``coord_t`` object.

    This is the complete coordinate API exposed by ``byul_wrapper``.  It owns
    newly created native coordinates and supports explicit ``close()`` and
    context-manager cleanup.
    """

    def __init__(self, x=0, y=0, raw_ptr=None, own=False):
        self._c = ffi.NULL
        self._own = False
        self._finalizer = None
        if raw_ptr is not None:
            if raw_ptr == ffi.NULL:
                raise ValueError("raw_ptr must not be NULL")
            self._c = raw_ptr
            self._own = own
        else:
            output = ffi.new("coord_t**")
            raise_for_status(
                C.coord_create_checked(x, y, output),
                "coord_create_checked",
            )
            self._c = output[0]
            self._own = True

        if self._own:
            self._finalizer = weakref.finalize(self, C.coord_destroy, self._c)

    def _require_open(self):
        if self._c == ffi.NULL:
            raise ReferenceError("c_coord is closed")
        return self._c

    @staticmethod
    def _require_coord(value, argument):
        if not isinstance(value, c_coord):
            raise TypeError(f"{argument} must be c_coord")
        return value._require_open()

    def _replace_checked(self, x: int, y: int):
        raise_for_status(
            C.coord_init_checked(self._require_open(), x, y),
            "coord_init_checked",
        )

    @property
    def x(self):
        return C.coord_get_x(self._require_open())

    @x.setter
    def x(self, value):
        self._replace_checked(value, self.y)

    @property
    def y(self):
        return C.coord_get_y(self._require_open())

    @y.setter
    def y(self, value):
        self._replace_checked(self.x, value)

    def init_full(self, x: int, y: int):
        self._replace_checked(x, y)

    def set(self, x: int, y: int):
        self._replace_checked(x, y)

    def copy(self):
        output = ffi.new("coord_t**")
        raise_for_status(
            C.coord_copy_checked(self._require_open(), output),
            "coord_copy_checked",
        )
        return c_coord(raw_ptr=output[0], own=True)

    def distance(self, other: 'c_coord'):
        output = ffi.new("double*")
        raise_for_status(
            C.coord_distance_f64(
                self._require_open(),
                self._require_coord(other, "other"),
                output,
            ),
            "coord_distance_f64",
        )
        return output[0]

    def manhattan_distance(self, other: 'c_coord'):
        output = ffi.new("int64_t*")
        raise_for_status(
            C.coord_manhattan_distance_i64(
                self._require_open(),
                self._require_coord(other, "other"),
                output,
            ),
            "coord_manhattan_distance_i64",
        )
        return output[0]

    def degree(self, other: 'c_coord'):
        output = ffi.new("double*")
        raise_for_status(
            C.coord_angle_deg(
                self._require_open(),
                self._require_coord(other, "other"),
                output,
            ),
            "coord_angle_deg",
        )
        return output[0]

    def __eq__(self, other):
        if not isinstance(other, c_coord):
            return NotImplemented
        return C.coord_equal(
            self._require_open(), other._require_open()
        ) != 0

    def __lt__(self, other):
        output = ffi.new("int*")
        raise_for_status(
            C.coord_compare_canonical(
                self._require_open(),
                self._require_coord(other, "other"),
                output,
            ),
            "coord_compare_canonical",
        )
        return output[0] < 0

    def __ge__(self, other):
        return not self < other

    __hash__ = None

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass

    def close(self):
        finalizer = getattr(self, "_finalizer", None)
        if getattr(self, "_own", False) and finalizer and finalizer.alive:
            finalizer()
        self._c = ffi.NULL
        self._own = False

    def __enter__(self):
        self._require_open()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()

    def __add__(self, other):
        result = c_coord()
        try:
            raise_for_status(
                C.coord_add_checked(
                    result._require_open(),
                    self._require_open(),
                    self._require_coord(other, "other"),
                ),
                "coord_add_checked",
            )
            return result
        except Exception:
            result.close()
            raise

    def __sub__(self, other):
        result = c_coord()
        try:
            raise_for_status(
                C.coord_sub_checked(
                    result._require_open(),
                    self._require_open(),
                    self._require_coord(other, "other"),
                ),
                "coord_sub_checked",
            )
            return result
        except Exception:
            result.close()
            raise

    def __mul__(self, scalar: int):
        result = c_coord()
        try:
            raise_for_status(
                C.coord_mul_checked(
                    result._require_open(), self._require_open(), scalar
                ),
                "coord_mul_checked",
            )
            return result
        except Exception:
            result.close()
            raise

    def __floordiv__(self, scalar: int):
        result = c_coord()
        try:
            raise_for_status(
                C.coord_div_checked(
                    result._require_open(), self._require_open(), scalar
                ),
                "coord_div_checked",
            )
            return result
        except Exception:
            result.close()
            raise

    def format(self):
        required = ffi.new("size_t*")
        raise_for_status(
            C.coord_format(self._require_open(), ffi.NULL, 0, required),
            "coord_format",
        )
        buffer = ffi.new("char[]", required[0])
        raise_for_status(
            C.coord_format(
                self._require_open(), buffer, required[0], required
            ),
            "coord_format",
        )
        return ffi.string(buffer).decode("utf-8")

    def __str__(self):
        return f"c_coord(x={self.x}, y={self.y})"

    def __repr__(self):
        return str(self)

    def to_tuple(self):
        return (self.x, self.y)

    def ptr(self):
        return self._require_open()

    @staticmethod
    def from_tuple(t: tuple):
        return c_coord(*t)

# Constants accessible from Python side
c_coord.COORD_MAX = COORD_MAX
c_coord.COORD_MIN = COORD_MIN
