import weakref

from .ffi_core import ffi, C

from .coord import c_coord
from .navsys_status import NavsysStatus, raise_for_status

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/coord/cost_coord_pq.h */
typedef struct s_cost_coord_pq cost_coord_pq_t;

typedef struct s_cost_coord_pq_create_info {
    uint32_t struct_size;
    uint32_t abi_version;
    uint32_t flags;
} cost_coord_pq_create_info_t;

 navsys_status_t cost_coord_pq_create_ex(
    const cost_coord_pq_create_info_t* info,
    cost_coord_pq_t** out_queue);

 navsys_status_t cost_coord_pq_push_ex(
    cost_coord_pq_t* queue, float cost, const coord_t* coord);

 navsys_status_t cost_coord_pq_peek_min(
    const cost_coord_pq_t* queue,
    float* out_cost,
    coord_t* out_coord);

 navsys_status_t cost_coord_pq_pop_min(
    cost_coord_pq_t* queue,
    float* out_cost,
    coord_t* out_coord);

 size_t cost_coord_pq_size(const cost_coord_pq_t* queue);

 bool cost_coord_pq_empty(const cost_coord_pq_t* queue);

 navsys_status_t cost_coord_pq_remove_one(
    cost_coord_pq_t* queue,
    float cost,
    const coord_t* coord,
    bool* out_removed);

 navsys_status_t cost_coord_pq_remove_all(
    cost_coord_pq_t* queue,
    const coord_t* coord,
    size_t* out_removed_count);

 void cost_coord_pq_clear(cost_coord_pq_t* queue);

 navsys_status_t cost_coord_pq_trim_to_size(
    cost_coord_pq_t* queue,
    size_t max_size,
    size_t* out_removed_count);

 cost_coord_pq_t* cost_coord_pq_create(void);

 void cost_coord_pq_destroy(cost_coord_pq_t* pq);

 void cost_coord_pq_push(
    cost_coord_pq_t* pq, float cost, const coord_t* c);

 coord_t* cost_coord_pq_peek(cost_coord_pq_t* pq);

 coord_t* cost_coord_pq_pop(cost_coord_pq_t* pq);

 float cost_coord_pq_peek_cost(cost_coord_pq_t* pq);

 bool cost_coord_pq_is_empty(cost_coord_pq_t* pq);

 bool cost_coord_pq_contains(
    cost_coord_pq_t* pq, const coord_t* c);

 bool cost_coord_pq_remove(
    cost_coord_pq_t* pq, float cost, const coord_t* c);

 int cost_coord_pq_length(cost_coord_pq_t* pq);

 void cost_coord_pq_trim_worst(cost_coord_pq_t* pq, int n);
""")

class c_cost_coord_pq:
    def __init__(self, raw_ptr=None, own=False):
        self._c = ffi.NULL
        self._own = False
        self._finalizer = None
        if raw_ptr is not None:
            if raw_ptr == ffi.NULL:
                raise ValueError("raw_ptr must not be NULL")
            self._c = raw_ptr
            self._own = own
        else:
            info = ffi.new("cost_coord_pq_create_info_t*")
            info.struct_size = ffi.sizeof("cost_coord_pq_create_info_t")
            info.abi_version = 1
            output = ffi.new("cost_coord_pq_t**")
            raise_for_status(
                C.cost_coord_pq_create_ex(info, output),
                "cost_coord_pq_create_ex",
            )
            self._c = output[0]
            self._own = True

        if self._own:
            self._finalizer = weakref.finalize(
                self, C.cost_coord_pq_destroy, self._c
            )

    def _require_open(self):
        if self._c == ffi.NULL:
            raise ReferenceError("c_cost_coord_pq is closed")
        return self._c

    @staticmethod
    def _require_coord(value, argument):
        if not isinstance(value, c_coord):
            raise TypeError(f"{argument} must be c_coord")
        return value._require_open()

    def _read_min(self, pop):
        result = c_coord()
        cost = ffi.new("float*")
        operation = "cost_coord_pq_pop_min" if pop else "cost_coord_pq_peek_min"
        function = C.cost_coord_pq_pop_min if pop else C.cost_coord_pq_peek_min
        status = function(self._require_open(), cost, result._require_open())
        if status == NavsysStatus.NOT_FOUND:
            result.close()
            if pop:
                raise IndexError("pop from empty c_cost_coord_pq")
            return None
        try:
            raise_for_status(status, operation)
        except Exception:
            result.close()
            raise
        return (float(cost[0]), result)

    def push(self, cost: float, coord: c_coord):
        raise_for_status(
            C.cost_coord_pq_push_ex(
                self._require_open(),
                cost,
                self._require_coord(coord, "coord"),
            ),
            "cost_coord_pq_push_ex",
        )
        return True

    def peek(self):
        return self.peek_min()

    def peek_min(self):
        """Return the minimum ``(cost, coord)`` as a caller-owned value."""
        return self._read_min(pop=False)

    def peek_cost(self):
        result = self.peek_min()
        if result is None:
            return None
        cost, coord = result
        coord.close()
        return cost

    def pop(self):
        return self.pop_min()

    def pop_min(self):
        """Remove and return the minimum ``(cost, coord)`` value."""
        return self._read_min(pop=True)

    def contains(self, coord: c_coord):
        return bool(
            C.cost_coord_pq_contains(
                self._require_open(), self._require_coord(coord, "coord")
            )
        )

    def remove(self, cost: float, coord: c_coord):
        removed = ffi.new("bool*")
        raise_for_status(
            C.cost_coord_pq_remove_one(
                self._require_open(),
                cost,
                self._require_coord(coord, "coord"),
                removed,
            ),
            "cost_coord_pq_remove_one",
        )
        return bool(removed[0])

    def remove_all(self, coord: c_coord):
        removed = ffi.new("size_t*")
        raise_for_status(
            C.cost_coord_pq_remove_all(
                self._require_open(),
                self._require_coord(coord, "coord"),
                removed,
            ),
            "cost_coord_pq_remove_all",
        )
        return int(removed[0])

    def clear(self):
        C.cost_coord_pq_clear(self._require_open())

    def trim_to_size(self, max_size: int):
        if not isinstance(max_size, int):
            raise TypeError("max_size must be int")
        if max_size < 0:
            raise ValueError("max_size must be nonnegative")
        removed = ffi.new("size_t*")
        raise_for_status(
            C.cost_coord_pq_trim_to_size(
                self._require_open(), max_size, removed
            ),
            "cost_coord_pq_trim_to_size",
        )
        return int(removed[0])

    def trim_worst(self, n: int):
        if not isinstance(n, int):
            raise TypeError("n must be int")
        if n < 0:
            raise ValueError("n must be nonnegative")
        return self.trim_to_size(max(0, len(self) - n))

    def __len__(self):
        return int(C.cost_coord_pq_size(self._require_open()))

    def is_empty(self):
        return bool(C.cost_coord_pq_empty(self._require_open()))

    def ptr(self):
        return self._require_open()

    def __repr__(self):
        return f"c_cost_coord_pq(len={len(self)})"

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass

    def close(self):
        finalizer = getattr(self, "_finalizer", None)
        if getattr(self, "_own", False) and finalizer and finalizer.alive:
            finalizer()
        self._c = ffi.NULL
        self._own = False

    def __enter__(self):
        self._require_open()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
