import weakref

from .ffi_core import ffi, C

from .coord import c_coord

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/coord/cost_coord_pq.h */
typedef struct s_cost_coord_pq cost_coord_pq_t;

typedef struct s_cost_coord_pq_create_info {
    uint32_t struct_size;
    uint32_t abi_version;
    uint32_t flags;
} cost_coord_pq_create_info_t;

 navsys_status_t cost_coord_pq_create_ex(
    const cost_coord_pq_create_info_t* info,
    cost_coord_pq_t** out_queue);

 navsys_status_t cost_coord_pq_push_ex(
    cost_coord_pq_t* queue, float cost, const coord_t* coord);

 navsys_status_t cost_coord_pq_peek_min(
    const cost_coord_pq_t* queue,
    float* out_cost,
    coord_t* out_coord);

 navsys_status_t cost_coord_pq_pop_min(
    cost_coord_pq_t* queue,
    float* out_cost,
    coord_t* out_coord);

 size_t cost_coord_pq_size(const cost_coord_pq_t* queue);

 bool cost_coord_pq_empty(const cost_coord_pq_t* queue);

 navsys_status_t cost_coord_pq_remove_one(
    cost_coord_pq_t* queue,
    float cost,
    const coord_t* coord,
    bool* out_removed);

 navsys_status_t cost_coord_pq_remove_all(
    cost_coord_pq_t* queue,
    const coord_t* coord,
    size_t* out_removed_count);

 void cost_coord_pq_clear(cost_coord_pq_t* queue);

 navsys_status_t cost_coord_pq_trim_to_size(
    cost_coord_pq_t* queue,
    size_t max_size,
    size_t* out_removed_count);

 cost_coord_pq_t* cost_coord_pq_create(void);

 void cost_coord_pq_destroy(cost_coord_pq_t* pq);

 void cost_coord_pq_push(
    cost_coord_pq_t* pq, float cost, const coord_t* c);

 coord_t* cost_coord_pq_peek(cost_coord_pq_t* pq);

 coord_t* cost_coord_pq_pop(cost_coord_pq_t* pq);

 float cost_coord_pq_peek_cost(cost_coord_pq_t* pq);

 bool cost_coord_pq_is_empty(cost_coord_pq_t* pq);

 bool cost_coord_pq_contains(
    cost_coord_pq_t* pq, const coord_t* c);

 bool cost_coord_pq_remove(
    cost_coord_pq_t* pq, float cost, const coord_t* c);

 int cost_coord_pq_length(cost_coord_pq_t* pq);

 void cost_coord_pq_trim_worst(cost_coord_pq_t* pq, int n);
""")

class c_cost_coord_pq:
    def __init__(self, raw_ptr=None, own=False):
        if raw_ptr:
            self._c = raw_ptr
            self._own = own
        else:
            self._c = C.cost_coord_pq_create()
            if not self._c:
                raise MemoryError("cost_coord_pq allocation failed")
            self._own = True

        if self._own:
            self._finalizer = weakref.finalize(self, C.cost_coord_pq_destroy, self._c)
        else:
            self._finalizer = None

    def push(self, cost: float, coord: c_coord):
        C.cost_coord_pq_push(self._c, cost, coord.ptr())

    def peek(self):
        ptr = C.cost_coord_pq_peek(self._c)
        return c_coord(raw_ptr=ptr) if ptr != ffi.NULL else None

    def peek_cost(self):
        return C.cost_coord_pq_peek_cost(self._c)

    def pop(self):
        ptr = C.cost_coord_pq_pop(self._c)
        return c_coord(raw_ptr=ptr) if ptr != ffi.NULL else None

    def contains(self, coord: c_coord):
        return bool(C.cost_coord_pq_contains(self._c, coord.ptr()))

    def remove(self, cost: float, coord: c_coord):
        return bool(C.cost_coord_pq_remove(self._c, cost, coord.ptr()))

    def trim_worst(self, n: int):
        C.cost_coord_pq_trim_worst(self._c, n)

    def __len__(self):
        return C.cost_coord_pq_length(self._c)

    def is_empty(self):
        return bool(C.cost_coord_pq_is_empty(self._c))

    def ptr(self):
        return self._c

    def __repr__(self):
        return f"c_cost_coord_pq(len={len(self)})"

    def __del__(self):
        self.close()

    def close(self):
        if self._own and self._finalizer and self._finalizer.alive:
            self._finalizer()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
