from functools import total_ordering
import weakref

from .ffi_core import ffi, C
from .navsys_status import raise_for_status

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/dstar_lite/dstar_lite_key.h */
typedef struct s_dstar_lite_key {
    float k1;
    float k2;
} dstar_lite_key_t;

 size_t dstar_lite_key_sizeof(void);

 size_t dstar_lite_key_alignof(void);

 size_t dstar_lite_key_offsetof_k1(void);

 size_t dstar_lite_key_offsetof_k2(void);

 navsys_status_t dstar_lite_key_init(
    dstar_lite_key_t* out_key, float k1, float k2);

 navsys_status_t dstar_lite_key_create_ex(
    float k1, float k2, dstar_lite_key_t** out_key);

 navsys_status_t dstar_lite_key_copy_ex(
    const dstar_lite_key_t* source,
    dstar_lite_key_t** out_key);

 bool dstar_lite_key_equal_exact(
    const dstar_lite_key_t* lhs,
    const dstar_lite_key_t* rhs);

 navsys_status_t dstar_lite_key_compare_exact(
    const dstar_lite_key_t* lhs,
    const dstar_lite_key_t* rhs,
    int* out_compare);

 uint32_t dstar_lite_key_hash_exact(
    const dstar_lite_key_t* key);

 navsys_status_t dstar_lite_key_is_close(
    const dstar_lite_key_t* lhs,
    const dstar_lite_key_t* rhs,
    float absolute_tolerance,
    float relative_tolerance,
    bool* out_is_close);

 dstar_lite_key_t* dstar_lite_key_create(void);

 dstar_lite_key_t* dstar_lite_key_create_full(float k1, float k2);

 dstar_lite_key_t* dstar_lite_key_copy(const dstar_lite_key_t* key);

 void dstar_lite_key_destroy(dstar_lite_key_t* key);

 bool dstar_lite_key_equal(
    const dstar_lite_key_t* dsk0,
    const dstar_lite_key_t* dsk1);

 int dstar_lite_key_compare(
    const dstar_lite_key_t* dsk0,
    const dstar_lite_key_t* dsk1);

 unsigned int dstar_lite_key_hash(const dstar_lite_key_t* key);
""")

@total_ordering
class c_dstar_lite_key:
    """Immutable canonical D* Lite key backed by the native C ABI.

    Equality, ordering, and hashing use one exact canonical relation.  The
    ``ptr()`` returns a detached canonical snapshot for native interoperability,
    so external field writes cannot mutate the value or its hash.  Approximate
    comparisons require an explicit ``is_close`` call.
    """

    def __init__(self, k1=0.0, k2=0.0, raw_ptr=None, own=False):
        self._c = ffi.NULL
        self._own = False
        self._finalizer = None
        if raw_ptr is not None:
            if raw_ptr == ffi.NULL:
                raise ValueError("raw_ptr must not be NULL")
            self._c = raw_ptr
            self._own = own
        else:
            output = ffi.new("dstar_lite_key_t**")
            raise_for_status(
                C.dstar_lite_key_create_ex(k1, k2, output),
                "dstar_lite_key_create_ex",
            )
            self._c = output[0]
            self._own = True

        validation = ffi.new("int*")
        try:
            raise_for_status(
                C.dstar_lite_key_compare_exact(
                    self._c, self._c, validation
                ),
                "dstar_lite_key_compare_exact",
            )
        except Exception:
            if self._own:
                C.dstar_lite_key_destroy(self._c)
            self._c = ffi.NULL
            self._own = False
            raise

        self._k1 = self._canonical_component(float(self._c.k1))
        self._k2 = self._canonical_component(float(self._c.k2))
        self._hash = int(C.dstar_lite_key_hash_exact(self._c))
        if self._own:
            self._finalizer = weakref.finalize(
                self, C.dstar_lite_key_destroy, self._c
            )

    @staticmethod
    def _canonical_component(value):
        return 0.0 if value == 0.0 else value

    def _require_open(self):
        if self._c == ffi.NULL:
            raise ReferenceError("c_dstar_lite_key is closed")
        return self._c

    @staticmethod
    def _require_key(value, argument):
        if not isinstance(value, c_dstar_lite_key):
            raise TypeError(f"{argument} must be c_dstar_lite_key")
        return value

    def copy(self):
        if self._c == ffi.NULL:
            return c_dstar_lite_key(self._k1, self._k2)
        output = ffi.new("dstar_lite_key_t**")
        raise_for_status(
            C.dstar_lite_key_copy_ex(self._c, output),
            "dstar_lite_key_copy_ex",
        )
        return c_dstar_lite_key(raw_ptr=output[0], own=True)

    def equal(self, other: 'c_dstar_lite_key'):
        other = self._require_key(other, "other")
        return self.to_tuple() == other.to_tuple()

    def compare(self, other: 'c_dstar_lite_key'):
        other = self._require_key(other, "other")
        if self._c != ffi.NULL and other._c != ffi.NULL:
            output = ffi.new("int*")
            raise_for_status(
                C.dstar_lite_key_compare_exact(
                    self._c, other._c, output
                ),
                "dstar_lite_key_compare_exact",
            )
            return int(output[0])
        return (self.to_tuple() > other.to_tuple()) - (
            self.to_tuple() < other.to_tuple()
        )

    def is_close(
        self,
        other: 'c_dstar_lite_key',
        *,
        absolute_tolerance,
        relative_tolerance,
    ):
        other = self._require_key(other, "other")
        output = ffi.new("bool*")
        raise_for_status(
            C.dstar_lite_key_is_close(
                self._require_open(),
                other._require_open(),
                absolute_tolerance,
                relative_tolerance,
                output,
            ),
            "dstar_lite_key_is_close",
        )
        return bool(output[0])

    def __eq__(self, other):
        if not isinstance(other, c_dstar_lite_key):
            return NotImplemented
        return self.to_tuple() == other.to_tuple()

    def __lt__(self, other):
        if not isinstance(other, c_dstar_lite_key):
            return NotImplemented
        return self.to_tuple() < other.to_tuple()

    def __hash__(self):
        return self._hash

    @property
    def k1(self):
        return self._k1

    @property
    def k2(self):
        return self._k2

    def to_tuple(self):
        return (self.k1, self.k2)

    def ptr(self):
        self._require_open()
        snapshot = ffi.new("dstar_lite_key_t*")
        snapshot.k1 = self._k1
        snapshot.k2 = self._k2
        return snapshot

    def __repr__(self):
        return f"c_dstar_lite_key(k1={self.k1:.6f}, k2={self.k2:.6f})"

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass

    def close(self):
        finalizer = getattr(self, "_finalizer", None)
        if getattr(self, "_own", False) and finalizer and finalizer.alive:
            finalizer()
        self._c = ffi.NULL
        self._own = False

    def __enter__(self):
        self._require_open()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
