import weakref

from .ffi_core import ffi, C

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/dstar_lite/dstar_lite_key.h */
typedef struct s_dstar_lite_key {
    float k1;
    float k2;
} dstar_lite_key_t;

 dstar_lite_key_t* dstar_lite_key_create(void);

 dstar_lite_key_t* dstar_lite_key_create_full(float k1, float k2);

 dstar_lite_key_t* dstar_lite_key_copy(const dstar_lite_key_t* key);

 void dstar_lite_key_destroy(dstar_lite_key_t* key);

 bool dstar_lite_key_equal(const dstar_lite_key_t* dsk0,
                                   const dstar_lite_key_t* dsk1);

 int dstar_lite_key_compare(const dstar_lite_key_t* dsk0,
                                    const dstar_lite_key_t* dsk1);

 unsigned int dstar_lite_key_hash(const dstar_lite_key_t* key);
""")

class c_dstar_lite_key:
    def __init__(self, k1=0.0, k2=0.0, raw_ptr=None, own=False):
        if raw_ptr:
            self._c = raw_ptr
            self._own = own
        else:
            self._c = C.dstar_lite_key_create_full(k1, k2)
            if not self._c:
                raise MemoryError("dstar_lite_key allocation failed")
            self._own = True

        if self._own:
            self._finalizer = weakref.finalize(self, C.dstar_lite_key_destroy, self._c)
        else:
            self._finalizer = None

    def copy(self):
        return c_dstar_lite_key(raw_ptr=C.dstar_lite_key_copy(self._c), own=True)

    def equal(self, other: 'c_dstar_lite_key'):
        return bool(C.dstar_lite_key_equal(self._c, other._c))

    def compare(self, other: 'c_dstar_lite_key'):
        return C.dstar_lite_key_compare(self._c, other._c)

    def __eq__(self, other):
        return isinstance(other, c_dstar_lite_key) and self.equal(other)

    def __lt__(self, other):
        return self.compare(other) < 0

    def __gt__(self, other):
        return self.compare(other) > 0

    def __hash__(self):
        return C.dstar_lite_key_hash(self._c)

    @property
    def k1(self):
        return float(self._c.k1)

    @property
    def k2(self):
        return float(self._c.k2)

    def to_tuple(self):
        return (self.k1, self.k2)

    def ptr(self):
        return self._c

    def __repr__(self):
        return f"c_dstar_lite_key(k1={self.k1:.6f}, k2={self.k2:.6f})"

    def __del__(self):
        self.close()

    def close(self):
        if self._own and self._finalizer and self._finalizer.alive:
            self._finalizer()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
