from .ffi_core import ffi, C

from typing import Any

from .route_finder_common import g_RouteFuncReg
from .coord import c_coord
from .coord_list import c_coord_list
from .coord_hash import c_coord_hash

from .route import c_route
from .navgrid import c_navgrid, NavgridDirMode

from .dstar_lite_key import c_dstar_lite_key
from .dstar_lite_pqueue import c_dstar_lite_pqueue
from .byul_tick import c_tick

import weakref

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/dstar_lite/dstar_lite.h */
typedef void (*move_func)(const coord_t* c, void* userdata);

typedef coord_list_t* (*changed_coords_func)(void* userdata);

 float dstar_lite_cost(
    const navgrid_t* navgrid,
    const coord_t* start,
    const coord_t* goal,
    void* userdata);

 float dstar_lite_dynamic_cost(
    const navgrid_t* navgrid,
    const coord_t* start,
    const coord_t* goal,
    void* userdata);

 float dstar_lite_heuristic(
    const coord_t* start, const coord_t* goal, void* userdata);

 void move_to(const coord_t* c, void* userdata);

 coord_list_t* get_changed_coord(void* userdata);

 coord_list_t* get_changed_coords(void* userdata);

typedef struct s_dstar_lite {

    navgrid_t* navgrid;
    coord_t start;
    coord_t goal;

    cost_func cost_fn;
    void* cost_fn_userdata;

    heuristic_func heuristic_fn;
    void* heuristic_fn_userdata;

    int max_retry;
    bool debug_mode_enabled;

    float km;
    coord_hash_t* g_table;
    coord_hash_t* rhs_table;

    dstar_lite_pqueue_t* frontier;

    move_func move_fn;
    void* move_fn_userdata;

    changed_coords_func changed_coords_fn;
    void* changed_coords_fn_userdata;

    route_t* proto_route;
    route_t* real_route;

    int real_loop_max_retry;
    int reconstruct_max_retry;

    int proto_compute_retry_count;
    int real_compute_retry_count;
    int real_loop_retry_count;
    int reconstruct_retry_count;

    int max_range;

    float interval_sec;

    bool force_quit;

} dstar_lite_t;

 dstar_lite_t* dstar_lite_create(navgrid_t* navgrid);

 dstar_lite_t* dstar_lite_create_full(
    navgrid_t* navgrid,
    const coord_t* start,
    const coord_t* goal,
    cost_func cost_fn,
    heuristic_func heuristic_fn,
    bool debug_mode_enabled);

 void dstar_lite_destroy(dstar_lite_t* dsl);

 dstar_lite_t* dstar_lite_copy(const dstar_lite_t* src);

 int dstar_lite_fetch_start(const dstar_lite_t* dsl, coord_t* out);

 void  dstar_lite_set_start(dstar_lite_t* dsl, const coord_t* c);

 int dstar_lite_fetch_goal(const dstar_lite_t* dsl, coord_t* out);

 void  dstar_lite_set_goal(dstar_lite_t* dsl, const coord_t* c);

 coord_hash_t* dstar_lite_get_g_table(const dstar_lite_t* dsl);

 coord_hash_t* dstar_lite_get_rhs_table(const dstar_lite_t* dsl);

 dstar_lite_pqueue_t* dstar_lite_get_frontier(
    const dstar_lite_t* dsl);

 void     dstar_lite_set_frontier(
    dstar_lite_t* dsl, dstar_lite_pqueue_t* frontier);

 float dstar_lite_get_km(const dstar_lite_t* dsl);
 void   dstar_lite_set_km(dstar_lite_t* dsl, float km);

 int   dstar_lite_get_max_range(const dstar_lite_t* dsl);
 void   dstar_lite_set_max_range(dstar_lite_t* dsl, int value);

 int   dstar_lite_get_real_loop_max_retry(const dstar_lite_t* dsl);
 void  dstar_lite_set_real_loop_max_retry(
    dstar_lite_t* dsl, int value);
 int   dstar_lite_real_loop_retry_count(const dstar_lite_t* dsl);

 int dstar_lite_get_max_retry(const dstar_lite_t* dsl);
 void dstar_lite_set_max_retry(
    dstar_lite_t* dsl, int v);

 int dstar_lite_proto_compute_retry_count(const dstar_lite_t* dsl);

 int dstar_lite_real_compute_retry_count(const dstar_lite_t* dsl);

 int dstar_lite_get_reconstruct_max_retry(const dstar_lite_t* dsl);
 void dstar_lite_set_reconstruct_max_retry(dstar_lite_t* dsl, int v);
 int dstar_lite_reconstruct_retry_count(const dstar_lite_t* dsl);

 bool dstar_lite_is_debug_mode_enabled(const dstar_lite_t* dsl);

 void     dstar_lite_enable_debug_mode(
    dstar_lite_t* dsl, bool enabled);

 const navgrid_t*    dstar_lite_get_navgrid(const dstar_lite_t* dsl);
 void    dstar_lite_set_navgrid(dstar_lite_t* dsl, navgrid_t* navgrid);

 const route_t* dstar_lite_get_proto_route(const dstar_lite_t* dsl);

 const route_t* dstar_lite_get_real_route(const dstar_lite_t* dsl);

 void dstar_lite_reset(dstar_lite_t* dsl);

 float dstar_lite_get_interval_sec(dstar_lite_t* dsl);

 void dstar_lite_set_interval_sec(
    dstar_lite_t* dsl, float interval_sec);

 cost_func    dstar_lite_get_cost_func(const dstar_lite_t* dsl);
 void dstar_lite_set_cost_func(dstar_lite_t* dsl, cost_func fn);

 void*    dstar_lite_get_cost_func_userdata(const dstar_lite_t* dsl);

 void dstar_lite_set_cost_func_userdata(
    dstar_lite_t* dsl, void* userdata);

 heuristic_func dstar_lite_get_heuristic_func(
    const dstar_lite_t* dsl);
 void         dstar_lite_set_heuristic_func(
    dstar_lite_t* dsl, heuristic_func func);
 void* dstar_lite_get_heuristic_func_userdata(
    const dstar_lite_t* dsl);
 void dstar_lite_set_heuristic_func_userdata(
    dstar_lite_t* dsl, void* userdata);

 move_func dstar_lite_get_move_func(const dstar_lite_t* dsl);
 void dstar_lite_set_move_func(dstar_lite_t* dsl, move_func fn);
 void* dstar_lite_get_move_func_userdata(const dstar_lite_t* dsl);
 void dstar_lite_set_move_func_userdata(
    dstar_lite_t* dsl, void* userdata);

 changed_coords_func dstar_lite_get_changed_coords_func(
    const dstar_lite_t* dsl);
 void dstar_lite_set_changed_coords_func(
    dstar_lite_t* dsl, changed_coords_func fn);
 void* dstar_lite_get_changed_coords_func_userdata(
    const dstar_lite_t* dsl);
 void dstar_lite_set_changed_coords_func_userdata(
    dstar_lite_t* dsl, void* userdata);

 navsys_status_t dstar_lite_bind_cost_func(
    dstar_lite_t* dsl, cost_func fn, void* userdata);

 navsys_status_t dstar_lite_unbind_cost_func(dstar_lite_t* dsl);

 navsys_status_t dstar_lite_bind_heuristic_func(
    dstar_lite_t* dsl, heuristic_func fn, void* userdata);

 navsys_status_t dstar_lite_unbind_heuristic_func(
    dstar_lite_t* dsl);

 navsys_status_t dstar_lite_bind_move_func(
    dstar_lite_t* dsl, move_func fn, void* userdata);

 navsys_status_t dstar_lite_unbind_move_func(dstar_lite_t* dsl);

 navsys_status_t dstar_lite_bind_changed_coords_func(
    dstar_lite_t* dsl, changed_coords_func fn, void* userdata);

 navsys_status_t dstar_lite_unbind_changed_coords_func(
    dstar_lite_t* dsl);

 dstar_lite_key_t* dstar_lite_calc_key(
    dstar_lite_t* dsl, const coord_t* s);

 void dstar_lite_init(dstar_lite_t* dsl);

 void dstar_lite_update_vertex(dstar_lite_t* dsl, const coord_t* u);

 void dstar_lite_update_vertex_range(dstar_lite_t* dsl,
    const coord_t* s, int max_range);

 void dstar_lite_update_vertex_auto_range(
    dstar_lite_t* dsl, const coord_t* s);

 void dstar_lite_compute_shortest_route(dstar_lite_t* dsl);

 bool dstar_lite_reconstruct_route(dstar_lite_t* dsl);

 route_t* dstar_lite_find(dstar_lite_t* dsl);

 void dstar_lite_find_full(dstar_lite_t* dsl);

 bool dstar_lite_find_proto(dstar_lite_t* dsl);

 void dstar_lite_find_loop(dstar_lite_t* dsl);

 void dstar_lite_update_vertex_by_route(
    dstar_lite_t* dsl, route_t* p);

 void dstar_lite_force_quit(dstar_lite_t* dsl);

 bool dstar_lite_is_quit_forced(dstar_lite_t* dsl);

 void dstar_lite_set_force_quit(dstar_lite_t* dsl, bool v);

 bool dstar_lite_fetch_next(
    const dstar_lite_t* dsl, const coord_t* start, coord_t* out);
""", override=True)

class c_dstar_lite:
    def __init__(self, 
                 m: c_navgrid = None, 
                 start: c_coord = None,
                 goal: c_coord = None,
                 cost_fn=None, 
                 heuristic_fn=None, 
                 debug=False, 
                 raw_ptr=None, 
                 own=False):

        self._c = ffi.NULL
        self._own = False
        self._finalizer = None

        if raw_ptr:
            self._c = raw_ptr
            self._own = own
        else:
            if m is None:
                raise ValueError("navgrid (m) must be provided")

            if start and goal:
                self._c = C.dstar_lite_create_full(
                    m.ptr(),
                    start.ptr(),
                    goal.ptr(),
                    cost_fn if cost_fn else ffi.NULL,
                    heuristic_fn if heuristic_fn else ffi.NULL,
                    debug
                )
            else:
                self._c = C.dstar_lite_create(m.ptr())

            self._own = True

        if not self._c:
            raise MemoryError("dstar_lite allocation failed")

        if self._own:
            self._finalizer = weakref.finalize(
                self, C.dstar_lite_destroy, self._c
            )
        else:
            self._finalizer = None


    def ptr(self):
        return self._c

       # ───── Start/Goal ─────
    def get_start(self) -> c_coord:
        out = ffi.new("coord_t*")
        if C.dstar_lite_fetch_start(self._c, out) == 0:
            return c_coord(raw_ptr=out)
        else:
            raise RuntimeError("Failed to get start coordinate")

    def set_start(self, coord: c_coord):
        C.dstar_lite_set_start(self._c, coord.ptr())

    def get_goal(self) -> c_coord:
        out = ffi.new("coord_t*")
        if C.dstar_lite_fetch_goal(self._c, out) == 0:
            return c_coord(raw_ptr=out)
        else:
            raise RuntimeError("Failed to get goal coordinate")

    def set_goal(self, coord: c_coord):
        C.dstar_lite_set_goal(self._c, coord.ptr())

    # ───── 테이블 접근 ─────
    def g_table(self):
        return c_coord_hash(
            raw_ptr=C.dstar_lite_get_g_table(self._c), own=False)

    def rhs_table(self):
        return c_coord_hash(
            raw_ptr=C.dstar_lite_get_rhs_table(self._c), own=False)

    def frontier(self):
        return c_dstar_lite_pqueue(
            raw_ptr=C.dstar_lite_get_frontier(self._c), own=False)

    def set_frontier(self, frontier: c_dstar_lite_pqueue):
        C.dstar_lite_set_frontier(self._c, frontier.ptr())

    # ───── 설정값들 ─────
    def get_km(self):
        return C.dstar_lite_get_km(self._c)

    def set_km(self, v):
        C.dstar_lite_set_km(self._c, v)

    def get_max_range(self):
        return C.dstar_lite_get_max_range(self._c)

    def set_max_range(self, v):
        C.dstar_lite_set_max_range(self._c, v)

    @property
    def real_loop_max_retry(self):
        # gint   dstar_lite_get_real_loop_max_retry(const dstar_lite dsl);
        return C.dstar_lite_get_real_loop_max_retry(self.ptr())

    @real_loop_max_retry.setter
    def real_loop_max_retry(self, value:int):
        # void   dstar_lite_set_real_loop_max_retry(
        #     dstar_lite dsl, gint value);
        C.dstar_lite_set_real_loop_max_retry(self.ptr(), value)

    @property
    def compute_max_retry(self):
        # // 10x10의 맵에서 100은 되어야 잘 찾는거 같다.
        # gint dstar_lite_get_compute_max_retry(const dstar_lite dsl);
        return C.dstar_lite_get_compute_max_retry(self.ptr())

    @compute_max_retry.setter
    def compute_max_retry(self, value:int):
        # void dstar_lite_set_compute_max_retry(
        #     const dstar_lite dsl, gint v);
        C.dstar_lite_set_compute_max_retry(self.ptr(), value)

    @property
    def reconstruct_max_retry(self):
        # // proto route 생성할때 reconstruct_route한다. 여기에 사용하는 루프
        # // 10x10에서 100은 오버고 10은 너무 작고 대충 40 정도면 되겠다.
        # gint dstar_lite_get_reconstruct_max_retry(const dstar_lite dsl);
        return C.dstar_lite_get_reconstruct_max_retry(self.ptr())

    @reconstruct_max_retry.setter
    def reconstruct_max_retry(self, value:int):
        # void dstar_lite_set_reconstruct_max_retry(
        #     const dstar_lite dsl, gint v);
        C.dstar_lite_set_reconstruct_max_retry(self.ptr(), value)

    
    @property
    def proto_compute_retry_count(self):
        # gint dstar_lite_proto_compute_retry_count(dstar_lite dsl);
        return C.dstar_lite_proto_compute_retry_count(self.ptr())

    @property
    def real_compute_retry_count(self):
        # gint dstar_lite_real_compute_retry_count(dstar_lite dsl);
        return C.dstar_lite_real_compute_retry_count(self.ptr())

    @property
    def real_loop_retry_count(self):
        # gint dstar_lite_real_loop_retry_count(dstar_lite dsl);
        return C.dstar_lite_real_loop_retry_count(self.ptr())

    @property
    def reconstruct_retry_count(self):
        # gint dstar_lite_reconstruct_retry_count(dstar_lite dsl);         
        return C.dstar_lite_reconstruct_retry_count(self.ptr())


    def set_interval_sec(self, v):
        C.dstar_lite_set_interval_sec(self._c, v)

    def get_interval_sec(self):
        return C.dstar_lite_get_interval_sec(self._c)

    def set_debug_mode_enabled(self, v: bool):
        C.dstar_lite_enable_debug_mode(self._c, v)

    def is_debug_mode_enabled(self):
        return bool(C.dstar_lite_get_debug_mode_enabled(self._c))

    # ───── 경로 ─────
    def get_proto_route(self):
        return c_route(
            raw_ptr=C.dstar_lite_get_proto_route(self._c), own=False)

    def get_real_route(self):
        return c_route(
            raw_ptr=C.dstar_lite_get_real_route(self._c), own=False)

    # ───── 경로 탐색 함수들 ─────
    def find(self):
        ptr = C.dstar_lite_find(self._c)
        return c_route(raw_ptr=ptr, own=True) if ptr != ffi.NULL else None

    def find_proto(self):
        C.dstar_lite_find_proto(self._c)

    def find_loop(self):
        C.dstar_lite_find_loop(self._c)

    def find_full(self):
        C.dstar_lite_find_full(self._c)

    # ───── 유틸 함수 ─────
    def init(self):
        C.dstar_lite_init(self._c)

    def reset(self):
        C.dstar_lite_reset(self._c)

    def compute_shortest_route(self):
        C.dstar_lite_compute_shortest_route(self._c)

    def reconstruct_route(self):
        ptr = C.dstar_lite_reconstruct_route(self._c)
        return c_route(raw_ptr=ptr, own=True) if ptr != ffi.NULL else None

    def calculate_key(self, s: c_coord):
        ptr = C.dstar_lite_calculate_key(self._c, s.ptr())
        return c_dstar_lite_key(
            raw_ptr=ptr, own=True) if ptr != ffi.NULL else None

    def update_vertex(self, coord: c_coord):
        C.dstar_lite_update_vertex(self._c, coord.ptr())

    def update_vertex_range(self, center: c_coord, range_val: int):
        C.dstar_lite_update_vertex_range(self._c, center.ptr(), range_val)

    def update_vertex_auto_range(self, center: c_coord):
        C.dstar_lite_update_vertex_auto_range(self._c, center.ptr())

    def update_vertex_by_route(self, route: c_route):
        C.dstar_lite_update_vertex_by_route(self._c, route.ptr())

    # ───── 상태 통계 및 종료 ─────
    def is_quit_forced(self):
        return bool(C.dstar_lite_is_quit_forced(self._c))

    def set_force_quit(self, v: bool):
        C.dstar_lite_set_force_quit(self._c, v)

    def force_quit(self):
        C.dstar_lite_force_quit(self._c)

    def update_count_table(self):
        return c_coord_hash(
            raw_ptr=C.dstar_lite_get_update_count_table(self._c), own=False)

    def add_update_count(self, coord: c_coord):
        C.dstar_lite_add_update_count(self._c, coord.ptr())

    def get_update_count(self, coord: c_coord):
        return C.dstar_lite_get_update_count(self._c, coord.ptr())

    def clear_update_count(self):
        C.dstar_lite_clear_update_count(self._c)

    def navgrid(self):
        return c_navgrid(raw_ptr=C.dstar_lite_get_navgrid(self._c), own=False)

    def set_map(self, m: c_navgrid):
        C.dstar_lite_set_map(self._c, m.ptr())

    # ───── 메모리 관리 ─────
    def __del__(self):
        if getattr(self, "_own", False) and self._finalizer and self._finalizer.alive:
            self._finalizer()

    def close(self):
        if getattr(self, "_own", False) and self._finalizer and self._finalizer.alive:
            self._finalizer()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()

    def __repr__(self):
        return f'''c_dstar_lite(
start={self.get_start()}, goal={self.get_goal()}, km={self.get_km():.2f})'''

    # ───── 비용 함수 (cost_fn) 등록 ─────
    def set_cost_func(self, py_func: callable):
        self._py_cost_func = py_func
        # self._cost_func_userdata = userdata
        # self._ffi_cost_func_userdata = ffi.new_handle(userdata)
        # self._ffi_cost_func_userdata = (
        #     ffi.new_handle(userdata) if userdata is not None else ffi.NULL
        # )        

        @ffi.callback(
                "float(const navgrid_t*, const coord_t*, const coord_t*, void*)")
        def _wrapped(m_ptr, s_ptr, g_ptr, udata_ptr):
            map_obj = c_navgrid(raw_ptr=m_ptr, own=False)
            start = c_coord(raw_ptr=s_ptr)
            goal = c_coord(raw_ptr=g_ptr)
            # user = ffi.from_handle(udata_ptr)
            # This wrapper does not register a Python handle as userdata.
            # Treat the native userdata value as opaque; attempting to pass it
            # to ffi.from_handle() can abort Python if C returns a stale or
            # non-Python pointer.
            user = None
            return py_func(map_obj, start, goal, user)

        self._ffi_cost_func = _wrapped
        C.dstar_lite_set_cost_func(self._c, _wrapped)
        # C.dstar_lite_set_cost_func_userdata(
        #     self._c, self._ffi_cost_func_userdata)
        


    # ───── 휴리스틱 함수 (heuristic_fn) 등록 ─────
    def set_heuristic_func(self, py_func: callable):
        self._py_heuristic_func = py_func
        # self._heuristic_func_userdata = userdata
        # self._ffi_heuristic_func_userdata = ffi.new_handle(userdata)
        # self._ffi_heuristic_func_userdata = (
        #     ffi.new_handle(userdata) if userdata is not None else ffi.NULL
        # )                

        @ffi.callback("float(const coord_t*, const coord_t*, void*)")
        def _wrapped(s_ptr, g_ptr, udata_ptr):
            start = c_coord(raw_ptr=s_ptr)
            goal = c_coord(raw_ptr=g_ptr)
            user = None
            return py_func(start, goal, user)

        self._ffi_heuristic_func = _wrapped
        C.dstar_lite_set_heuristic_func(self._c, _wrapped)
        # C.dstar_lite_set_heuristic_func_userdata(
        #     self._c, self._ffi_heuristic_func_userdata)

    # ───── 장애물 여부 함수 (is_blocked_fn) 등록 ─────
    def set_is_blocked_func(self, py_func: callable):
        self._py_is_blocked_func = py_func
        # self._is_blocked_func_userdata = userdata
        # self._ffi_is_blocked_func_userdata = ffi.new_handle(userdata)
        # self._ffi_is_blocked_func_userdata = (
        #     ffi.new_handle(userdata) if userdata is not None else ffi.NULL
        # )

        @ffi.callback("bool(const navgrid_t*, int, int, void*)")
        def _wrapped(m_ptr, x, y, udata_ptr):
            map_obj = c_navgrid(raw_ptr=m_ptr, own=False)
            user = None
            return bool(py_func(map_obj, x, y, user))

        self._ffi_is_blocked_func = _wrapped
        C.dstar_lite_set_is_blocked_func(self._c, _wrapped)
        # C.dstar_lite_set_is_blocked_func_userdata(
        #     self._c, self._ffi_is_blocked_func_userdata)

    # ───── 이동 콜백 함수 (move_func) 등록 ─────
    def set_move_func(self, py_func: callable):
        self._py_move_func = py_func

        @ffi.callback("void(const coord_t*, void*)")
        def _wrapped(c_ptr, udata_ptr):
            coord = c_coord(raw_ptr=c_ptr)
            user = None
            py_func(coord, user)

        self._ffi_move_func = _wrapped
        C.dstar_lite_set_move_func(self._c, _wrapped)
        # C.dstar_lite_set_move_func_userdata(
        #     self._c, self._ffi_move_func_userdata)

    # ───── 동적 장애물 갱신 함수 (changed_coords_func) 등록 ─────
    def set_changed_coords_func(self, py_func: callable):
        self._py_changed_coords_func = py_func
        # self._changed_coords_func_userdata = userdata
        # self._ffi_changed_coords_func_userdata = ffi.new_handle(userdata)
        # self._ffi_changed_coords_func_userdata = (
        #     ffi.new_handle(userdata) if userdata is not None else ffi.NULL
        # )

        @ffi.callback("coord_list_t*(void*)")
        def _wrapped(udata_ptr):
            user = None
            clist = py_func(user)
            if isinstance(clist, c_coord_list):
                return clist.ptr()
            return ffi.NULL

        self._ffi_changed_coords_func = _wrapped
        C.dstar_lite_set_changed_coords_func(self._c, _wrapped)
        # C.dstar_lite_set_changed_coords_func_userdata(
        #     self._c, self._ffi_changed_coords_func_userdata)

if __name__ == '__main__':
    navgrid = c_navgrid(width=10, height=10, mode=NavgridDirMode.DIR_8.value)
    finder = c_dstar_lite(navgrid)
    finder.set_debug_mode_enabled(True)

    # 1️⃣ 초기 경로
    print("\n▶ 최초 경로:")
    start = c_coord(0,0)
    goal = c_coord(9,9)
    finder.set_start(start)
    finder.set_goal(goal)

    result = finder.find()
    result.print()

    result.close()    

g_RouteFuncReg.register_cost("dstar_lite", C.dstar_lite_cost)

g_RouteFuncReg.register_heuristic("dstar_lite", C.dstar_lite_heuristic)
