"""Owned Python wrapper for the checked Maze core API."""

import weakref

from .ffi_core import ffi, C
from .navsys_status import raise_for_status
from .coord import c_coord
from .coord_hash import c_coord_hash  # Registers coord_hash_t in the shared FFI.
from .navgrid import c_navgrid  # Registers navgrid_t and overlay identifiers.


MAZE_ABI_VERSION = 2
MAZE_ABI_FINGERPRINT = 0x4D415A4502000000
MAZE_GENERATE_OPTIONS_ABI_VERSION = 1


def _check_maze_abi():
    mismatch = ffi.new("byul_maze_abi_mismatch_t*")
    try:
        status = C.byul_maze_check_abi(
            MAZE_ABI_VERSION,
            MAZE_ABI_FINGERPRINT,
            mismatch,
        )
    except AttributeError as error:
        raise RuntimeError(
            "Maze ABI mismatch: runtime does not export byul_maze_check_abi"
        ) from error
    if int(status) == 0:
        return
    reason = {1: "version", 2: "fingerprint"}.get(
        int(mismatch[0]), "unknown"
    )
    raise RuntimeError(
        f"Maze ABI mismatch: {reason}; expected version={MAZE_ABI_VERSION} "
        f"fingerprint=0x{MAZE_ABI_FINGERPRINT:016x}"
    )


ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/maze/maze_core.h */
typedef struct s_maze maze_t;

typedef enum e_byul_maze_abi_mismatch {
    BYUL_MAZE_ABI_MATCH = 0,
    BYUL_MAZE_ABI_VERSION_MISMATCH = 1,
    BYUL_MAZE_ABI_FINGERPRINT_MISMATCH = 2
} byul_maze_abi_mismatch_t;

 uint32_t byul_maze_get_abi_version(void);

 uint64_t byul_maze_get_abi_fingerprint(void);

 navsys_status_t byul_maze_check_abi(
    uint32_t expected_version,
    uint64_t expected_fingerprint,
    byul_maze_abi_mismatch_t* out_mismatch);

 size_t byul_maze_sizeof(void);

 size_t byul_maze_alignof(void);

typedef struct byul_maze_extent {
    int32_t origin_x;
    int32_t origin_y;
    uint32_t width;
    uint32_t height;
} byul_maze_extent_t;

typedef enum e_byul_maze_navgrid_merge_policy {

    BYUL_MAZE_NAVGRID_MERGE_PRESERVE_BASE = 0
} byul_maze_navgrid_merge_policy_t;

typedef bool (*byul_maze_navgrid_cancel_func)(void* userdata);

typedef struct s_byul_maze_navgrid_apply_options {
    uint32_t struct_size;
    uint32_t abi_version;

    uint32_t merge_policy;
    byul_maze_navgrid_cancel_func cancel_func;
    void* cancel_userdata;
} byul_maze_navgrid_apply_options_t;

typedef struct s_byul_maze_navgrid_overlay_token {
    uint32_t struct_size;
    uint32_t abi_version;
    uint64_t owner_cookie;
    navgrid_overlay_id_t overlay;
} byul_maze_navgrid_overlay_token_t;

 navsys_status_t byul_maze_create(
    const byul_maze_extent_t* extent, maze_t** out_maze);

 maze_t* maze_create(void);

 maze_t* maze_create_full(int x0, int y0, int width, int height);

 void maze_destroy(maze_t* maze);

 void maze_clear(maze_t* maze);

 maze_t* maze_copy(const maze_t* maze);

 navsys_status_t byul_maze_copy(
    const maze_t* source, maze_t** out_maze);

 bool maze_equal(const maze_t* a, const maze_t* b);

 uint32_t maze_hash(const maze_t* maze);

 navsys_status_t byul_maze_translate(
    maze_t* maze, int32_t delta_x, int32_t delta_y);

 void maze_set_origin(maze_t* maze, int x0, int y0);

 void maze_get_origin(
    const maze_t* maze, int* out_x0, int* out_y0);

 navsys_status_t byul_maze_get_extent(
    const maze_t* maze, byul_maze_extent_t* out_extent);

 int maze_get_width(const maze_t* maze);

 int maze_get_height(const maze_t* maze);

 const coord_hash_t* maze_get_blocked_coords(
    const maze_t* maze);

 navsys_status_t byul_maze_get_blocked_count(
    const maze_t* maze, size_t* out_count);

 navsys_status_t byul_maze_fetch_blocked(
    const maze_t* maze,
    coord_t* buffer,
    size_t capacity,
    size_t* out_count);

 navsys_status_t byul_maze_is_blocked(
    const maze_t* maze, int32_t x, int32_t y, bool* out_blocked);

 navsys_status_t byul_maze_set_blocked(
    maze_t* maze,
    int32_t x,
    int32_t y,
    bool blocked,
    bool* out_changed);

 navsys_status_t byul_maze_apply(
    const maze_t* maze,
    navgrid_t* navgrid,
    const byul_maze_navgrid_apply_options_t* options,
    byul_maze_navgrid_overlay_token_t* out_overlay,
    size_t* out_changed_count);

 navsys_status_t byul_maze_remove_overlay(
    navgrid_t* navgrid,
    byul_maze_navgrid_overlay_token_t* overlay,
    size_t* out_changed_count);

 void maze_apply_to_navgrid(const maze_t* maze, navgrid_t* navgrid);

 void maze_remove_from_navgrid(const maze_t* maze, navgrid_t* navgrid);

/* Source: byul/navsys/maze/maze.h */
typedef enum e_maze_type {
    MAZE_TYPE_RECURSIVE = 0,
    MAZE_TYPE_PRIM = 1,
    MAZE_TYPE_BINARY = 2,
    MAZE_TYPE_ELLER = 3,

    MAZE_TYPE_ALDOUS_BRODER = 4,
    MAZE_TYPE_WILSON = 5,
    MAZE_TYPE_HUNT_AND_KILL = 6,
    MAZE_TYPE_SIDEWINDER = 7,

    MAZE_TYPE_RECURSIVE_DIVISION = 8,
    MAZE_TYPE_KRUSKAL = 9,
    MAZE_TYPE_ROOM_BLEND = 10
} maze_type_t;

typedef enum e_byul_maze_algorithm {
    BYUL_MAZE_ALGORITHM_RECURSIVE_BACKTRACKER = 0,
    BYUL_MAZE_ALGORITHM_RANDOMIZED_PRIM = 1,
    BYUL_MAZE_ALGORITHM_BINARY_TREE = 2,
    BYUL_MAZE_ALGORITHM_ELLER = 3,
    BYUL_MAZE_ALGORITHM_ALDOUS_BRODER = 4,
    BYUL_MAZE_ALGORITHM_WILSON = 5,
    BYUL_MAZE_ALGORITHM_HUNT_AND_KILL = 6,
    BYUL_MAZE_ALGORITHM_SIDEWINDER = 7,
    BYUL_MAZE_ALGORITHM_RECURSIVE_DIVISION = 8,
    BYUL_MAZE_ALGORITHM_RANDOMIZED_KRUSKAL = 9,
    BYUL_MAZE_ALGORITHM_ROOM_BLEND = 10
} byul_maze_algorithm_t;

typedef bool (*byul_maze_generate_cancel_func)(void* userdata);

typedef struct s_byul_maze_generate_options {
    uint32_t struct_size;
    uint32_t abi_version;
    uint64_t seed;
    uint64_t max_steps;
    uint64_t max_cells;
    byul_maze_generate_cancel_func cancel_func;
    void* cancel_userdata;
} byul_maze_generate_options_t;

 navsys_status_t byul_maze_algorithm_is_supported(
    byul_maze_algorithm_t algorithm, bool* out_supported);

 navsys_status_t byul_maze_generate(
    byul_maze_algorithm_t algorithm,
    int32_t origin_x,
    int32_t origin_y,
    uint32_t width,
    uint32_t height,
    const byul_maze_generate_options_t* options,
    maze_t** out_maze);

 maze_t* maze_make(
    int x0, int y0, int width, int height, maze_type_t type);

/* Source: byul/navsys/maze/maze_binary.h */
typedef enum e_byul_maze_binary_bias {
    BYUL_MAZE_BINARY_BIAS_NORTH_WEST = 0,
    BYUL_MAZE_BINARY_BIAS_NORTH_EAST = 1,
    BYUL_MAZE_BINARY_BIAS_SOUTH_WEST = 2,
    BYUL_MAZE_BINARY_BIAS_SOUTH_EAST = 3
} byul_maze_binary_bias_t;

 navsys_status_t byul_maze_binary_bias_is_supported(
    byul_maze_binary_bias_t bias, bool* out_supported);

 navsys_status_t byul_maze_generate_binary_tree(
    int32_t origin_x,
    int32_t origin_y,
    uint32_t width,
    uint32_t height,
    byul_maze_binary_bias_t bias,
    const byul_maze_generate_options_t* options,
    maze_t** out_maze);

 maze_t* maze_make_binary(int x0, int y0, int width, int height);

/* Source: byul/navsys/maze/maze_eller.h */
navsys_status_t byul_maze_generate_eller(
    int32_t origin_x,
    int32_t origin_y,
    uint32_t width,
    uint32_t height,
    const byul_maze_generate_options_t* options,
    maze_t** out_maze);

 maze_t* maze_make_eller(int x0, int y0, int width, int height);

/* Source: byul/navsys/maze/maze_hunt_and_kill.h */
navsys_status_t byul_maze_generate_hunt_and_kill(
    int32_t origin_x,
    int32_t origin_y,
    uint32_t width,
    uint32_t height,
    const byul_maze_generate_options_t* options,
    maze_t** out_maze);

 maze_t* maze_make_hunt_and_kill(int x0, int y0, int width, int height);

/* Source: byul/navsys/maze/maze_kruskal.h */
navsys_status_t byul_maze_generate_randomized_kruskal(
    int32_t origin_x,
    int32_t origin_y,
    uint32_t width,
    uint32_t height,
    const byul_maze_generate_options_t* options,
    maze_t** out_maze);

 maze_t* maze_make_kruskal(int x0, int y0, int width, int height);

/* Source: byul/navsys/maze/maze_recursive_division.h */
navsys_status_t byul_maze_generate_recursive_division(
    int32_t origin_x,
    int32_t origin_y,
    uint32_t width,
    uint32_t height,
    const byul_maze_generate_options_t* options,
    maze_t** out_maze);

 maze_t* maze_make_recursive_division(
    int x0, int y0, int width, int height);

/* Source: byul/navsys/maze/maze_sidewinder.h */
typedef enum e_byul_maze_sidewinder_sweep {
    BYUL_MAZE_SIDEWINDER_EAST_NORTH = 0,
    BYUL_MAZE_SIDEWINDER_EAST_SOUTH = 1,
    BYUL_MAZE_SIDEWINDER_WEST_NORTH = 2,
    BYUL_MAZE_SIDEWINDER_WEST_SOUTH = 3
} byul_maze_sidewinder_sweep_t;

 navsys_status_t byul_maze_sidewinder_sweep_is_supported(
    byul_maze_sidewinder_sweep_t sweep, bool* out_supported);

 navsys_status_t byul_maze_generate_sidewinder(
    int32_t origin_x,
    int32_t origin_y,
    uint32_t width,
    uint32_t height,
    byul_maze_sidewinder_sweep_t sweep,
    const byul_maze_generate_options_t* options,
    maze_t** out_maze);

 maze_t* maze_make_sidewinder(int x0, int y0, int width, int height);
""")


def maze_algorithm_is_supported(algorithm):
    """Return the runtime correctness-gate state for an algorithm."""
    _check_maze_abi()
    output = ffi.new("bool*")
    raise_for_status(
        C.byul_maze_algorithm_is_supported(algorithm, output),
        "byul_maze_algorithm_is_supported",
    )
    return bool(output[0])


def maze_binary_bias_is_supported(bias):
    """Return whether the Binary Tree generator supports a bias."""
    _check_maze_abi()
    output = ffi.new("bool*")
    raise_for_status(
        C.byul_maze_binary_bias_is_supported(bias, output),
        "byul_maze_binary_bias_is_supported",
    )
    return bool(output[0])


def maze_sidewinder_sweep_is_supported(sweep):
    """Return whether the Sidewinder generator supports a sweep."""
    _check_maze_abi()
    output = ffi.new("bool*")
    raise_for_status(
        C.byul_maze_sidewinder_sweep_is_supported(sweep, output),
        "byul_maze_sidewinder_sweep_is_supported",
    )
    return bool(output[0])


class c_maze:
    """Caller-owned Maze using only the opaque-ready checked API."""

    def __init__(self, x0=0, y0=0, width=0, height=0, raw_ptr=None, own=True):
        _check_maze_abi()
        self._own = own
        self._c = raw_ptr if raw_ptr is not None else ffi.NULL
        self._finalizer = None
        if self._c == ffi.NULL:
            extent = ffi.new(
                "byul_maze_extent_t*",
                dict(origin_x=x0, origin_y=y0, width=width, height=height),
            )
            output = ffi.new("maze_t**")
            raise_for_status(C.byul_maze_create(extent, output), "byul_maze_create")
            self._c = output[0]
        if own:
            self._finalizer = weakref.finalize(self, C.maze_destroy, self._c)

    @classmethod
    def generate(
        cls,
        algorithm,
        x0,
        y0,
        width,
        height,
        *,
        seed,
        max_steps=0,
        max_cells=0,
    ):
        """Generate through the deterministic checked dispatcher."""
        _check_maze_abi()
        options = ffi.new(
            "byul_maze_generate_options_t*",
            dict(
                struct_size=ffi.sizeof("byul_maze_generate_options_t"),
                abi_version=MAZE_GENERATE_OPTIONS_ABI_VERSION,
                seed=seed,
                max_steps=max_steps,
                max_cells=max_cells,
                cancel_func=ffi.NULL,
                cancel_userdata=ffi.NULL,
            ),
        )
        output = ffi.new("maze_t**")
        raise_for_status(
            C.byul_maze_generate(
                algorithm,
                x0,
                y0,
                width,
                height,
                options,
                output,
            ),
            "byul_maze_generate",
        )
        return cls(raw_ptr=output[0], own=True)

    @classmethod
    def generate_binary_tree(
        cls,
        x0,
        y0,
        width,
        height,
        bias,
        *,
        seed,
        max_steps=0,
        max_cells=0,
    ):
        """Generate a deterministic perfect Binary Tree Maze."""
        _check_maze_abi()
        options = ffi.new(
            "byul_maze_generate_options_t*",
            dict(
                struct_size=ffi.sizeof("byul_maze_generate_options_t"),
                abi_version=MAZE_GENERATE_OPTIONS_ABI_VERSION,
                seed=seed,
                max_steps=max_steps,
                max_cells=max_cells,
                cancel_func=ffi.NULL,
                cancel_userdata=ffi.NULL,
            ),
        )
        output = ffi.new("maze_t**")
        raise_for_status(
            C.byul_maze_generate_binary_tree(
                x0,
                y0,
                width,
                height,
                bias,
                options,
                output,
            ),
            "byul_maze_generate_binary_tree",
        )
        return cls(raw_ptr=output[0], own=True)

    @classmethod
    def generate_eller(
        cls,
        x0,
        y0,
        width,
        height,
        *,
        seed,
        max_steps=0,
        max_cells=0,
    ):
        """Generate a deterministic perfect Eller Maze."""
        _check_maze_abi()
        options = ffi.new(
            "byul_maze_generate_options_t*",
            dict(
                struct_size=ffi.sizeof("byul_maze_generate_options_t"),
                abi_version=MAZE_GENERATE_OPTIONS_ABI_VERSION,
                seed=seed,
                max_steps=max_steps,
                max_cells=max_cells,
                cancel_func=ffi.NULL,
                cancel_userdata=ffi.NULL,
            ),
        )
        output = ffi.new("maze_t**")
        raise_for_status(
            C.byul_maze_generate_eller(
                x0,
                y0,
                width,
                height,
                options,
                output,
            ),
            "byul_maze_generate_eller",
        )
        return cls(raw_ptr=output[0], own=True)

    @classmethod
    def generate_hunt_and_kill(
        cls,
        x0,
        y0,
        width,
        height,
        *,
        seed,
        max_steps=0,
        max_cells=0,
    ):
        """Generate a deterministic perfect Hunt-and-Kill Maze."""
        _check_maze_abi()
        options = ffi.new(
            "byul_maze_generate_options_t*",
            dict(
                struct_size=ffi.sizeof("byul_maze_generate_options_t"),
                abi_version=MAZE_GENERATE_OPTIONS_ABI_VERSION,
                seed=seed,
                max_steps=max_steps,
                max_cells=max_cells,
                cancel_func=ffi.NULL,
                cancel_userdata=ffi.NULL,
            ),
        )
        output = ffi.new("maze_t**")
        raise_for_status(
            C.byul_maze_generate_hunt_and_kill(
                x0,
                y0,
                width,
                height,
                options,
                output,
            ),
            "byul_maze_generate_hunt_and_kill",
        )
        return cls(raw_ptr=output[0], own=True)

    @classmethod
    def generate_sidewinder(
        cls,
        x0,
        y0,
        width,
        height,
        sweep,
        *,
        seed,
        max_steps=0,
        max_cells=0,
    ):
        """Generate a deterministic perfect Sidewinder Maze."""
        _check_maze_abi()
        options = ffi.new(
            "byul_maze_generate_options_t*",
            dict(
                struct_size=ffi.sizeof("byul_maze_generate_options_t"),
                abi_version=MAZE_GENERATE_OPTIONS_ABI_VERSION,
                seed=seed,
                max_steps=max_steps,
                max_cells=max_cells,
                cancel_func=ffi.NULL,
                cancel_userdata=ffi.NULL,
            ),
        )
        output = ffi.new("maze_t**")
        raise_for_status(
            C.byul_maze_generate_sidewinder(
                x0,
                y0,
                width,
                height,
                sweep,
                options,
                output,
            ),
            "byul_maze_generate_sidewinder",
        )
        return cls(raw_ptr=output[0], own=True)

    @classmethod
    def generate_recursive_division(
        cls,
        x0,
        y0,
        width,
        height,
        *,
        seed,
        max_steps=0,
        max_cells=0,
    ):
        """Generate a deterministic perfect Recursive Division Maze."""
        _check_maze_abi()
        options = ffi.new(
            "byul_maze_generate_options_t*",
            dict(
                struct_size=ffi.sizeof("byul_maze_generate_options_t"),
                abi_version=MAZE_GENERATE_OPTIONS_ABI_VERSION,
                seed=seed,
                max_steps=max_steps,
                max_cells=max_cells,
                cancel_func=ffi.NULL,
                cancel_userdata=ffi.NULL,
            ),
        )
        output = ffi.new("maze_t**")
        raise_for_status(
            C.byul_maze_generate_recursive_division(
                x0,
                y0,
                width,
                height,
                options,
                output,
            ),
            "byul_maze_generate_recursive_division",
        )
        return cls(raw_ptr=output[0], own=True)

    @classmethod
    def generate_randomized_kruskal(
        cls,
        x0,
        y0,
        width,
        height,
        *,
        seed,
        max_steps=0,
        max_cells=0,
    ):
        """Generate a deterministic perfect randomized Kruskal Maze."""
        _check_maze_abi()
        options = ffi.new(
            "byul_maze_generate_options_t*",
            dict(
                struct_size=ffi.sizeof("byul_maze_generate_options_t"),
                abi_version=MAZE_GENERATE_OPTIONS_ABI_VERSION,
                seed=seed,
                max_steps=max_steps,
                max_cells=max_cells,
                cancel_func=ffi.NULL,
                cancel_userdata=ffi.NULL,
            ),
        )
        output = ffi.new("maze_t**")
        raise_for_status(
            C.byul_maze_generate_randomized_kruskal(
                x0,
                y0,
                width,
                height,
                options,
                output,
            ),
            "byul_maze_generate_randomized_kruskal",
        )
        return cls(raw_ptr=output[0], own=True)

    @property
    def extent(self):
        output = ffi.new("byul_maze_extent_t*")
        raise_for_status(
            C.byul_maze_get_extent(self._c, output),
            "byul_maze_get_extent",
        )
        return (
            int(output.origin_x),
            int(output.origin_y),
            int(output.width),
            int(output.height),
        )

    @property
    def hash(self):
        """Return the deterministic blocked-coordinate hash."""
        return int(C.maze_hash(self._c))

    def translate(self, delta_x, delta_y):
        raise_for_status(
            C.byul_maze_translate(self._c, delta_x, delta_y),
            "byul_maze_translate",
        )

    def set_blocked(self, x, y, blocked=True):
        changed = ffi.new("bool*")
        raise_for_status(
            C.byul_maze_set_blocked(self._c, x, y, blocked, changed),
            "byul_maze_set_blocked",
        )
        return bool(changed[0])

    def is_blocked(self, x, y):
        blocked = ffi.new("bool*")
        raise_for_status(
            C.byul_maze_is_blocked(self._c, x, y, blocked),
            "byul_maze_is_blocked",
        )
        return bool(blocked[0])

    def blocked_coords(self):
        count = ffi.new("size_t*")
        raise_for_status(
            C.byul_maze_fetch_blocked(self._c, ffi.NULL, 0, count),
            "byul_maze_fetch_blocked(count)",
        )
        if count[0] == 0:
            return []
        output = ffi.new("coord_t[]", count[0])
        raise_for_status(
            C.byul_maze_fetch_blocked(self._c, output, count[0], count),
            "byul_maze_fetch_blocked",
        )
        return [c_coord(output[i].x, output[i].y) for i in range(count[0])]

    def ptr(self):
        return self._c

    def close(self):
        if self._own and self._finalizer and self._finalizer.alive:
            self._finalizer()

    def __del__(self):
        self.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.close()
