import weakref

from .ffi_core import ffi, C
from .navsys_status import NavsysStatus, raise_for_status

from .coord import c_coord
from .coord_list import c_coord_list
from .coord_hash import c_coord_hash  # Registers coord_hash_t in the shared FFI.

from enum import IntEnum

class NavgridDirMode(IntEnum):
    DIR_4 = 0
    DIR_8 = 1


NAVGRID_ABI_VERSION = 2
NAVGRID_ABI_FINGERPRINT = 0x4E4752494402002F


def _check_navgrid_abi():
    mismatch = ffi.new("navgrid_abi_mismatch_t*")
    try:
        status = NavsysStatus(
            C.navgrid_check_abi(
                NAVGRID_ABI_VERSION,
                NAVGRID_ABI_FINGERPRINT,
                mismatch,
            )
        )
    except AttributeError as error:
        raise RuntimeError(
            "Navgrid ABI mismatch: runtime does not export navgrid_check_abi"
        ) from error
    if status is NavsysStatus.OK:
        return
    reason = {
        1: "version",
        2: "fingerprint",
    }.get(int(mismatch[0]), "unknown")
    raise RuntimeError(
        f"Navgrid ABI mismatch: {reason}; "
        f"expected version={NAVGRID_ABI_VERSION} "
        f"fingerprint=0x{NAVGRID_ABI_FINGERPRINT:016x}"
    )

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/navgrid/navcell.h */
typedef enum e_terrain_type {
    TERRAIN_TYPE_NORMAL = 0,
    TERRAIN_TYPE_WATER = 1,
    TERRAIN_TYPE_FOREST = 2,
    TERRAIN_TYPE_MOUNTAIN = 3,
    TERRAIN_TYPE_FORBIDDEN = 100
} terrain_type_t;

typedef struct s_navcell {
    terrain_type_t terrain;
    int height;
} navcell_t;

 navsys_status_t navcell_is_terrain_supported(
    terrain_type_t terrain, bool* out_supported);

 navsys_status_t navcell_validate(const navcell_t* cell);

 navsys_status_t navcell_init_checked(
    navcell_t* out_cell, terrain_type_t terrain, int32_t height);

 navsys_status_t navcell_create_checked(
    terrain_type_t terrain, int32_t height, navcell_t** out_cell);

 navsys_status_t navcell_copy_checked(
    const navcell_t* source, navcell_t** out_cell);

 navsys_status_t navcell_assign_checked(
    navcell_t* out_cell, const navcell_t* source);

 navcell_t* navcell_create_full(terrain_type_t terrain, int height);

 navcell_t* navcell_create();

 void navcell_destroy(navcell_t* nc);

 navcell_t* navcell_copy(const navcell_t* nc);

 int navcell_init_full(
    navcell_t* nc, terrain_type_t terrain, int height);

 int navcell_init(navcell_t* nc);

 int navcell_assign(navcell_t* nc, const navcell_t* src);

/* Source: byul/navsys/navgrid/navgrid.h */
typedef bool (*is_coord_blocked_func)(
    const void* context, int x, int y, void* userdata);

 bool is_coord_blocked_navgrid(
    const void* context, int x, int y, void* userdata);

typedef enum {
    NAVGRID_DIR_4,
    NAVGRID_DIR_8
} navgrid_dir_mode_t;

typedef struct s_navgrid navgrid_t;

typedef enum e_navgrid_abi_mismatch {
    NAVGRID_ABI_MATCH = 0,
    NAVGRID_ABI_VERSION_MISMATCH = 1,
    NAVGRID_ABI_FINGERPRINT_MISMATCH = 2
} navgrid_abi_mismatch_t;

typedef uint64_t navgrid_overlay_id_t;

typedef struct s_navgrid_cell_entry {
    coord_t coord;
    navcell_t cell;
    bool present;
    bool blocked;
} navgrid_cell_entry_t;

 uint32_t navgrid_get_abi_version(void);

 uint64_t navgrid_get_abi_fingerprint(void);

 navsys_status_t navgrid_check_abi(
    uint32_t expected_version,
    uint64_t expected_fingerprint,
    navgrid_abi_mismatch_t* out_mismatch);

 navgrid_t* navgrid_create();

 navgrid_t* navgrid_create_full(int width, int height,
    navgrid_dir_mode_t mode,
    is_coord_blocked_func is_coord_blocked_fn);

 void navgrid_destroy(navgrid_t* navgrid);

 navgrid_t* navgrid_copy(const navgrid_t* navgrid);

 uint32_t navgrid_hash(const navgrid_t* navgrid);

 bool navgrid_equal(const navgrid_t* a, const navgrid_t* b);

 int navgrid_get_width(const navgrid_t* navgrid);

 void navgrid_set_width(navgrid_t* navgrid, int width);

 int navgrid_get_height(const navgrid_t* navgrid);

 void navgrid_set_height(navgrid_t* navgrid, int height);

 void navgrid_set_is_coord_blocked_func(
    navgrid_t* navgrid, is_coord_blocked_func fn);

 is_coord_blocked_func navgrid_get_is_coord_blocked_fn(
    const navgrid_t* navgrid);

 navsys_status_t navgrid_fetch_is_coord_blocked_binding(
    const navgrid_t* navgrid,
    is_coord_blocked_func* out_fn,
    void** out_userdata);

 navsys_status_t navgrid_bind_is_coord_blocked_func(
    navgrid_t* navgrid, is_coord_blocked_func fn, void* userdata);

 navsys_status_t navgrid_unbind_is_coord_blocked_func(
    navgrid_t* navgrid);

 navgrid_dir_mode_t navgrid_get_mode(const navgrid_t* navgrid);

 void navgrid_set_mode(
    navgrid_t* navgrid, navgrid_dir_mode_t mode);

 bool navgrid_block_coord(navgrid_t* navgrid, int x, int y);

 bool navgrid_unblock_coord(navgrid_t* navgrid, int x, int y);

 bool navgrid_is_inside(const navgrid_t* navgrid, int x, int y);

 void navgrid_clear(navgrid_t* navgrid);

 navsys_status_t navgrid_block_coord_ex(
    navgrid_t* navgrid, int x, int y, bool* out_changed);

 navsys_status_t navgrid_unblock_coord_ex(
    navgrid_t* navgrid, int x, int y, bool* out_changed);

 navsys_status_t navgrid_clear_ex(
    navgrid_t* navgrid, bool* out_changed);

 bool navgrid_set_cell(
    navgrid_t* navgrid, int x, int y, const navcell_t* cell);

 int navgrid_fetch_cell(
    const navgrid_t* navgrid, int x, int y, navcell_t* out);

 navsys_status_t navgrid_set_cell_ex(
    navgrid_t* navgrid, int x, int y, const navcell_t* cell,
    navcell_t* out_prior, bool* out_had_prior, bool* out_changed);

 navsys_status_t navgrid_fetch_cell_ex(
    const navgrid_t* navgrid, int x, int y,
    navcell_t* out_cell, bool* out_present);

 navsys_status_t navgrid_apply_blocked_overlay(
    navgrid_t* navgrid, const coord_t* coords, size_t count,
    navgrid_overlay_id_t* out_overlay, size_t* out_changed_count);

 navsys_status_t navgrid_remove_blocked_overlay(
    navgrid_t* navgrid, navgrid_overlay_id_t overlay,
    size_t* out_changed_count);

 const coord_hash_t* navgrid_get_cell_map(const navgrid_t* navgrid);

 navsys_status_t navgrid_export_neighbors(
    const navgrid_t* navgrid, int x, int y, bool traversable_only,
    coord_t* out_coords, size_t capacity, size_t* out_count);

 navsys_status_t navgrid_export_neighbors_range(
    const navgrid_t* navgrid, int x, int y, int range,
    coord_t* out_coords, size_t capacity, size_t* out_count);

 navsys_status_t navgrid_fetch_neighbor_at_degree(
    const navgrid_t* navgrid, int x, int y,
    double degree, coord_t* out_coord);

 navsys_status_t navgrid_fetch_neighbor_at_goal(
    const navgrid_t* navgrid, const coord_t* center,
    const coord_t* goal, coord_t* out_coord);

 navsys_status_t navgrid_export_neighbors_at_degree_range(
    const navgrid_t* navgrid,
    const coord_t* center, const coord_t* goal,
    double start_deg, double end_deg, int range,
    coord_t* out_coords, size_t capacity, size_t* out_count);

 navsys_status_t navgrid_export_cells(
    const navgrid_t* navgrid, navgrid_cell_entry_t* out_entries,
    size_t capacity, size_t* out_count);

 coord_list_t* navgrid_copy_neighbors(
    const navgrid_t* navgrid, int x, int y);

 coord_list_t* navgrid_copy_neighbors_all(
    const navgrid_t* navgrid, int x, int y);

 coord_list_t* navgrid_copy_neighbors_all_range(
    navgrid_t* navgrid, int x, int y, int range);

 coord_t* navgrid_copy_neighbor_at_degree(const navgrid_t* navgrid,
    int x, int y, double degree);

 coord_t* navgrid_copy_neighbor_at_goal(const navgrid_t* navgrid,
    const coord_t* center, const coord_t* goal);

 coord_list_t* navgrid_copy_neighbors_at_degree_range(
    const navgrid_t* navgrid,
    const coord_t* center, const coord_t* goal,
    double start_deg, double end_deg,
    int range);
""")

class c_navgrid:
    def __init__(self, raw_ptr=None, own=False,
                 width=None, height=None, mode=NavgridDirMode.DIR_8,
                 py_func=None):
        self._own = own
        self._c = ffi.NULL
        self._finalizer = None
        self._py_is_coord_blocked_func = None
        self._ffi_is_coord_blocked_func = None
        created_callback = None

        if raw_ptr:
            self._c = raw_ptr
        elif width is not None and height is not None:
            _check_navgrid_abi()
            created_callback = self._wrap_py_func(py_func) if py_func else None
            fn = created_callback if created_callback is not None else ffi.NULL
            self._c = C.navgrid_create_full(width, height, mode.value, fn)
        else:
            _check_navgrid_abi()
            self._c = C.navgrid_create()

        if not self._c:
            raise MemoryError("navgrid allocation failed")

        if created_callback is not None:
            self._py_is_coord_blocked_func = py_func
            self._ffi_is_coord_blocked_func = created_callback

        if own:
            self._finalizer = weakref.finalize(self, C.navgrid_destroy, self._c)

    def _wrap_py_func(self, py_func):
        @ffi.callback("bool(const void*, int, int, void*)")
        def _wrapped(m_ptr, x, y, udata_ptr):
            grid = c_navgrid(raw_ptr=m_ptr, own=False)
            return bool(py_func(grid, x, y, None))

        return _wrapped

    # ───── 속성 접근 ─────
    @property
    def width(self):
        return C.navgrid_get_width(self._c)

    @width.setter
    def width(self, w):
        C.navgrid_set_width(self._c, w)

    @property
    def height(self):
        return C.navgrid_get_height(self._c)

    @height.setter
    def height(self, h):
        C.navgrid_set_height(self._c, h)

    def mode(self):
        return NavgridDirMode(C.navgrid_get_mode(self._c))

    def set_mode(self, mode: NavgridDirMode):
        C.navgrid_set_mode(self._c, mode.value)

    def set_is_coord_blocked_fn(self, py_func):
        if py_func is None:
            raise_for_status(
                C.navgrid_unbind_is_coord_blocked_func(self._c),
                "navgrid_unbind_is_coord_blocked_func",
            )
            self._py_is_coord_blocked_func = None
            self._ffi_is_coord_blocked_func = None
            return

        fn = self._wrap_py_func(py_func)
        raise_for_status(
            C.navgrid_bind_is_coord_blocked_func(self._c, fn, ffi.NULL),
            "navgrid_bind_is_coord_blocked_func",
        )
        self._py_is_coord_blocked_func = py_func
        self._ffi_is_coord_blocked_func = fn

    def get_is_coord_blocked_fn(self):
        return self._py_is_coord_blocked_func

    # ───── 장애물 관련 ─────
    def block(self, x, y):
        return bool(C.navgrid_block_coord(self._c, x, y))

    def unblock(self, x, y):
        return bool(C.navgrid_unblock_coord(self._c, x, y))

    def block_checked(self, x, y):
        changed = ffi.new("bool*")
        raise_for_status(
            C.navgrid_block_coord_ex(self._c, x, y, changed),
            "navgrid_block_coord_ex",
        )
        return bool(changed[0])

    def unblock_checked(self, x, y):
        changed = ffi.new("bool*")
        raise_for_status(
            C.navgrid_unblock_coord_ex(self._c, x, y, changed),
            "navgrid_unblock_coord_ex",
        )
        return bool(changed[0])

    def set_cell_checked(self, x, y, terrain, height):
        cell = ffi.new("navcell_t*", {"terrain": terrain, "height": height})
        prior = ffi.new("navcell_t*")
        had_prior = ffi.new("bool*")
        changed = ffi.new("bool*")
        raise_for_status(
            C.navgrid_set_cell_ex(
                self._c, x, y, cell, prior, had_prior, changed
            ),
            "navgrid_set_cell_ex",
        )
        return (
            (int(prior.terrain), int(prior.height)),
            bool(had_prior[0]),
            bool(changed[0]),
        )

    def fetch_cell_checked(self, x, y):
        cell = ffi.new("navcell_t*")
        present = ffi.new("bool*")
        raise_for_status(
            C.navgrid_fetch_cell_ex(self._c, x, y, cell, present),
            "navgrid_fetch_cell_ex",
        )
        return bool(present[0]), int(cell.terrain), int(cell.height)

    def apply_blocked_overlay(self, coords):
        normalized = [
            (coord.x, coord.y) if isinstance(coord, c_coord) else tuple(coord)
            for coord in coords
        ]
        buffer = (
            ffi.new(
                "coord_t[]",
                [{"x": int(x), "y": int(y)} for x, y in normalized],
            )
            if normalized
            else ffi.NULL
        )
        overlay = ffi.new("navgrid_overlay_id_t*")
        changed = ffi.new("size_t*")
        raise_for_status(
            C.navgrid_apply_blocked_overlay(
                self._c, buffer, len(normalized), overlay, changed
            ),
            "navgrid_apply_blocked_overlay",
        )
        return int(overlay[0]), int(changed[0])

    def remove_blocked_overlay(self, overlay):
        changed = ffi.new("size_t*")
        raise_for_status(
            C.navgrid_remove_blocked_overlay(self._c, overlay, changed),
            "navgrid_remove_blocked_overlay",
        )
        return int(changed[0])

    def is_blocked(self, x, y):
        return bool(C.is_coord_blocked_navgrid(self._c, x, y, ffi.NULL))

    def is_inside(self, x, y):
        return bool(C.navgrid_is_inside(self._c, x, y))

    def clear(self):
        C.navgrid_clear(self._c)

    @staticmethod
    def _coord_list_from_buffer(buffer, count):
        result = c_coord_list()
        try:
            for index in range(count):
                raise_for_status(
                    C.coord_list_push_back_ex(result._c, buffer + index),
                    "coord_list_push_back_ex",
                )
            return result
        except Exception:
            result.close()
            raise

    def _export_coord_list(self, function, *arguments):
        count = ffi.new("size_t*")
        raise_for_status(
            function(*arguments, ffi.NULL, 0, count),
            function.__name__,
        )
        if count[0] == 0:
            return c_coord_list()
        buffer = ffi.new("coord_t[]", count[0])
        raise_for_status(
            function(*arguments, buffer, count[0], count),
            function.__name__,
        )
        return self._coord_list_from_buffer(buffer, int(count[0]))

    def cell_entries(self):
        count = ffi.new("size_t*")
        raise_for_status(
            C.navgrid_export_cells(self._c, ffi.NULL, 0, count),
            "navgrid_export_cells",
        )
        if count[0] == 0:
            return []
        entries = ffi.new("navgrid_cell_entry_t[]", count[0])
        raise_for_status(
            C.navgrid_export_cells(self._c, entries, count[0], count),
            "navgrid_export_cells",
        )
        return [
            (
                int(entry.coord.x),
                int(entry.coord.y),
                int(entry.cell.terrain),
                int(entry.cell.height),
                bool(entry.present),
                bool(entry.blocked),
            )
            for entry in entries[0:count[0]]
        ]

    def blocked_coords(self):
        result = c_coord_list()
        try:
            for x, y, _terrain, _height, _present, blocked in self.cell_entries():
                if blocked:
                    coord = ffi.new("coord_t*", {"x": x, "y": y})
                    raise_for_status(
                        C.coord_list_push_back_ex(result._c, coord),
                        "coord_list_push_back_ex",
                    )
            return result
        except Exception:
            result.close()
            raise

    # ───── 이웃 탐색 ─────
    def neighbors(self, x, y):
        return self._export_coord_list(
            C.navgrid_export_neighbors, self._c, x, y, True
        )

    def neighbors_all(self, x, y):
        return self._export_coord_list(
            C.navgrid_export_neighbors, self._c, x, y, False
        )

    def neighbors_range(self, x, y, range_val):
        return self._export_coord_list(
            C.navgrid_export_neighbors_range,
            self._c,
            x,
            y,
            range_val,
        )

    def neighbor_at_degree(self, x, y, degree):
        output = ffi.new("coord_t*")
        status = NavsysStatus(
            C.navgrid_fetch_neighbor_at_degree(
                self._c, x, y, degree, output
            )
        )
        if status is NavsysStatus.NOT_FOUND:
            return None
        raise_for_status(status, "navgrid_fetch_neighbor_at_degree")
        return c_coord(output.x, output.y)

    def neighbor_at_goal(self, center: c_coord, goal: c_coord):
        output = ffi.new("coord_t*")
        status = NavsysStatus(
            C.navgrid_fetch_neighbor_at_goal(
                self._c, center.ptr(), goal.ptr(), output
            )
        )
        if status is NavsysStatus.NOT_FOUND:
            return None
        raise_for_status(status, "navgrid_fetch_neighbor_at_goal")
        return c_coord(output.x, output.y)

    def neighbors_at_degree_range(self, center: c_coord, goal: c_coord,
        start_deg: float, end_deg: float, range_val: int):

        return self._export_coord_list(
            C.navgrid_export_neighbors_at_degree_range,
            self._c,
            center.ptr(),
            goal.ptr(),
            start_deg,
            end_deg,
            range_val,
        )

    # ───── 복사 및 비교 ─────
    def copy(self):
        new_ptr = C.navgrid_copy(self._c)
        if new_ptr == ffi.NULL:
            raise MemoryError("navgrid copy failed")
        copied = c_navgrid(raw_ptr=new_ptr, own=True)
        copied._py_is_coord_blocked_func = self._py_is_coord_blocked_func
        copied._ffi_is_coord_blocked_func = self._ffi_is_coord_blocked_func
        return copied

    def equals(self, other):
        return isinstance(other, c_navgrid) and C.navgrid_equal(self._c, other._c)

    def __eq__(self, other):
        return self.equals(other)

    def __hash__(self):
        return int(C.navgrid_hash(self._c))

    def ptr(self):
        return self._c

    def __repr__(self):
        return f"c_navgrid({self.width}x{self.height}, mode={self.mode().name})"

    def __del__(self):
        self.close()

    def close(self):
        if self._own and self._finalizer and self._finalizer.alive:
            self._finalizer()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
