"""Low-level CFFI declarations for the Navsys status foundation."""

from enum import IntEnum

from .ffi_core import ffi


class NavsysStatus(IntEnum):
    """Stable Python view of ``navsys_status_t``."""

    OK = 0
    INVALID_ARGUMENT = -1
    OUT_OF_MEMORY = -2
    UNSUPPORTED = -3
    CALLBACK_FAILED = -4
    CORRUPT_STATE = -5
    NOT_FOUND = -6
    INVALIDATED = -7
    NO_PATH = -8
    CANCELLED = -9
    LIMIT_REACHED = -10
    INCOMPLETE = -11
    IN_PROGRESS = -12


class NavsysError(RuntimeError):
    """Base exception for a failed ``navsys_status_t`` operation."""

    def __init__(self, status: NavsysStatus | int, operation: str):
        self.status = status
        self.operation = operation
        name = status.name if isinstance(status, NavsysStatus) else str(status)
        super().__init__(f"{operation} failed: {name}")


class NavsysInvalidArgumentError(NavsysError, ValueError):
    """A Navsys argument or value is outside its declared contract."""


class NavsysOutOfMemoryError(NavsysError, MemoryError):
    """A Navsys allocation failed."""


class NavsysUnsupportedError(NavsysError, NotImplementedError):
    """The requested Navsys capability is unsupported."""


class NavsysCallbackError(NavsysError):
    """A callback invoked by Navsys failed."""


class NavsysCorruptStateError(NavsysError):
    """Navsys detected an invalid internal state."""


class NavsysNotFoundError(NavsysError, LookupError):
    """A requested Navsys object was not found."""


class NavsysInvalidatedError(NavsysError, ReferenceError):
    """A borrowed or retained Navsys object was invalidated."""


class NavsysNoPathError(NavsysError, LookupError):
    """No route exists for the requested query."""


class NavsysCancelledError(NavsysError, InterruptedError):
    """A Navsys operation was cancelled."""


class NavsysLimitReachedError(NavsysError):
    """A configured Navsys work or result limit was reached."""


class NavsysIncompleteError(NavsysError, BufferError):
    """The provided output capacity was insufficient."""


class NavsysInProgressError(NavsysError):
    """An asynchronous Navsys operation has not completed."""


_STATUS_EXCEPTIONS = {
    NavsysStatus.INVALID_ARGUMENT: NavsysInvalidArgumentError,
    NavsysStatus.OUT_OF_MEMORY: NavsysOutOfMemoryError,
    NavsysStatus.UNSUPPORTED: NavsysUnsupportedError,
    NavsysStatus.CALLBACK_FAILED: NavsysCallbackError,
    NavsysStatus.CORRUPT_STATE: NavsysCorruptStateError,
    NavsysStatus.NOT_FOUND: NavsysNotFoundError,
    NavsysStatus.INVALIDATED: NavsysInvalidatedError,
    NavsysStatus.NO_PATH: NavsysNoPathError,
    NavsysStatus.CANCELLED: NavsysCancelledError,
    NavsysStatus.LIMIT_REACHED: NavsysLimitReachedError,
    NavsysStatus.INCOMPLETE: NavsysIncompleteError,
    NavsysStatus.IN_PROGRESS: NavsysInProgressError,
}


def raise_for_status(status: NavsysStatus | int, operation: str) -> None:
    """Raise the typed Python exception for a non-OK Navsys status."""
    try:
        resolved = NavsysStatus(status)
    except ValueError:
        raise NavsysError(int(status), operation) from None
    if resolved is NavsysStatus.OK:
        return
    raise _STATUS_EXCEPTIONS[resolved](resolved, operation)


ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/navsys_status.h */
typedef enum e_navsys_status {
    NAVSYS_STATUS_OK = 0,
    NAVSYS_STATUS_INVALID_ARGUMENT = -1,
    NAVSYS_STATUS_OUT_OF_MEMORY = -2,
    NAVSYS_STATUS_UNSUPPORTED = -3,
    NAVSYS_STATUS_CALLBACK_FAILED = -4,
    NAVSYS_STATUS_CORRUPT_STATE = -5,
    NAVSYS_STATUS_NOT_FOUND = -6,
    NAVSYS_STATUS_INVALIDATED = -7,
    NAVSYS_STATUS_NO_PATH = -8,
    NAVSYS_STATUS_CANCELLED = -9,
    NAVSYS_STATUS_LIMIT_REACHED = -10,
    NAVSYS_STATUS_INCOMPLETE = -11,
    NAVSYS_STATUS_IN_PROGRESS = -12
} navsys_status_t;
""")
