"""Low-level CFFI declarations for the Navsys status foundation."""

from enum import IntEnum

from .ffi_core import ffi


class NavsysStatus(IntEnum):
    """Stable Python view of ``navsys_status_t``."""

    OK = 0
    INVALID_ARGUMENT = -1
    OUT_OF_MEMORY = -2
    UNSUPPORTED = -3
    CALLBACK_FAILED = -4
    CORRUPT_STATE = -5
    NOT_FOUND = -6
    INVALIDATED = -7
    NO_PATH = -8
    CANCELLED = -9
    LIMIT_REACHED = -10
    INCOMPLETE = -11
    IN_PROGRESS = -12


ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/navsys_status.h */
typedef enum e_navsys_status {
    NAVSYS_STATUS_OK = 0,
    NAVSYS_STATUS_INVALID_ARGUMENT = -1,
    NAVSYS_STATUS_OUT_OF_MEMORY = -2,
    NAVSYS_STATUS_UNSUPPORTED = -3,
    NAVSYS_STATUS_CALLBACK_FAILED = -4,
    NAVSYS_STATUS_CORRUPT_STATE = -5,
    NAVSYS_STATUS_NOT_FOUND = -6,
    NAVSYS_STATUS_INVALIDATED = -7,
    NAVSYS_STATUS_NO_PATH = -8,
    NAVSYS_STATUS_CANCELLED = -9,
    NAVSYS_STATUS_LIMIT_REACHED = -10,
    NAVSYS_STATUS_INCOMPLETE = -11,
    NAVSYS_STATUS_IN_PROGRESS = -12
} navsys_status_t;
""")
