"""Canonical one-shot Navsys path-search facade."""

from dataclasses import dataclass
from enum import IntEnum

from .ffi_core import ffi, C
from .coord import c_coord
from .navgrid import c_navgrid
from .route import c_route
from .route_finder import RouteFinderType
from .navsys_status import NavsysStatus, raise_for_status


class NavsysAlgorithmConfigKind(IntEnum):
    NONE = 0
    FRINGE_SEARCH = 1
    RTA_STAR = 2
    SMA_STAR = 3
    WEIGHTED_ASTAR = 4


@dataclass(frozen=True)
class NavsysSearchStats:
    expansions: int
    route_length: int
    route_cost: float
    complete: bool
    partial: bool
    algorithm: RouteFinderType
    status: NavsysStatus


@dataclass(frozen=True)
class NavsysAlgorithmDescriptor:
    algorithm: RouteFinderType
    required_config: NavsysAlgorithmConfigKind
    supported: bool
    experimental: bool
    complete: bool
    optimal: bool
    bounded_suboptimal: bool
    incremental: bool


ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/navsys.h */
typedef struct s_navgrid navgrid_t;
typedef struct s_route route_t;

typedef enum e_navsys_algorithm_config_kind {
    NAVSYS_ALGORITHM_CONFIG_NONE = 0,
    NAVSYS_ALGORITHM_CONFIG_FRINGE_SEARCH = 1,
    NAVSYS_ALGORITHM_CONFIG_RTA_STAR = 2,
    NAVSYS_ALGORITHM_CONFIG_SMA_STAR = 3,
    NAVSYS_ALGORITHM_CONFIG_WEIGHTED_ASTAR = 4
} navsys_algorithm_config_kind_t;

typedef struct s_navsys_algorithm_config {
    size_t struct_size;
    uint32_t version;
    navsys_algorithm_config_kind_t kind;
    union {
        route_finder_fringe_search_config_t fringe_search;
        route_finder_rta_star_config_t rta_star;
        route_finder_sma_star_config_t sma_star;
        route_finder_weighted_astar_config_t weighted_astar;
    } value;
} navsys_algorithm_config_t;

typedef struct s_navsys_path_query {
    size_t struct_size;
    uint32_t version;
    navgrid_t* grid;
    coord_t start;
    coord_t goal;
    route_finder_type_t algorithm;
    const navsys_algorithm_config_t* algorithm_config;
    size_t max_expansions;
    route_finder_cancel_func cancel_func;
    void* cancel_userdata;
} navsys_path_query_t;

typedef struct s_navsys_search_stats {
    size_t expansions;
    size_t route_length;
    float route_cost;
    bool complete;
    bool partial;
    route_finder_type_t algorithm;
    navsys_status_t status;
} navsys_search_stats_t;

typedef struct s_navsys_algorithm_descriptor {
    size_t struct_size;
    uint32_t version;
    route_finder_type_t algorithm;
    navsys_algorithm_config_kind_t required_config;
    bool supported;
    bool experimental;
    bool complete;
    bool optimal;
    bool bounded_suboptimal;
    bool incremental;
} navsys_algorithm_descriptor_t;

 navsys_status_t navsys_path_query_init(
    navsys_path_query_t* out_query, navgrid_t* grid,
    const coord_t* start, const coord_t* goal);

 navsys_status_t navsys_algorithm_config_init(
    navsys_algorithm_config_t* out_config,
    navsys_algorithm_config_kind_t kind);

 bool navsys_is_algorithm_supported(
    route_finder_type_t algorithm);

 navsys_status_t navsys_get_algorithm_descriptor(
    route_finder_type_t algorithm,
    navsys_algorithm_descriptor_t* out_descriptor);

 navsys_status_t navsys_find_path(
    const navsys_path_query_t* query,
    route_t** out_route,
    navsys_search_stats_t* out_stats);

 route_t* navsys_find_astar(navgrid_t* ng, const coord_t* start, const coord_t* goal);

 route_t* navsys_find_bfs(navgrid_t* ng, const coord_t* start, const coord_t* goal);

 route_t* navsys_find_dfs(navgrid_t* ng, const coord_t* start, const coord_t* goal);

 route_t* navsys_find_dijkstra(navgrid_t* ng, const coord_t* start, const coord_t* goal);

 route_t* navsys_find_greedy_best_first(navgrid_t* ng, const coord_t* start, const coord_t* goal);

 route_t* navsys_find_fast_marching(navgrid_t* ng, const coord_t* start, const coord_t* goal);

 route_t* navsys_find_ida_star(navgrid_t* ng, const coord_t* start, const coord_t* goal);

 route_t* navsys_find_fringe_search(navgrid_t* ng, const coord_t* start, const coord_t* goal, float delta_epsilon);

 route_t* navsys_find_rta_star(navgrid_t* ng, const coord_t* start, const coord_t* goal, int depth_limit);

 route_t* navsys_find_sma_star(navgrid_t* ng, const coord_t* start, const coord_t* goal, int memory_limit);

 route_t* navsys_find_weighted_astar(navgrid_t* ng, const coord_t* start, const coord_t* goal, float weight);

 route_t* navsys_find_dstar_lite(navgrid_t* ng, const coord_t* start, const coord_t* goal);
""")


def is_algorithm_supported(algorithm):
    """Return whether the canonical facade executes ``algorithm``."""
    return bool(C.navsys_is_algorithm_supported(int(algorithm)))


def get_algorithm_descriptor(algorithm):
    """Return machine-readable capability claims for ``algorithm``."""
    output = ffi.new("navsys_algorithm_descriptor_t*")
    raise_for_status(
        C.navsys_get_algorithm_descriptor(int(algorithm), output),
        "navsys_get_algorithm_descriptor",
    )
    return NavsysAlgorithmDescriptor(
        algorithm=RouteFinderType(output.algorithm),
        required_config=NavsysAlgorithmConfigKind(output.required_config),
        supported=bool(output.supported),
        experimental=bool(output.experimental),
        complete=bool(output.complete),
        optimal=bool(output.optimal),
        bounded_suboptimal=bool(output.bounded_suboptimal),
        incremental=bool(output.incremental),
    )


def find_path(grid, start, goal, algorithm=RouteFinderType.ASTAR, *,
              max_expansions=10000, weight=None, cancel=None):
    """Execute a validated one-shot query and return ``(status, route, stats)``."""
    if not isinstance(grid, c_navgrid):
        raise TypeError("grid must be c_navgrid")
    if not isinstance(start, c_coord) or not isinstance(goal, c_coord):
        raise TypeError("start and goal must be c_coord")

    query = ffi.new("navsys_path_query_t*")
    raise_for_status(
        C.navsys_path_query_init(query, grid.ptr(), start.ptr(), goal.ptr()),
        "navsys_path_query_init",
    )
    query.algorithm = int(algorithm)
    query.max_expansions = max_expansions

    config = None
    if weight is not None:
        config = ffi.new("navsys_algorithm_config_t*")
        raise_for_status(
            C.navsys_algorithm_config_init(
                config, C.NAVSYS_ALGORITHM_CONFIG_WEIGHTED_ASTAR),
            "navsys_algorithm_config_init",
        )
        config.value.weighted_astar.weight = weight
        query.algorithm_config = config

    callback_error = []
    cancel_callback = None
    if cancel is not None:
        @ffi.callback("bool(void*)")
        def cancel_callback(_):
            try:
                return bool(cancel())
            except BaseException as exc:
                callback_error.append(exc)
                return True
        query.cancel_func = cancel_callback

    out_route = ffi.new("route_t**")
    out_stats = ffi.new("navsys_search_stats_t*")
    status = NavsysStatus(C.navsys_find_path(query, out_route, out_stats))
    if callback_error:
        if out_route[0] != ffi.NULL:
            C.route_destroy(out_route[0])
        raise callback_error[0]
    if status not in {
        NavsysStatus.OK, NavsysStatus.NO_PATH,
        NavsysStatus.CANCELLED, NavsysStatus.LIMIT_REACHED,
    }:
        raise_for_status(status, "navsys_find_path")

    route = (c_route(raw_ptr=out_route[0], own=True)
             if out_route[0] != ffi.NULL else None)
    stats = NavsysSearchStats(
        expansions=int(out_stats.expansions),
        route_length=int(out_stats.route_length),
        route_cost=float(out_stats.route_cost),
        complete=bool(out_stats.complete),
        partial=bool(out_stats.partial),
        algorithm=RouteFinderType(out_stats.algorithm),
        status=NavsysStatus(out_stats.status),
    )
    return status, route, stats
