import weakref

from .ffi_core import ffi, C
from .navsys_status import NavsysStatus, raise_for_status
from .coord import c_coord
from .coord_list import c_coord_list
from .coord_hash import c_coord_hash  # Registers coord_hash_t in the shared FFI.
from .navgrid import c_navgrid  # Registers navgrid_t in the shared FFI.


OBSTACLE_ABI_VERSION = 2
OBSTACLE_ABI_FINGERPRINT = 0x4F42535402000000


def _check_obstacle_abi():
    mismatch = ffi.new("obstacle_abi_mismatch_t*")
    try:
        status = NavsysStatus(
            C.obstacle_check_abi(
                OBSTACLE_ABI_VERSION,
                OBSTACLE_ABI_FINGERPRINT,
                mismatch,
            )
        )
    except AttributeError as error:
        raise RuntimeError(
            "Obstacle ABI mismatch: runtime does not export obstacle_check_abi"
        ) from error
    if status is NavsysStatus.OK:
        return
    reason = {1: "version", 2: "fingerprint"}.get(
        int(mismatch[0]), "unknown"
    )
    raise RuntimeError(
        f"Obstacle ABI mismatch: {reason}; "
        f"expected version={OBSTACLE_ABI_VERSION} "
        f"fingerprint=0x{OBSTACLE_ABI_FINGERPRINT:016x}"
    )


ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/obstacle/obstacle_core.h */
typedef struct s_obstacle obstacle_t;

typedef enum e_obstacle_abi_mismatch {
    OBSTACLE_ABI_MATCH = 0,
    OBSTACLE_ABI_VERSION_MISMATCH = 1,
    OBSTACLE_ABI_FINGERPRINT_MISMATCH = 2
} obstacle_abi_mismatch_t;

 uint32_t obstacle_get_abi_version(void);

 uint64_t obstacle_get_abi_fingerprint(void);

 navsys_status_t obstacle_check_abi(
    uint32_t expected_version,
    uint64_t expected_fingerprint,
    obstacle_abi_mismatch_t* out_mismatch);

 size_t obstacle_sizeof(void);

 size_t obstacle_alignof(void);

typedef enum e_obstacle_navgrid_merge_policy {

    OBSTACLE_NAVGRID_MERGE_PRESERVE_BASE = 0
} obstacle_navgrid_merge_policy_t;

typedef bool (*obstacle_navgrid_cancel_func)(void* userdata);

typedef struct s_obstacle_navgrid_apply_options {
    uint32_t struct_size;
    uint32_t abi_version;

    uint32_t merge_policy;
    obstacle_navgrid_cancel_func cancel_func;
    void* cancel_userdata;
} obstacle_navgrid_apply_options_t;

typedef struct s_obstacle_navgrid_overlay_token {
    uint32_t struct_size;
    uint32_t abi_version;
    uint64_t owner_cookie;
    navgrid_overlay_id_t overlay;
} obstacle_navgrid_overlay_token_t;

 navsys_status_t obstacle_create_checked(
    int32_t x0, int32_t y0, int32_t width, int32_t height,
    obstacle_t** out_obstacle);

 obstacle_t* obstacle_create();

 obstacle_t* obstacle_create_full(
    int x0, int y0, int width, int height);

 void obstacle_destroy(obstacle_t* obstacle);

 navsys_status_t obstacle_copy_checked(
    const obstacle_t* source, obstacle_t** out_obstacle);

 obstacle_t* obstacle_copy(const obstacle_t* obstacle);

 bool obstacle_equal(const obstacle_t* a, const obstacle_t* b);

 uint32_t obstacle_hash(const obstacle_t* obstacle);

 void obstacle_set_origin(obstacle_t* obstacle, int x0, int y0);

 void obstacle_fetch_origin(
    const obstacle_t* obstacle, int* out_x0, int* out_y0);

 int obstacle_get_width(const obstacle_t* m);

 void obstacle_set_width(obstacle_t* m, int width);

 int obstacle_get_height(const obstacle_t* m);

 void obstacle_set_height(obstacle_t* m, int height);

 const coord_hash_t* obstacle_get_blocked_coords(
    const obstacle_t* obstacle);

 navsys_status_t obstacle_set_blocked(
    obstacle_t* obstacle, int32_t x, int32_t y,
    bool blocked, bool* out_changed);

 navsys_status_t obstacle_export_blocked(
    const obstacle_t* obstacle, coord_t* out_coords,
    size_t capacity, size_t* out_count);

 bool obstacle_block_coord(obstacle_t* m, int x, int y);

 bool obstacle_unblock_coord(obstacle_t* m, int x, int y);

 bool obstacle_is_inside(const obstacle_t* m, int x, int y);

 void obstacle_clear(obstacle_t* m);

 coord_list_t* obstacle_clone_neighbors(
    const obstacle_t* m, int x, int y);

 coord_list_t* obstacle_clone_neighbors_all(
    const obstacle_t* m, int x, int y);

 coord_list_t* obstacle_clone_neighbors_all_range(
    obstacle_t* m, int x, int y, int range);

 coord_t* obstacle_clone_neighbor_at_degree(const obstacle_t* m,
    int x, int y, double degree);

 coord_t* obstacle_clone_neighbor_at_goal(const obstacle_t* m,
    const coord_t* center, const coord_t* goal);

 coord_list_t* obstacle_clone_neighbors_at_degree_range(
    const obstacle_t* m,
    const coord_t* center, const coord_t* goal,
    double start_deg, double end_deg,
    int range);

 bool obstacle_is_coord_blocked(
    const obstacle_t* obstacle, int x, int y);

 navsys_status_t obstacle_apply_to_navgrid_checked(
    const obstacle_t* obstacle,
    navgrid_t* navgrid,
    const obstacle_navgrid_apply_options_t* options,
    obstacle_navgrid_overlay_token_t* out_overlay,
    size_t* out_changed_count);

 navsys_status_t obstacle_remove_from_navgrid_checked(
    navgrid_t* navgrid,
    obstacle_navgrid_overlay_token_t* overlay,
    size_t* out_changed_count);

 void obstacle_apply_to_navgrid(const obstacle_t* obstacle, navgrid_t* navgrid);

 void obstacle_remove_from_navgrid(
    const obstacle_t* obstacle, navgrid_t* navgrid);

 void obstacle_block_range(obstacle_t* obs, int x, int y, int range);

 void obstacle_block_straight(obstacle_t* obs,
    int x0, int y0, int x1, int y1, int range);

/* Source: byul/navsys/obstacle/obstacle.h */
navsys_status_t obstacle_export_neighbors(
    const obstacle_t* obstacle, int32_t x, int32_t y,
    bool traversable_only, coord_t* out_coords,
    size_t capacity, size_t* out_count);

 navsys_status_t obstacle_export_neighbors_range(
    const obstacle_t* obstacle, int32_t x, int32_t y, int32_t range,
    coord_t* out_coords, size_t capacity, size_t* out_count);

 navsys_status_t obstacle_fetch_neighbor_at_degree(
    const obstacle_t* obstacle, int32_t x, int32_t y,
    double degree, coord_t* out_coord);

 navsys_status_t obstacle_fetch_neighbor_at_goal(
    const obstacle_t* obstacle, const coord_t* center,
    const coord_t* goal, coord_t* out_coord);

 navsys_status_t obstacle_export_neighbors_at_degree_range(
    const obstacle_t* obstacle,
    const coord_t* center, const coord_t* goal,
    double start_deg, double end_deg, int32_t range,
    coord_t* out_coords, size_t capacity, size_t* out_count);

 coord_list_t* obstacle_create_neighbors(
    const obstacle_t* obstacle, int32_t x, int32_t y);

 coord_list_t* obstacle_create_neighbors_all(
    const obstacle_t* obstacle, int32_t x, int32_t y);

 coord_list_t* obstacle_create_neighbors_all_range(
    const obstacle_t* obstacle, int32_t x, int32_t y, int32_t range);

 coord_t* obstacle_create_neighbor_at_degree(
    const obstacle_t* obstacle, int32_t x, int32_t y, double degree);

 coord_t* obstacle_create_neighbor_at_goal(
    const obstacle_t* obstacle, const coord_t* center, const coord_t* goal);

 coord_list_t* obstacle_create_neighbors_at_degree_range(
    const obstacle_t* obstacle,
    const coord_t* center, const coord_t* goal,
    double start_deg, double end_deg, int32_t range);

 navsys_status_t obstacle_block_square(
    obstacle_t* obstacle, int32_t x, int32_t y, int32_t radius,
    size_t* out_changed_count);

 navsys_status_t obstacle_block_line(
    obstacle_t* obstacle,
    int32_t x0, int32_t y0, int32_t x1, int32_t y1,
    int32_t radius, size_t* out_changed_count);

typedef enum e_obstacle_raster_rule {
    OBSTACLE_RASTER_CELL_CENTER = 0,
    OBSTACLE_RASTER_ALL_TOUCHED = 1
} obstacle_raster_rule_t;

typedef enum e_obstacle_polygon_fill_rule {
    OBSTACLE_POLYGON_EVEN_ODD = 0,
    OBSTACLE_POLYGON_NON_ZERO = 1
} obstacle_polygon_fill_rule_t;

typedef bool (*obstacle_generate_cancel_func)(void* userdata);

typedef struct s_obstacle_generate_options {
    uint32_t struct_size;
    uint32_t abi_version;
    obstacle_raster_rule_t raster_rule;
    uint32_t reserved0;
    uint64_t seed;
    uint64_t max_cells;
    obstacle_generate_cancel_func cancel_func;
    void* cancel_userdata;
} obstacle_generate_options_t;

typedef enum e_obstacle_enclosure_side {
    OBSTACLE_ENCLOSURE_CLOSED = 0,
    OBSTACLE_ENCLOSURE_OPEN_RIGHT = 1,
    OBSTACLE_ENCLOSURE_OPEN_UP = 2,
    OBSTACLE_ENCLOSURE_OPEN_LEFT = 3,
    OBSTACLE_ENCLOSURE_OPEN_DOWN = 4
} obstacle_enclosure_side_t;

typedef enum e_obstacle_spiral_direction {
    OBSTACLE_SPIRAL_CLOCKWISE = 0,
    OBSTACLE_SPIRAL_COUNTER_CLOCKWISE = 1
} obstacle_spiral_direction_t;

typedef enum e_obstacle_spiral_clip_rule {
    OBSTACLE_SPIRAL_CLIP_PATH_ONLY = 0,
    OBSTACLE_SPIRAL_CLIP_OUTPUT = 1
} obstacle_spiral_clip_rule_t;

typedef struct s_obstacle_enclosure_desc {
    uint32_t struct_size;
    uint32_t abi_version;
    int32_t x0;
    int32_t y0;
    int32_t width;
    int32_t height;
    uint32_t wall_thickness_cells;
    obstacle_enclosure_side_t open_side;
    uint32_t aperture_offset_cells;
    uint32_t aperture_length_cells;
} obstacle_enclosure_desc_t;

typedef struct s_obstacle_cross_desc {
    uint32_t struct_size;
    uint32_t abi_version;
    coord_t center;
    uint32_t arm_length_cells;
    uint32_t radius_cells;
    uint32_t reserved0;
    uint32_t reserved1;
} obstacle_cross_desc_t;

typedef struct s_obstacle_spiral_desc {
    uint32_t struct_size;
    uint32_t abi_version;
    coord_t center;
    uint32_t max_radius_cells;
    uint32_t pitch_cells;
    uint32_t path_radius_cells;
    obstacle_spiral_direction_t direction;
    obstacle_spiral_clip_rule_t clip_rule;
    uint32_t reserved0;
} obstacle_spiral_desc_t;

 navsys_status_t obstacle_generate_options_init(
    obstacle_generate_options_t* options);

 navsys_status_t obstacle_generate_filled_rect(
    int32_t x0, int32_t y0, int32_t width, int32_t height,
    const obstacle_generate_options_t* options,
    obstacle_t** out_obstacle);

 navsys_status_t obstacle_generate_rect_outline(
    int32_t x0, int32_t y0, int32_t width, int32_t height,
    uint32_t wall_thickness_cells,
    const obstacle_generate_options_t* options,
    obstacle_t** out_obstacle);

 navsys_status_t obstacle_generate_random_rect(
    int32_t x0, int32_t y0, int32_t width, int32_t height,
    double blocked_probability,
    const obstacle_generate_options_t* options,
    obstacle_t** out_obstacle);

 navsys_status_t obstacle_generate_line(
    const coord_t* start, const coord_t* end, uint32_t radius_cells,
    const obstacle_generate_options_t* options,
    obstacle_t** out_obstacle);

 navsys_status_t obstacle_generate_polygon(
    const coord_t* vertices, size_t vertex_count,
    obstacle_polygon_fill_rule_t fill_rule,
    const obstacle_generate_options_t* options,
    obstacle_t** out_obstacle);

 navsys_status_t obstacle_generate_polygon_outline(
    const coord_t* vertices, size_t vertex_count, uint32_t radius_cells,
    const obstacle_generate_options_t* options,
    obstacle_t** out_obstacle);

 navsys_status_t obstacle_generate_triangle(
    const coord_t* a, const coord_t* b, const coord_t* c,
    obstacle_polygon_fill_rule_t fill_rule,
    const obstacle_generate_options_t* options,
    obstacle_t** out_obstacle);

 navsys_status_t obstacle_generate_triangle_outline(
    const coord_t* a, const coord_t* b, const coord_t* c,
    uint32_t radius_cells,
    const obstacle_generate_options_t* options,
    obstacle_t** out_obstacle);

 navsys_status_t obstacle_enclosure_desc_init(
    obstacle_enclosure_desc_t* desc);

 navsys_status_t obstacle_cross_desc_init(
    obstacle_cross_desc_t* desc);

 navsys_status_t obstacle_spiral_desc_init(
    obstacle_spiral_desc_t* desc);

 navsys_status_t obstacle_generate_enclosure(
    const obstacle_enclosure_desc_t* desc,
    const obstacle_generate_options_t* options,
    obstacle_t** out_obstacle);

 navsys_status_t obstacle_generate_cross(
    const obstacle_cross_desc_t* desc,
    const obstacle_generate_options_t* options,
    obstacle_t** out_obstacle);

 navsys_status_t obstacle_generate_spiral(
    const obstacle_spiral_desc_t* desc,
    const obstacle_generate_options_t* options,
    obstacle_t** out_obstacle);

 obstacle_t* obstacle_make_rect_all_blocked(
    int x0, int y0, int width, int height);

 obstacle_t* obstacle_make_rect_random_blocked(
    int x0, int y0, int width, int height, float ratio);

 obstacle_t* obstacle_make_beam(
    const coord_t* start, const coord_t* goal, int range);

 obstacle_t* obstacle_make_torus(
    const coord_t* start, const coord_t* goal, int thickness);

typedef enum e_enclosure_open_dir {
    ENCLOSURE_OPEN_UNKNOWN,
    ENCLOSURE_OPEN_RIGHT,
    ENCLOSURE_OPEN_UP,
    ENCLOSURE_OPEN_LEFT,
    ENCLOSURE_OPEN_DOWN,
} enclosure_open_dir_t;

 obstacle_t* obstacle_make_enclosure(
    const coord_t* start, const coord_t* goal, int thickness,
    enclosure_open_dir_t open);

 obstacle_t* obstacle_make_cross(
    const coord_t* center, int length, int range);

typedef enum e_spiral_dir {
    SPIRAL_CLOCKWISE,
    SPIRAL_COUNTER_CLOCKWISE
} spiral_dir_t;

 obstacle_t* obstacle_make_spiral(
    const coord_t* center,
    int radius,
    int turns,
    int range,
    int gap,
    spiral_dir_t direction
);

 obstacle_t* obstacle_make_triangle(
    const coord_t* a,
    const coord_t* b,
    const coord_t* c);

 obstacle_t* obstacle_make_triangle_torus(
    const coord_t* a,
    const coord_t* b,
    const coord_t* c,
    int thickness);

 obstacle_t* obstacle_make_polygon(coord_list_t* list);

 obstacle_t* obstacle_make_polygon_torus(
    coord_list_t* list, int thickness);
""")


def _generator_options(seed=0, max_cells=0, raster_rule=None):
    """Build call-scoped checked-generator options without callback retention."""
    options = ffi.new("obstacle_generate_options_t*")
    raise_for_status(
        C.obstacle_generate_options_init(options),
        "obstacle_generate_options_init",
    )
    options.seed = seed
    options.max_cells = max_cells
    if raster_rule is not None:
        options.raster_rule = raster_rule
    return options


def _coord_argument(value, argument):
    if isinstance(value, c_coord):
        return value._require_open()
    try:
        x, y = value
    except (TypeError, ValueError):
        raise TypeError(f"{argument} must be c_coord or an (x, y) pair") from None
    return ffi.new("coord_t*", {"x": x, "y": y})


def _coord_buffer(vertices):
    values = [(value.x, value.y) if isinstance(value, c_coord) else tuple(value)
              for value in vertices]
    if any(len(value) != 2 for value in values):
        raise TypeError("each vertex must be c_coord or an (x, y) pair")
    return ffi.new("coord_t[]", [dict(x=x, y=y) for x, y in values])


class c_obstacle:
    def __init__(self, x0=0, y0=0, width=0, height=0, raw_ptr=None, own=True):
        _check_obstacle_abi()
        self._own = own
        self._c = raw_ptr if raw_ptr is not None else ffi.NULL
        self._finalizer = None
        if self._c == ffi.NULL:
            output = ffi.new("obstacle_t**")
            raise_for_status(
                C.obstacle_create_checked(x0, y0, width, height, output),
                "obstacle_create_checked",
            )
            self._c = output[0]
        if own:
            self._finalizer = weakref.finalize(self, C.obstacle_destroy, self._c)

    @classmethod
    def _from_generator(cls, operation, invoke):
        output = ffi.new("obstacle_t**")
        raise_for_status(invoke(output), operation)
        if output[0] == ffi.NULL:
            raise RuntimeError(f"{operation} returned OK with a NULL obstacle")
        return cls(raw_ptr=output[0], own=True)

    @classmethod
    def generate_filled_rect(cls, x0, y0, width, height, *, max_cells=0):
        options = _generator_options(max_cells=max_cells)
        return cls._from_generator(
            "obstacle_generate_filled_rect",
            lambda output: C.obstacle_generate_filled_rect(
                x0, y0, width, height, options, output),
        )

    @classmethod
    def generate_rect_outline(
        cls, x0, y0, width, height, wall_thickness_cells,
        *, max_cells=0,
    ):
        options = _generator_options(max_cells=max_cells)
        return cls._from_generator(
            "obstacle_generate_rect_outline",
            lambda output: C.obstacle_generate_rect_outline(
                x0, y0, width, height, wall_thickness_cells,
                options, output),
        )

    @classmethod
    def generate_random_rect(
        cls, x0, y0, width, height, blocked_probability,
        *, seed, max_cells=0,
    ):
        options = _generator_options(seed=seed, max_cells=max_cells)
        return cls._from_generator(
            "obstacle_generate_random_rect",
            lambda output: C.obstacle_generate_random_rect(
                x0, y0, width, height, blocked_probability,
                options, output),
        )

    @classmethod
    def generate_line(
        cls, start, end, radius_cells=0, *, max_cells=0, raster_rule=None,
    ):
        start_ptr = _coord_argument(start, "start")
        end_ptr = _coord_argument(end, "end")
        options = _generator_options(
            max_cells=max_cells, raster_rule=raster_rule)
        return cls._from_generator(
            "obstacle_generate_line",
            lambda output: C.obstacle_generate_line(
                start_ptr, end_ptr, radius_cells, options, output),
        )

    @classmethod
    def generate_polygon(
        cls, vertices, fill_rule=None, *, max_cells=0, raster_rule=None,
    ):
        buffer = _coord_buffer(vertices)
        if fill_rule is None:
            fill_rule = C.OBSTACLE_POLYGON_EVEN_ODD
        options = _generator_options(
            max_cells=max_cells, raster_rule=raster_rule)
        return cls._from_generator(
            "obstacle_generate_polygon",
            lambda output: C.obstacle_generate_polygon(
                buffer, len(buffer), fill_rule, options, output),
        )

    @classmethod
    def generate_polygon_outline(
        cls, vertices, radius_cells=0, *, max_cells=0, raster_rule=None,
    ):
        buffer = _coord_buffer(vertices)
        options = _generator_options(
            max_cells=max_cells, raster_rule=raster_rule)
        return cls._from_generator(
            "obstacle_generate_polygon_outline",
            lambda output: C.obstacle_generate_polygon_outline(
                buffer, len(buffer), radius_cells, options, output),
        )

    @classmethod
    def generate_triangle(
        cls, a, b, c, fill_rule=None, *, max_cells=0, raster_rule=None,
    ):
        points = [_coord_argument(value, name)
                  for value, name in ((a, "a"), (b, "b"), (c, "c"))]
        if fill_rule is None:
            fill_rule = C.OBSTACLE_POLYGON_EVEN_ODD
        options = _generator_options(
            max_cells=max_cells, raster_rule=raster_rule)
        return cls._from_generator(
            "obstacle_generate_triangle",
            lambda output: C.obstacle_generate_triangle(
                points[0], points[1], points[2], fill_rule, options, output),
        )

    @classmethod
    def generate_triangle_outline(
        cls, a, b, c, radius_cells=0, *, max_cells=0, raster_rule=None,
    ):
        points = [_coord_argument(value, name)
                  for value, name in ((a, "a"), (b, "b"), (c, "c"))]
        options = _generator_options(
            max_cells=max_cells, raster_rule=raster_rule)
        return cls._from_generator(
            "obstacle_generate_triangle_outline",
            lambda output: C.obstacle_generate_triangle_outline(
                points[0], points[1], points[2], radius_cells,
                options, output),
        )

    @classmethod
    def generate_enclosure(
        cls, x0, y0, width, height, wall_thickness_cells,
        *, open_side=None, aperture_offset_cells=0,
        aperture_length_cells=0, max_cells=0,
    ):
        desc = ffi.new("obstacle_enclosure_desc_t*")
        raise_for_status(
            C.obstacle_enclosure_desc_init(desc),
            "obstacle_enclosure_desc_init",
        )
        desc.x0, desc.y0 = x0, y0
        desc.width, desc.height = width, height
        desc.wall_thickness_cells = wall_thickness_cells
        if open_side is not None:
            desc.open_side = open_side
        desc.aperture_offset_cells = aperture_offset_cells
        desc.aperture_length_cells = aperture_length_cells
        options = _generator_options(max_cells=max_cells)
        return cls._from_generator(
            "obstacle_generate_enclosure",
            lambda output: C.obstacle_generate_enclosure(
                desc, options, output),
        )

    @classmethod
    def generate_cross(
        cls, center, arm_length_cells, radius_cells=0, *, max_cells=0,
    ):
        center_ptr = _coord_argument(center, "center")
        desc = ffi.new("obstacle_cross_desc_t*")
        raise_for_status(C.obstacle_cross_desc_init(desc),
                         "obstacle_cross_desc_init")
        desc.center = center_ptr[0]
        desc.arm_length_cells = arm_length_cells
        desc.radius_cells = radius_cells
        options = _generator_options(max_cells=max_cells)
        return cls._from_generator(
            "obstacle_generate_cross",
            lambda output: C.obstacle_generate_cross(desc, options, output),
        )

    @classmethod
    def generate_spiral(
        cls, center, max_radius_cells, pitch_cells, path_radius_cells=0,
        *, direction=None, clip_rule=None, max_cells=0,
    ):
        center_ptr = _coord_argument(center, "center")
        desc = ffi.new("obstacle_spiral_desc_t*")
        raise_for_status(C.obstacle_spiral_desc_init(desc),
                         "obstacle_spiral_desc_init")
        desc.center = center_ptr[0]
        desc.max_radius_cells = max_radius_cells
        desc.pitch_cells = pitch_cells
        desc.path_radius_cells = path_radius_cells
        if direction is not None:
            desc.direction = direction
        if clip_rule is not None:
            desc.clip_rule = clip_rule
        options = _generator_options(max_cells=max_cells)
        return cls._from_generator(
            "obstacle_generate_spiral",
            lambda output: C.obstacle_generate_spiral(desc, options, output),
        )

    @property
    def origin(self):
        x0 = ffi.new("int*")
        y0 = ffi.new("int*")
        C.obstacle_fetch_origin(self._c, x0, y0)
        return int(x0[0]), int(y0[0])

    @origin.setter
    def origin(self, value):
        C.obstacle_set_origin(self._c, int(value[0]), int(value[1]))

    @property
    def width(self):
        return int(C.obstacle_get_width(self._c))

    @width.setter
    def width(self, value):
        C.obstacle_set_width(self._c, int(value))

    @property
    def height(self):
        return int(C.obstacle_get_height(self._c))

    @height.setter
    def height(self, value):
        C.obstacle_set_height(self._c, int(value))

    def set_blocked(self, x, y, blocked=True):
        changed = ffi.new("bool*")
        raise_for_status(
            C.obstacle_set_blocked(self._c, x, y, blocked, changed),
            "obstacle_set_blocked",
        )
        return bool(changed[0])

    def blocked_coords(self):
        count = ffi.new("size_t*")
        raise_for_status(
            C.obstacle_export_blocked(self._c, ffi.NULL, 0, count),
            "obstacle_export_blocked(count)",
        )
        if count[0] == 0:
            return []
        output = ffi.new("coord_t[]", count[0])
        raise_for_status(
            C.obstacle_export_blocked(self._c, output, count[0], count),
            "obstacle_export_blocked",
        )
        return [c_coord(output[i].x, output[i].y) for i in range(count[0])]

    def ptr(self):
        return self._c

    def close(self):
        if self._own and self._finalizer and self._finalizer.alive:
            self._finalizer()

    def __del__(self):
        self.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.close()
