from .ffi_core import C, ffi
from .coord import c_coord  # Registers coord_t in the shared FFI.
from .navgrid import c_navgrid  # Registers navgrid_t in the shared FFI.
from .navsys_status import NavsysStatus


ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/route_carver/route_carver.h */
typedef enum e_navgrid_carve_metric {
    NAVGRID_CARVE_CHEBYSHEV_SQUARE = 0,
    NAVGRID_CARVE_MANHATTAN_DIAMOND = 1,
    NAVGRID_CARVE_EUCLIDEAN_DISK = 2
} navgrid_carve_metric_t;

typedef enum e_navgrid_line_coverage {
    NAVGRID_LINE_CENTER_CELLS = 0,
    NAVGRID_LINE_SUPERCOVER_CELLS = 1
} navgrid_line_coverage_t;

typedef enum e_navgrid_carve_match {
    NAVGRID_CARVE_STORED_FORBIDDEN_ONLY = 0,
    NAVGRID_CARVE_EFFECTIVE_BLOCKED = 1
} navgrid_carve_match_t;

typedef bool (*navgrid_carve_cancel_func)(void* userdata);

typedef struct s_navgrid_carve_options {
    uint32_t struct_size;
    uint32_t abi_version;
    uint32_t radius_cells;
    uint32_t metric;
    uint32_t line_coverage;
    uint32_t match;
    uint32_t flags;
    uint32_t reserved0;
    uint64_t max_cells;
    navgrid_carve_cancel_func cancel_func;
    void* cancel_userdata;
} navgrid_carve_options_t;

 navsys_status_t navgrid_carve_line(
    navgrid_t* navgrid,
    const coord_t* start,
    const coord_t* goal,
    const navgrid_carve_options_t* options,
    size_t* out_changed_count);

 navsys_status_t navgrid_carve_area(
    navgrid_t* navgrid,
    const coord_t* center,
    const navgrid_carve_options_t* options,
    size_t* out_changed_count);

 int route_carve_beam(
    navgrid_t* navgrid,
    const coord_t* start,
    const coord_t* goal,
    int range);

 int route_carve_bomb(
    navgrid_t* navgrid,
    const coord_t* center,
    int range);
""")


__all__ = ["C", "NavsysStatus", "c_coord", "c_navgrid", "ffi"]
