from .ffi_core import ffi, C
import weakref

from .coord import c_coord
from .coord_list import c_coord_list
from .coord_hash import c_coord_hash
from .navsys_status import NavsysStatus

from enum import IntEnum

class RouteDir(IntEnum):
    UNKNOWN = 0
    RIGHT = 1
    UP_RIGHT = 2
    UP = 3
    UP_LEFT = 4
    LEFT = 5
    DOWN_LEFT = 6
    DOWN = 7
    DOWN_RIGHT = 8
    COUNT = 9

class RouteCompletion(IntEnum):
    NONE = 0
    COMPLETE = 1
    PARTIAL = 2

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/route/route.h */
typedef enum e_route_dir {
    ROUTE_DIR_UNKNOWN,
    ROUTE_DIR_RIGHT,
    ROUTE_DIR_UP_RIGHT,
    ROUTE_DIR_UP,
    ROUTE_DIR_UP_LEFT,
    ROUTE_DIR_LEFT,
    ROUTE_DIR_DOWN_LEFT,
    ROUTE_DIR_DOWN,
    ROUTE_DIR_DOWN_RIGHT,
    ROUTE_DIR_COUNT
} route_dir_t;

typedef enum e_route_completion {
    ROUTE_COMPLETION_NONE = 0,
    ROUTE_COMPLETION_COMPLETE = 1,
    ROUTE_COMPLETION_PARTIAL = 2
} route_completion_t;

struct s_route {
    coord_list_t* coords;
    coord_list_t* visited_order;
    coord_hash_t* visited_count;
    float cost;
    bool success;
    int total_retry_count;

    float avg_vec_x;
    float avg_vec_y;
    int vec_count;
};

typedef struct s_route route_t;

 route_t* route_create();

 void  route_destroy(route_t* p);

 route_t* route_copy(const route_t* p);
 uintptr_t route_hash(const route_t* a);
 int route_equal(const route_t* a, const route_t* b);

 void  route_set_cost(route_t* p, float cost);
 float route_get_cost(const route_t* p);
 void  route_set_success(route_t* p, int success);
 int   route_get_success(const route_t* p);

 const coord_list_t* route_get_coords(const route_t* p);

 const coord_list_t* route_get_visited_order(const route_t* p);
 const coord_hash_t*  route_get_visited_count(const route_t* p);

 int route_get_total_retry_count(const route_t* p);

 void route_set_total_retry_count(route_t* p, int retry_count);

 int  route_add_coord(route_t* p, const coord_t* c);
 void route_clear_coords(route_t* p);
 const coord_t* route_get_last(const route_t* p);
 const coord_t* route_get_coord_at(const route_t* p, int index);
 int   route_length(const route_t* p);

 size_t route_get_coord_count(const route_t* route);

 navsys_status_t route_fetch_coord(
    const route_t* route,
    size_t index,
    coord_t* out_coord);

 navsys_status_t route_fetch_total_cost(
    const route_t* route,
    double* out_total_cost);

 navsys_status_t route_fetch_completion(
    const route_t* route,
    route_completion_t* out_completion);

 navsys_status_t route_export_coords(
    const route_t* route,
    coord_t* output,
    size_t capacity,
    size_t* out_required_count);

 int  route_add_visited(route_t* p, const coord_t* c);
 void route_clear_visited(route_t* p);

 void route_append(route_t* dest, const route_t* src);

 void route_append_nodup(route_t* dest, const route_t* src);

 void route_insert(route_t* p, int index, const coord_t* c);
 void route_remove_at(route_t* p, int index);
 void route_remove_value(route_t* p, const coord_t* c);
 int  route_contains(const route_t* p, const coord_t* c);
 int  route_find(const route_t* p, const coord_t* c);

 route_t* route_slice(const route_t* p, int start, int end);

 void route_print(const route_t* p);

 coord_t* route_make_direction(route_t* p, int index);
 route_dir_t route_get_direction_by_dir_coord(const coord_t* dxdy);
 route_dir_t route_get_direction_by_index(route_t* p, int index);
 route_dir_t route_calc_average_facing(route_t* p, int history);
 float route_calc_average_dir(route_t* p, int history);

 coord_t* direction_to_coord(route_dir_t route_dir);

 int route_has_changed(
    route_t* p, const coord_t* from,
    const coord_t* to, float angle_threshold_deg);

 int route_has_changed_with_angle(
    route_t* p, const coord_t* from,
    const coord_t* to, float angle_threshold_deg,
    float* out_angle_deg);

 int route_has_changed_by_index(
    route_t* p, int index_from,
    int index_to, float angle_threshold_deg);

 int route_has_changed_with_angle_by_index(
    route_t* p, int index_from, int index_to,
    float angle_threshold_deg, float* out_angle_deg);

 void route_update_average_vector(
    route_t* p, const coord_t* from, const coord_t* to);

 void route_update_average_vector_by_index(
    route_t* p, int index_from, int index_to);

 route_dir_t calc_direction(
    const coord_t* start, const coord_t* goal);

 bool route_reconstruct(
    route_t* route, const coord_hash_t* came_from,
    const coord_t* start, const coord_t* goal);
""")

class c_route:
    def __init__(self, raw_ptr=None, cost=None, own=False):
        self._c = ffi.NULL
        self._own = False
        self._finalizer = None
        if raw_ptr:
            self._c = raw_ptr
            self._own = own
        else:
            self._c = C.route_create()
            self._own = True

        if not self._c:
            raise MemoryError("route allocation failed")

        if self._own:
            self._finalizer = weakref.finalize(self, C.route_destroy, self._c)
        if cost is not None:
            C.route_set_cost(self._c, cost)

    def cost(self):
        return C.route_get_cost(self._c)

    def set_cost(self, cost: float):
        C.route_set_cost(self._c, cost)

    def is_success(self):
        return bool(C.route_get_success(self._c))

    def set_success(self, success: bool):
        C.route_set_success(self._c, int(success))

    def retry_count(self):
        return C.route_get_total_retry_count(self._c)

    def set_retry_count(self, count: int):
        C.route_set_total_retry_count(self._c, count)

    def coords(self):
        return c_coord_list(raw_ptr=C.route_get_coords(self._c), own=False)

    def add_coord(self, coord: c_coord):
        return C.route_add_coord(self._c, coord.ptr())

    def clear_coords(self):
        C.route_clear_coords(self._c)

    def last(self):
        ptr = C.route_get_last(self._c)
        return c_coord(raw_ptr=ptr) if ptr != ffi.NULL else None

    def coord_at(self, index):
        ptr = C.route_get_coord_at(self._c, index)
        return c_coord(raw_ptr=ptr) if ptr != ffi.NULL else None

    def length(self):
        return C.route_length(self._c)

    def coord_count(self):
        return C.route_get_coord_count(self._c)

    def fetch_coord(self, index):
        """Return one coordinate value without borrowing native storage."""
        output = ffi.new("coord_t*")
        status = NavsysStatus(
            C.route_fetch_coord(self._c, index, output)
        )
        if status is NavsysStatus.NOT_FOUND:
            raise IndexError(index)
        if status is not NavsysStatus.OK:
            raise RuntimeError(f"route coordinate fetch failed: {status.name}")
        return output.x, output.y

    def total_cost(self):
        output = ffi.new("double*")
        status = NavsysStatus(
            C.route_fetch_total_cost(self._c, output)
        )
        if status is not NavsysStatus.OK:
            raise RuntimeError(f"route cost fetch failed: {status.name}")
        return output[0]

    def completion(self):
        output = ffi.new("route_completion_t*")
        status = NavsysStatus(
            C.route_fetch_completion(self._c, output)
        )
        if status is not NavsysStatus.OK:
            raise RuntimeError(
                f"route completion fetch failed: {status.name}"
            )
        return RouteCompletion(output[0])

    def export_coords(self):
        """Return a caller-buffer snapshot as ``[(x, y), ...]``."""
        required = ffi.new("size_t*")
        status = NavsysStatus(
            C.route_export_coords(self._c, ffi.NULL, 0, required)
        )
        if status is not NavsysStatus.OK:
            raise RuntimeError(f"route coordinate query failed: {status.name}")
        if required[0] == 0:
            return []

        output = ffi.new("coord_t[]", required[0])
        status = NavsysStatus(
            C.route_export_coords(
                self._c, output, required[0], required
            )
        )
        if status is not NavsysStatus.OK:
            raise RuntimeError(f"route coordinate export failed: {status.name}")
        return [(output[i].x, output[i].y) for i in range(required[0])]

    def visited_order(self):
        return c_coord_list(raw_ptr=C.route_get_visited_order(self._c), own=False)

    def visited_count(self):
        return c_coord_hash(raw_ptr=C.route_get_visited_count(self._c), own=False)

    def add_visited(self, coord: c_coord):
        return C.route_add_visited(self._c, coord.ptr())

    def clear_visited(self):
        C.route_clear_visited(self._c)

    def append(self, other: 'c_route', nodup=False):
        if nodup:
            C.route_append_nodup(self._c, other._c)
        else:
            C.route_append(self._c, other._c)

    def insert(self, index, coord: c_coord):
        C.route_insert(self._c, index, coord.ptr())

    def remove_at(self, index):
        C.route_remove_at(self._c, index)

    def remove_value(self, coord: c_coord):
        C.route_remove_value(self._c, coord.ptr())

    def contains(self, coord: c_coord):
        return bool(C.route_contains(self._c, coord.ptr()))

    def find(self, coord: c_coord):
        return C.route_find(self._c, coord.ptr())

    def slice(self, start, end):
        return c_route(raw_ptr=C.route_slice(self._c, start, end), own=True)

    def look_at(self, index):
        ptr = C.route_make_direction(self._c, index)
        return c_coord(raw_ptr=ptr) if ptr != ffi.NULL else None

    def calc_average_facing(self, history):
        return RouteDir(C.route_calc_average_facing(self._c, history))

    def calc_average_dir(self, history):
        return C.route_calc_average_dir(self._c, history)

    def get_direction_by_index(self, index):
        return RouteDir(C.route_get_direction_by_index(self._c, index))

    def has_changed(self, from_coord, to_coord, angle_threshold):
        return bool(C.route_has_changed(self._c, from_coord.ptr(), to_coord.ptr(), angle_threshold))

    def has_changed_with_angle(self, from_coord, to_coord, angle_threshold):
        out = ffi.new("float*")
        changed = C.route_has_changed_with_angle(self._c, from_coord.ptr(), to_coord.ptr(), angle_threshold, out)
        return bool(changed), out[0]

    def has_changed_by_index(self, index_from, index_to, angle_threshold):
        return bool(C.route_has_changed_by_index(self._c, index_from, index_to, angle_threshold))

    def has_changed_with_angle_by_index(self, index_from, index_to, angle_threshold):
        out = ffi.new("float*")
        changed = C.route_has_changed_with_angle_by_index(self._c, index_from, index_to, angle_threshold, out)
        return bool(changed), out[0]

    def update_average_vector(self, from_coord, to_coord):
        C.route_update_average_vector(self._c, from_coord.ptr(), to_coord.ptr())

    def update_average_vector_by_index(self, index_from, index_to):
        C.route_update_average_vector_by_index(self._c, index_from, index_to)

    def reconstruct_path(self, came_from: c_coord_hash, start: c_coord, goal: c_coord):
        return bool(C.route_reconstruct_path(self._c, came_from.ptr(), start.ptr(), goal.ptr()))

    def print(self):
        C.route_print(self._c)

    def ptr(self):
        return self._c

    def __repr__(self):
        return f"c_route(len={self.length()}, cost={self.cost():.2f}, success={self.is_success()})"

    def __del__(self):
        self.close()

    def close(self):
        if getattr(self, "_own", False) and self._finalizer and self._finalizer.alive:
            self._finalizer()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()

    def __len__(self):
        return self.length()

    def to_string(self):
        coords = self.coords()
        parts = []
        for c in coords:
            parts.append(f"({c.x}, {c.y})")
        return f"Route(len : {len(parts)}): " + " -> ".join(parts)

    @staticmethod
    def direction_to_coord(direction: RouteDir) -> c_coord:
        ptr = C.direction_to_coord(direction)
        return c_coord(raw_ptr=ptr) if ptr != ffi.NULL else None

    @staticmethod
    def calc_direction(start: c_coord, goal: c_coord) -> RouteDir:
        return RouteDir(C.calc_direction(start.ptr(), goal.ptr()))

    @staticmethod
    def get_direction_by_dir_coord(dxdy: c_coord):
        return RouteDir(C.route_get_direction_by_dir_coord(dxdy.ptr()))
