from .ffi_core import ffi, C

from .coord import c_coord
from .coord_list import c_coord_list
from .coord_hash import c_coord_hash
from .cost_coord_pq import c_cost_coord_pq

from .route import c_route
from .navgrid import c_navgrid
from .route_finder_common import g_RouteFuncReg
from .navsys_status import NavsysStatus

from dataclasses import dataclass
import weakref

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/route_finder/route_finder.h */
typedef enum e_route_finder_type{
    ROUTE_FINDER_UNKNOWN = 0,

    ROUTE_FINDER_BELLMAN_FORD,
    ROUTE_FINDER_DFS,
    ROUTE_FINDER_BFS,
    ROUTE_FINDER_DIJKSTRA,
    ROUTE_FINDER_FLOYD_WARSHALL,
    ROUTE_FINDER_ASTAR,

    ROUTE_FINDER_BIDIRECTIONAL_DIJKSTRA,
    ROUTE_FINDER_BIDIRECTIONAL_ASTAR,
    ROUTE_FINDER_WEIGHTED_ASTAR,
    ROUTE_FINDER_JOHNSON,
    ROUTE_FINDER_K_SHORTEST_PATH,
    ROUTE_FINDER_DIAL,

    ROUTE_FINDER_ITERATIVE_DEEPENING,
    ROUTE_FINDER_GREEDY_BEST_FIRST,
    ROUTE_FINDER_IDA_STAR,

    ROUTE_FINDER_RTA_STAR,
    ROUTE_FINDER_SMA_STAR,
    ROUTE_FINDER_DSTAR,
    ROUTE_FINDER_FAST_MARCHING,
    ROUTE_FINDER_ANT_COLONY,
    ROUTE_FINDER_FRINGE_SEARCH,

    ROUTE_FINDER_FOCAL_SEARCH,
    ROUTE_FINDER_DSTAR_LITE,
    ROUTE_FINDER_LPA_STAR,
    ROUTE_FINDER_HPA_STAR,
    ROUTE_FINDER_ALT,
    ROUTE_FINDER_ANY_ANGLE_ASTAR,
    ROUTE_FINDER_HCA_STAR,
    ROUTE_FINDER_RTAA_STAR,
    ROUTE_FINDER_THETA_STAR,
    ROUTE_FINDER_CONTRACTION_HIERARCHIES,

    ROUTE_FINDER_LAZY_THETA_STAR,
    ROUTE_FINDER_JUMP_POINT_SEARCH,
    ROUTE_FINDER_SIPP,
    ROUTE_FINDER_JPS_PLUS,
    ROUTE_FINDER_EPEA_STAR,
    ROUTE_FINDER_MHA_STAR,
    ROUTE_FINDER_ANYA,

    ROUTE_FINDER_DAG_SP,
    ROUTE_FINDER_MULTI_SOURCE_BFS,
    ROUTE_FINDER_MCTS
} route_finder_type_t;

typedef struct s_route_finder_fringe_search_config {
    float delta_epsilon;
} route_finder_fringe_search_config_t;

typedef struct s_route_finder_rta_star_config {
    int depth_limit;
} route_finder_rta_star_config_t;

typedef struct s_route_finder_sma_star_config {
    int memory_limit;
} route_finder_sma_star_config_t;

typedef struct s_route_finder_weighted_astar_config {
    float weight;
} route_finder_weighted_astar_config_t;

typedef struct s_route_finder_run_stats {
    int total_retry_count;
    int route_length;
    float route_cost;
    bool complete;
    bool partial;
} route_finder_run_stats_t;

 const char* get_route_finder_name(route_finder_type_t pa);

 bool route_finder_is_supported(route_finder_type_t type);

typedef struct s_route_finder {
    navgrid_t* navgrid;
    coord_t start;
    coord_t goal;

    route_finder_type_t type;
    void* typedata;

    int max_retry;
    bool debug_mode_enabled;

    cost_func cost_fn;
    void* cost_fn_userdata;

    heuristic_func heuristic_fn;
    void* heuristic_fn_userdata;
} route_finder_t;

 route_finder_t* route_finder_create(navgrid_t* navgrid);

 route_finder_t* route_finder_create_full(
    navgrid_t* navgrid,
    const coord_t* start,
    const coord_t* goal,

    route_finder_type_t type,
    void* typedata,

    int max_retry,
    bool debug_mode_enabled,

    cost_func cost_fn,
    void* cost_fn_userdata,

    heuristic_func heuristic_fn,
    void* heuristic_fn_userdata
);

 int route_finder_init(route_finder_t* out, navgrid_t* navgrid);

 int route_finder_init_full(
    route_finder_t* out,
    navgrid_t* navgrid,
    const coord_t* start,
    const coord_t* goal,
    route_finder_type_t type,
    void* typedata,
    int max_retry,
    bool debug_mode_enabled,

    cost_func cost_fn,
    void* cost_fn_userdata,

    heuristic_func heuristic_fn,
    void* heuristic_fn_userdata
);

 int route_finder_free(route_finder_t* out);

 int route_finder_destroy(route_finder_t* a);

 route_finder_t* route_finder_copy(const route_finder_t* src);

 void route_finder_set_navgrid(route_finder_t* a, navgrid_t* navgrid);
 void route_finder_set_start(route_finder_t* a, const coord_t* start);
 void route_finder_set_goal(route_finder_t* a, const coord_t* goal);

 const navgrid_t* route_finder_get_navgrid(const route_finder_t* a);
 int route_finder_fetch_start(const route_finder_t* a, coord_t* out);
 int route_finder_fetch_goal(const route_finder_t* a, coord_t* out);

 void route_finder_set_type(
    route_finder_t* a, route_finder_type_t type);

 route_finder_type_t route_finder_get_type(const route_finder_t* a);

 navsys_status_t route_finder_set_type_checked(
    route_finder_t* finder, route_finder_type_t type);

 void route_finder_set_typedata(
    route_finder_t* a, void* typedata);

 void* route_finder_get_typedata(const route_finder_t* a);

 navsys_status_t route_finder_bind_fringe_search_config(
    route_finder_t* finder,
    const route_finder_fringe_search_config_t* config);

 navsys_status_t route_finder_bind_rta_star_config(
    route_finder_t* finder,
    const route_finder_rta_star_config_t* config);

 navsys_status_t route_finder_bind_sma_star_config(
    route_finder_t* finder,
    const route_finder_sma_star_config_t* config);

 navsys_status_t route_finder_bind_weighted_astar_config(
    route_finder_t* finder,
    const route_finder_weighted_astar_config_t* config);

 navsys_status_t route_finder_unbind_algorithm_config(
    route_finder_t* finder);

 void route_finder_set_max_retry(route_finder_t* a, int max_retry);
 int route_finder_get_max_retry(route_finder_t* a);

 navsys_status_t route_finder_set_max_retry_checked(
    route_finder_t* finder, int max_retry);

 void route_finder_enable_debug_mode(
    route_finder_t* a, bool is_logging);

 bool route_finder_is_debug_mode_enabled(route_finder_t* a);

 void route_finder_set_cost_func(
    route_finder_t* a, cost_func cost_fn);

 cost_func route_finder_get_cost_func(route_finder_t* a);

 void route_finder_set_cost_fn_userdata(
    route_finder_t* a, void* cost_fn_userdata);

 void* route_finder_get_cost_fn_userdata(const route_finder_t* a);

 void route_finder_set_heuristic_func(
    route_finder_t* a, heuristic_func heuristic_fn);

 heuristic_func route_finder_get_heuristic_func(route_finder_t* a);

 void route_finder_set_heuristic_fn_userdata(
    route_finder_t* a, void* heuristic_fn_userdata);

 void* route_finder_get_heuristic_fn_userdata(
    const route_finder_t* a);

 navsys_status_t route_finder_bind_cost_func(
    route_finder_t* finder, cost_func fn, void* userdata);

 navsys_status_t route_finder_unbind_cost_func(
    route_finder_t* finder);

 navsys_status_t route_finder_bind_heuristic_func(
    route_finder_t* finder, heuristic_func fn, void* userdata);

 navsys_status_t route_finder_unbind_heuristic_func(
    route_finder_t* finder);

 void route_finder_clear(route_finder_t* a);

 void route_finder_set_defaults(route_finder_t* a);

 bool route_finder_is_valid(const route_finder_t* a);
 void route_finder_print(const route_finder_t* a);

 route_t* route_finder_run(route_finder_t* a);

 navsys_status_t route_finder_run_ex(
    route_finder_t* finder,
    route_t** out_route,
    route_finder_run_stats_t* out_stats);

/* Source: byul/navsys/route_finder/astar.h */
route_t* find_astar(const navgrid_t* m, const coord_t* start, const coord_t* goal,
    cost_func cost_fn, heuristic_func heuristic_fn,
    int max_retry, bool debug_mode_enabled);

/* Source: byul/navsys/route_finder/bfs.h */
route_t* find_bfs(const navgrid_t* m,
    const coord_t* start, const coord_t* goal,
    int max_retry, bool debug_mode_enabled);

/* Source: byul/navsys/route_finder/dfs.h */
route_t* find_dfs(const navgrid_t* m,
    const coord_t* start, const coord_t* goal,
    int max_retry, bool debug_mode_enabled);

/* Source: byul/navsys/route_finder/dijkstra.h */
route_t* find_dijkstra(const navgrid_t* m,
    const coord_t* start, const coord_t* goal, cost_func cost_fn,
    int max_retry, bool debug_mode_enabled);

/* Source: byul/navsys/route_finder/fast_marching.h */
typedef enum e_fmm_state {
    FMM_FAR = 0,
    FMM_NARROW,
    FMM_KNOWN
} fmm_state_t;

typedef struct s_fmm_cell {
    fmm_state_t state;
    float value;
} fmm_cell_t;

 void fmm_cell_init(fmm_cell_t* out);

 void fmm_cell_init_full(
    fmm_cell_t* out, fmm_state_t state, float value);

 void fmm_cell_assign(fmm_cell_t* out, const fmm_cell_t* src);

void* fmm_cell_copy(const void* p);

void fmm_cell_destroy(void* p);

typedef struct s_fmm_grid{
    int width;
    int height;
    coord_hash_t* cells;
    coord_list_t* visit_order;
    int total_retry_count;
} fmm_grid_t;

 fmm_grid_t* fmm_grid_create_full(const navgrid_t* m, const coord_t* start,
    cost_func cost_fn, float radius_limit, int max_retry);

 void fmm_grid_destroy(fmm_grid_t* grid);

 void fmm_dump_ascii(const fmm_grid_t* grid);

 route_t* find_fast_marching(const navgrid_t* m,
    const coord_t* start, const coord_t* goal,
    cost_func cost_fn, int max_retry, bool debug_mode_enabled);

/* Source: byul/navsys/route_finder/fringe_search.h */
route_t* find_fringe_search(const navgrid_t* m,
    const coord_t* start, const coord_t* goal,
    cost_func cost_fn, heuristic_func heuristic_fn, float delta_epsilon,
    int max_retry, bool debug_mode_enabled);

/* Source: byul/navsys/route_finder/greedy_best_first.h */
route_t* find_greedy_best_first(const navgrid_t* m,
    const coord_t* start, const coord_t* goal,
    heuristic_func heuristic_fn,
    int max_retry, bool debug_mode_enabled);

/* Source: byul/navsys/route_finder/ida_star.h */
route_t* find_ida_star(const navgrid_t* m,
    const coord_t* start, const coord_t* goal,
    cost_func cost_fn, heuristic_func heuristic_fn,
    int max_retry, bool debug_mode_enabled);

/* Source: byul/navsys/route_finder/rta_star.h */
typedef struct s_rta_star_config{
    int depth_limit;
} rta_star_config_t;
typedef rta_star_config_t* rta_star_config;

 rta_star_config rta_star_config_create();

 rta_star_config rta_star_config_create_full(int depth_limit);

 void rta_star_config_destroy(rta_star_config cfg);

 route_t* find_rta_star(const navgrid_t* m,
    const coord_t* start, const coord_t* goal,
    cost_func cost_fn, heuristic_func heuristic_fn,
    int depth_limit,
    int max_retry, bool debug_mode_enabled);

/* Source: byul/navsys/route_finder/sma_star.h */
route_t* find_sma_star(const navgrid_t* m,
    const coord_t* start, const coord_t* goal,
    cost_func cost_fn, heuristic_func heuristic_fn,
    int memory_limit,
    int max_retry, bool debug_mode_enabled);

/* Source: byul/navsys/route_finder/weighted_astar.h */
route_t* find_weighted_astar(const navgrid_t* m,
    const coord_t* start, const coord_t* goal,
    cost_func cost_fn, heuristic_func heuristic_fn,
    float weight,
    int max_retry, bool debug_mode_enabled);
""")

MAX_RETRY = 1000

from enum import IntEnum

class RouteFinderType(IntEnum):
    UNKNOWN = 0

    # // 1950s~1960s
    BELLMAN_FORD = 1 #            // 1958
    DFS = 2 #                     // 1959
    BFS = 3 #                     // 1959
    DIJKSTRA = 4 #                // 1959
    FLOYD_WARSHALL = 5 #          // 1959~
    ASTAR = 6 #                   // 1968

    # // 1970s
    BIDIRECTIONAL_DIJKSTRA = 7 # ,  // 1971
    BIDIRECTIONAL_ASTAR =8 #,     // 1971
    WEIGHTED_ASTAR = 9 #,          // 1977~
    JOHNSON = 10 #,                 // 1977
    K_SHORTEST_PATH = 11 #,         // 1977~
    DIAL = 12 #,                    // 1969

    # // 1980s
    ITERATIVE_DEEPENING = 13 #,     // 1980
    GREEDY_BEST_FIRST = 14 #,       // 1985
    IDA_STAR = 15 #,                // 1985

    # // 1990s
    RTA_STAR = 16 #,                // 1990
    SMA_STAR = 17 #,                // 1991
    DSTAR = 18 #,                   // 1994
    FAST_MARCHING = 19 #,           // 1996
    ANT_COLONY = 20 #,              // 1996
    FRINGE_SEARCH = 21 #,           // 1997

    # // 2000s
    FOCAL_SEARCH = 22 #,            // 2001
    DSTAR_LITE = 23 #,              // 2002
    LPA_STAR = 24 #,                // 2004
    HPA_STAR = 25 #,                // 2004
    ALT = 26 #,                     // 2005
    ANY_ANGLE_ASTAR = 27 #,         // 2005~
    HCA_STAR = 28 #,                // 2005
    RTAA_STAR = 29 #,               // 2006
    THETA_STAR = 30 #,              // 2007
    CONTRACTION_HIERARCHIES = 31 # ,// 2008

    # // 2010s
    LAZY_THETA_STAR = 32 #,         // 2010
    JUMP_POINT_SEARCH = 33 #,       // 2011
    SIPP = 34 #,                    // 2011
    JPS_PLUS = 35 #,                // 2012
    EPEA_STAR = 36 #,               // 2012
    MHA_STAR = 37 #              // 2012
    ANYA = 38 #,                    // 2013

    # // 특수 목적 / 확장형
    DAG_SP = 39 #,                  // 1960s (DAG 최단경로 O(V+E))
    MULTI_SOURCE_BFS =40 #,        // 2000s (복수 시작점 BFS)
    MCTS =41 #                     // 2006


@dataclass(frozen=True)
class RouteFinderRunStats:
    total_retry_count: int
    route_length: int
    route_cost: float
    complete: bool
    partial: bool


class c_route_finder:
    def __init__(self,
                 navgrid: c_navgrid,
                 start: c_coord = None,
                 goal: c_coord = None,
                 type: RouteFinderType = RouteFinderType.ASTAR,
                 typedata=None,
                 cost_fn=None,
                 cost_userdata=None,
                 heuristic_fn=None,
                 heuristic_userdata=None,
                 max_retry: int = MAX_RETRY,
                 debug=False,
                 raw_ptr=None, own=False):

        self._algorithm_config = None
        self._typedata_handle = (
            None if typedata is None else ffi.new_handle(typedata)
        )

        if raw_ptr:
            self._c = raw_ptr
            self._own = own
        else:
            if navgrid is None:
                raise ValueError("navgrid (navgrid) must be provided")

            if not start:
                start = c_coord(0, 0)
            if not goal:
                goal = c_coord(0, 0)

            if not cost_fn:
                cost_fn = C.default_cost
            if not heuristic_fn:
                heuristic_fn = C.euclidean_heuristic

            self._c = C.route_finder_create_full(
                navgrid.ptr(),
                start.ptr(),
                goal.ptr(),
                type,
                ffi.NULL if self._typedata_handle is None
                else self._typedata_handle,
                max_retry,
                debug,
                cost_fn,
                ffi.NULL if cost_userdata is None else ffi.new_handle(cost_userdata),
                heuristic_fn,
                ffi.NULL if heuristic_userdata is None else ffi.new_handle(heuristic_userdata)
            )
            self._own = True

        if not self._c:
            raise MemoryError("route_finder allocation failed")

        if self._own:
            self._finalizer = weakref.finalize(
                self, C.route_finder_destroy, self._c)
        else:
            self._finalizer = None

        self.type = type


    def ptr(self):
        return self._c

    def find(self):
        result = C.route_finder_run(self._c)
        if result != ffi.NULL:
            return c_route(raw_ptr=result, own=True)
        return None

    def find_ex(self):
        out_route = ffi.new("route_t**")
        out_stats = ffi.new("route_finder_run_stats_t*")
        status = NavsysStatus(
            C.route_finder_run_ex(self._c, out_route, out_stats)
        )
        if out_route[0] == ffi.NULL:
            return status, None, None
        stats = RouteFinderRunStats(
            total_retry_count=out_stats.total_retry_count,
            route_length=out_stats.route_length,
            route_cost=out_stats.route_cost,
            complete=bool(out_stats.complete),
            partial=bool(out_stats.partial),
        )
        return status, c_route(raw_ptr=out_route[0], own=True), stats

    def set_type(self, type: RouteFinderType):
        status = C.route_finder_set_type_checked(self._c, type)
        if status != C.NAVSYS_STATUS_OK:
            raise ValueError(f"unsupported route finder type ({status})")

    def get_type(self):
        return RouteFinderType(C.route_finder_get_type(self._c))

    def _bind_algorithm_config(self, c_type, field, value, bind):
        config = ffi.new(c_type)
        setattr(config, field, value)
        status = bind(self._c, config)
        if status != C.NAVSYS_STATUS_OK:
            raise ValueError(f"invalid route finder configuration ({status})")
        self._algorithm_config = config

    def bind_fringe_search_config(self, delta_epsilon: float):
        self._bind_algorithm_config(
            "route_finder_fringe_search_config_t*",
            "delta_epsilon",
            delta_epsilon,
            C.route_finder_bind_fringe_search_config,
        )

    def bind_rta_star_config(self, depth_limit: int):
        self._bind_algorithm_config(
            "route_finder_rta_star_config_t*",
            "depth_limit",
            depth_limit,
            C.route_finder_bind_rta_star_config,
        )

    def bind_sma_star_config(self, memory_limit: int):
        self._bind_algorithm_config(
            "route_finder_sma_star_config_t*",
            "memory_limit",
            memory_limit,
            C.route_finder_bind_sma_star_config,
        )

    def bind_weighted_astar_config(self, weight: float):
        self._bind_algorithm_config(
            "route_finder_weighted_astar_config_t*",
            "weight",
            weight,
            C.route_finder_bind_weighted_astar_config,
        )

    def unbind_algorithm_config(self):
        status = C.route_finder_unbind_algorithm_config(self._c)
        if status != C.NAVSYS_STATUS_OK:
            raise RuntimeError(
                f"could not unbind route finder configuration ({status})"
            )
        self._algorithm_config = None

    def set_max_retry(self, max_retry: int):
        status = C.route_finder_set_max_retry_checked(
            self._c, max_retry
        )
        if status != C.NAVSYS_STATUS_OK:
            raise ValueError(f"invalid max_retry ({status})")

    def get_max_retry(self):
        return C.route_finder_get_max_retry(self._c)

    def enable_debug(self, is_logging: bool):
        C.route_finder_enable_debug_mode(self._c, is_logging)

    def is_debug_enabled(self):
        return C.route_finder_is_debug_mode_enabled(self._c)

    def set_cost_func(self, name: str):
        fn = g_RouteFuncReg.get_cost_func(name)
        C.route_finder_set_cost_func(self._c, fn)

    def set_heuristic_func(self, name: str):
        fn = g_RouteFuncReg.get_heuristic_func(name)
        C.route_finder_set_heuristic_func(self._c, fn)

    def set_start(self, coord: c_coord):
        C.route_finder_set_start(self._c, coord._c)

    def set_goal(self, coord: c_coord):
        C.route_finder_set_goal(self._c, coord._c)

    def set_userdata(self, obj):
        C.route_finder_set_userdata(self._c, ffi.new_handle(obj))

    def get_start(self):
        out = ffi.new("coord_t*")
        C.route_finder_fetch_start(self._c, out)
        return c_coord(raw_ptr=out)

    def get_goal(self):
        out = ffi.new("coord_t*")
        C.route_finder_fetch_goal(self._c, out)
        return c_coord(raw_ptr=out)

    def get_navgrid(self):
        return c_navgrid(raw_ptr=C.route_finder_get_navgrid(self._c))

    def is_valid(self):
        return bool(C.route_finder_is_valid(self._c))

    def clear(self):
        C.route_finder_clear(self._c)
        self._algorithm_config = None
        self._typedata_handle = None

    def print(self):
        C.route_finder_print(self._c)

    def name(self):
        name_ptr = C.get_route_finder_name(self.get_type())
        return ffi.string(name_ptr).decode("utf-8") if name_ptr != ffi.NULL else "UNKNOWN"

    def __del__(self):
        self.close()

    def close(self):
        if self._own and self._finalizer and self._finalizer.alive:
            self._finalizer()
        self._algorithm_config = None
        self._typedata_handle = None

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()

    @staticmethod
    def list_route_finders():
        return list(RouteFinderType)

    @staticmethod
    def is_supported(type: RouteFinderType):
        return bool(C.route_finder_is_supported(type))

    @staticmethod
    def list_supported_route_finders():
        return [
            type for type in RouteFinderType
            if c_route_finder.is_supported(type)
        ]

    @staticmethod
    def find_by_name(name: str):
        for a in RouteFinderType:
            if ffi.string(C.get_route_finder_name(a)).decode("utf-8").lower() == name.lower():
                return a
        return RouteFinderType.UNKNOWN
