from .ffi_core import ffi, C
import weakref

from .coord import c_coord
from .coord_list import c_coord_list
from .coord_hash import c_coord_hash
from .navsys_status import NavsysStatus, raise_for_status

from enum import IntEnum

class RouteDir(IntEnum):
    UNKNOWN = 0
    RIGHT = 1
    UP_RIGHT = 2
    UP = 3
    UP_LEFT = 4
    LEFT = 5
    DOWN_LEFT = 6
    DOWN = 7
    DOWN_RIGHT = 8
    COUNT = 9

class RouteCompletion(IntEnum):
    NONE = 0
    COMPLETE = 1
    PARTIAL = 2

class RouteJoinPolicy(IntEnum):
    KEEP_ALL = 0
    DEDUP_BOUNDARY = 1

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/route/route.h */
typedef enum e_route_dir {
    ROUTE_DIR_UNKNOWN = 0,
    ROUTE_DIR_RIGHT = 1,
    ROUTE_DIR_UP_RIGHT = 2,
    ROUTE_DIR_UP = 3,
    ROUTE_DIR_UP_LEFT = 4,
    ROUTE_DIR_LEFT = 5,
    ROUTE_DIR_DOWN_LEFT = 6,
    ROUTE_DIR_DOWN = 7,
    ROUTE_DIR_DOWN_RIGHT = 8,
    ROUTE_DIR_COUNT = 9
} route_dir_t;

typedef enum e_route_completion {
    ROUTE_COMPLETION_NONE = 0,
    ROUTE_COMPLETION_COMPLETE = 1,
    ROUTE_COMPLETION_PARTIAL = 2
} route_completion_t;

typedef enum e_route_join_policy {
    ROUTE_JOIN_KEEP_ALL = 0,
    ROUTE_JOIN_DEDUP_BOUNDARY = 1
} route_join_policy_t;

struct s_route {
    coord_list_t* coords;
    coord_list_t* visited_order;
    coord_hash_t* visited_count;
    float cost;
    bool success;
    int total_retry_count;

    float avg_vec_x;
    float avg_vec_y;
    int vec_count;
};

typedef struct s_route route_t;
typedef struct s_route_builder route_builder_t;
typedef struct s_route_heading_tracker route_heading_tracker_t;
typedef struct s_navsys_search_trace navsys_search_trace_t;

 route_t* route_create(void);

 void  route_destroy(route_t* p);

 route_t* route_copy(const route_t* p);

 navsys_status_t route_clone_ex(
    const route_t* source,
    route_t** out_route);

 uintptr_t route_identity_hash(const route_t* route);

 int route_is_same(const route_t* left, const route_t* right);

 navsys_status_t route_content_equal(
    const route_t* left,
    const route_t* right,
    bool* out_equal);

 navsys_status_t route_fetch_content_hash(
    const route_t* route,
    uint64_t* out_hash);

 uintptr_t route_hash(const route_t* a);

 int route_equal(const route_t* a, const route_t* b);

 void  route_set_cost(route_t* p, float cost);
 float route_get_cost(const route_t* p);

 void  route_set_success(route_t* p, int success);
 int   route_get_success(const route_t* p);

 const coord_list_t* route_get_coords(const route_t* p);

 const coord_list_t* route_get_visited_order(const route_t* p);

 const coord_hash_t*  route_get_visited_count(const route_t* p);

 int route_get_total_retry_count(const route_t* p);

 void route_set_total_retry_count(route_t* p, int retry_count);

 int  route_add_coord(route_t* p, const coord_t* c);

 void route_clear_coords(route_t* p);

 const coord_t* route_get_last(const route_t* p);

 const coord_t* route_get_coord_at(const route_t* p, int index);
 int   route_length(const route_t* p);

 size_t route_get_coord_count(const route_t* route);

 navsys_status_t route_fetch_coord(
    const route_t* route,
    size_t index,
    coord_t* out_coord);

 navsys_status_t route_find_coord(
    const route_t* route,
    const coord_t* coord,
    size_t* out_index);

 navsys_status_t route_fetch_total_cost(
    const route_t* route,
    double* out_total_cost);

 navsys_status_t route_fetch_completion(
    const route_t* route,
    route_completion_t* out_completion);

 navsys_status_t route_export_coords(
    const route_t* route,
    coord_t* output,
    size_t capacity,
    size_t* out_required_count);

 navsys_status_t route_builder_create(route_builder_t** out_builder);

 navsys_status_t route_builder_create_from_route(
    const route_t* source,
    route_builder_t** out_builder);

 void route_builder_destroy(route_builder_t* builder);

 navsys_status_t route_builder_push_coord(
    route_builder_t* builder,
    const coord_t* coord);

 navsys_status_t route_builder_insert_coord(
    route_builder_t* builder,
    size_t index,
    const coord_t* coord);

 navsys_status_t route_builder_remove_coord(
    route_builder_t* builder,
    size_t index,
    coord_t* out_removed);

 navsys_status_t route_builder_append(
    route_builder_t* builder,
    const route_t* source,
    route_join_policy_t join_policy);

 navsys_status_t route_builder_assign_slice(
    route_builder_t* builder,
    const route_t* source,
    size_t begin,
    size_t end);

 navsys_status_t route_builder_set_total_cost(
    route_builder_t* builder,
    double total_cost);

 navsys_status_t route_builder_set_completion(
    route_builder_t* builder,
    route_completion_t completion);

 navsys_status_t route_builder_finish(
    route_builder_t* builder,
    route_t** out_route);

 navsys_status_t navsys_search_trace_create(
    navsys_search_trace_t** out_trace);

 void navsys_search_trace_destroy(navsys_search_trace_t* trace);

 navsys_status_t navsys_search_trace_clone_ex(
    const navsys_search_trace_t* source,
    navsys_search_trace_t** out_trace);

 size_t navsys_search_trace_get_visit_count(
    const navsys_search_trace_t* trace);

 navsys_status_t navsys_search_trace_fetch_visit(
    const navsys_search_trace_t* trace,
    size_t index,
    coord_t* out_coord);

 navsys_status_t navsys_search_trace_fetch_coord_visit_count(
    const navsys_search_trace_t* trace,
    const coord_t* coord,
    size_t* out_count);

 navsys_status_t navsys_search_trace_export_visits(
    const navsys_search_trace_t* trace,
    coord_t* output,
    size_t capacity,
    size_t* out_required_count);

 int  route_add_visited(route_t* p, const coord_t* c);
 void route_clear_visited(route_t* p);

 void route_append(route_t* dest, const route_t* src);

 void route_append_nodup(route_t* dest, const route_t* src);

 void route_insert(route_t* p, int index, const coord_t* c);

 void route_remove_at(route_t* p, int index);

 void route_remove_value(route_t* p, const coord_t* c);
 int  route_contains(const route_t* p, const coord_t* c);

 int  route_find(const route_t* p, const coord_t* c);

 route_t* route_slice(const route_t* p, int start, int end);

 navsys_status_t route_slice_ex(
    const route_t* source,
    size_t begin,
    size_t end,
    route_t** out_route);

 navsys_status_t route_format(
    const route_t* route,
    char* output,
    size_t capacity,
    size_t* out_required_size);

 void route_print(const route_t* p);

 navsys_status_t route_direction_between(
    const coord_t* from,
    const coord_t* to,
    route_dir_t* out_direction);

 navsys_status_t route_direction_from_vector(
    const coord_t* vector,
    route_dir_t* out_direction);

 navsys_status_t route_direction_fetch_vector(
    route_dir_t direction,
    coord_t* out_vector);

 navsys_status_t route_fetch_direction_at(
    const route_t* route,
    size_t index,
    route_dir_t* out_direction);

 navsys_status_t route_compute_recent_facing(
    const route_t* route,
    size_t history,
    route_dir_t* out_direction);

 navsys_status_t route_compute_recent_heading_degrees(
    const route_t* route,
    size_t history,
    double* out_heading_degrees);

 navsys_status_t route_heading_tracker_create(
    route_heading_tracker_t** out_tracker);

 void route_heading_tracker_destroy(
    route_heading_tracker_t* tracker);

 navsys_status_t route_heading_tracker_reset(
    route_heading_tracker_t* tracker);

 size_t route_heading_tracker_get_sample_count(
    const route_heading_tracker_t* tracker);

 navsys_status_t route_heading_tracker_fetch_heading_degrees(
    const route_heading_tracker_t* tracker,
    double* out_heading_degrees);

 navsys_status_t route_heading_tracker_observe_vector(
    route_heading_tracker_t* tracker,
    const coord_t* vector,
    double threshold_degrees,
    double* out_angle_degrees,
    bool* out_changed);

 navsys_status_t route_heading_tracker_observe(
    route_heading_tracker_t* tracker,
    const coord_t* from,
    const coord_t* to,
    double threshold_degrees,
    double* out_angle_degrees,
    bool* out_changed);

 coord_t* route_make_direction(route_t* p, int index);

 route_dir_t route_get_direction_by_dir_coord(const coord_t* dxdy);

 route_dir_t route_get_direction_by_index(route_t* p, int index);

 route_dir_t route_calc_average_facing(route_t* p, int history);

 float route_calc_average_dir(route_t* p, int history);

 coord_t* direction_to_coord(route_dir_t route_dir);

 int route_has_changed(
    route_t* p, const coord_t* from,
    const coord_t* to, float angle_threshold_deg);

 int route_has_changed_with_angle(
    route_t* p, const coord_t* from,
    const coord_t* to, float angle_threshold_deg,
    float* out_angle_deg);

 int route_has_changed_by_index(
    route_t* p, int index_from,
    int index_to, float angle_threshold_deg);

 int route_has_changed_with_angle_by_index(
    route_t* p, int index_from, int index_to,
    float angle_threshold_deg, float* out_angle_deg);

 void route_update_average_vector(
    route_t* p, const coord_t* from, const coord_t* to);

 void route_update_average_vector_by_index(
    route_t* p, int index_from, int index_to);

 route_dir_t calc_direction(
    const coord_t* start, const coord_t* goal);

 bool route_reconstruct(
    route_t* route, const coord_hash_t* came_from,
    const coord_t* start, const coord_t* goal);

 navsys_status_t route_reconstruct_ex(
    route_t* route,
    const coord_hash_t* came_from,
    const coord_t* start,
    const coord_t* goal);
""")

class c_route:
    def __init__(self, raw_ptr=None, cost=None, own=False):
        self._c = ffi.NULL
        self._own = False
        self._finalizer = None
        if raw_ptr:
            self._c = raw_ptr
            self._own = own
        else:
            self._c = C.route_create()
            self._own = True

        if not self._c:
            raise MemoryError("route allocation failed")

        if self._own:
            self._finalizer = weakref.finalize(self, C.route_destroy, self._c)
        if cost is not None:
            C.route_set_cost(self._c, cost)

    def _require_open(self):
        if self._c == ffi.NULL:
            raise ReferenceError("c_route is closed")
        return self._c

    def cost(self):
        return C.route_get_cost(self._c)

    def set_cost(self, cost: float):
        C.route_set_cost(self._c, cost)

    def is_success(self):
        return bool(C.route_get_success(self._c))

    def set_success(self, success: bool):
        C.route_set_success(self._c, int(success))

    def retry_count(self):
        return C.route_get_total_retry_count(self._c)

    def set_retry_count(self, count: int):
        C.route_set_total_retry_count(self._c, count)

    def coords(self):
        return c_coord_list(
            raw_ptr=C.route_get_coords(self._require_open()),
            own=False,
            parent=self,
        )

    def add_coord(self, coord: c_coord):
        return C.route_add_coord(self._c, coord.ptr())

    def clear_coords(self):
        C.route_clear_coords(self._c)

    def last(self):
        count = self.coord_count()
        if count == 0:
            return None
        x, y = self.fetch_coord(count - 1)
        return c_coord(x, y)

    def coord_at(self, index):
        if index < 0 or index >= self.coord_count():
            return None
        x, y = self.fetch_coord(index)
        return c_coord(x, y)

    def length(self):
        return self.coord_count()

    def coord_count(self):
        return C.route_get_coord_count(self._c)

    def fetch_coord(self, index):
        """Return one coordinate value without borrowing native storage."""
        output = ffi.new("coord_t*")
        status = NavsysStatus(
            C.route_fetch_coord(self._c, index, output)
        )
        if status is NavsysStatus.NOT_FOUND:
            raise IndexError(index)
        if status is not NavsysStatus.OK:
            raise RuntimeError(f"route coordinate fetch failed: {status.name}")
        return output.x, output.y

    def total_cost(self):
        output = ffi.new("double*")
        status = NavsysStatus(
            C.route_fetch_total_cost(self._c, output)
        )
        if status is not NavsysStatus.OK:
            raise RuntimeError(f"route cost fetch failed: {status.name}")
        return output[0]

    def identity_hash(self):
        """Return the process-local native handle identity hash."""
        return int(C.route_identity_hash(self._require_open()))

    def is_same(self, other: 'c_route'):
        """Return whether two wrappers reference the same native route."""
        return bool(C.route_is_same(
            self._require_open(), other._require_open()
        ))

    def content_equal(self, other: 'c_route'):
        """Compare immutable route result coordinates, completion, and cost."""
        output = ffi.new("bool*")
        raise_for_status(
            C.route_content_equal(
                self._require_open(), other._require_open(), output
            ),
            "route_content_equal",
        )
        return bool(output[0])

    def content_hash(self):
        """Return the native 64-bit result-content hash."""
        output = ffi.new("uint64_t*")
        raise_for_status(
            C.route_fetch_content_hash(self._require_open(), output),
            "route_fetch_content_hash",
        )
        return int(output[0])

    def completion(self):
        output = ffi.new("route_completion_t*")
        status = NavsysStatus(
            C.route_fetch_completion(self._c, output)
        )
        if status is not NavsysStatus.OK:
            raise RuntimeError(
                f"route completion fetch failed: {status.name}"
            )
        return RouteCompletion(output[0])

    def export_coords(self):
        """Return a caller-buffer snapshot as ``[(x, y), ...]``."""
        required = ffi.new("size_t*")
        status = NavsysStatus(
            C.route_export_coords(self._c, ffi.NULL, 0, required)
        )
        if status is not NavsysStatus.OK:
            raise RuntimeError(f"route coordinate query failed: {status.name}")
        if required[0] == 0:
            return []

        output = ffi.new("coord_t[]", required[0])
        status = NavsysStatus(
            C.route_export_coords(
                self._c, output, required[0], required
            )
        )
        if status is not NavsysStatus.OK:
            raise RuntimeError(f"route coordinate export failed: {status.name}")
        return [(output[i].x, output[i].y) for i in range(required[0])]

    def to_builder(self):
        """Create an independent transactional builder from this route."""
        return c_route_builder(self)

    def visited_order(self):
        return c_coord_list(
            raw_ptr=C.route_get_visited_order(self._require_open()),
            own=False,
            parent=self,
        )

    def visited_count(self):
        return c_coord_hash(
            raw_ptr=C.route_get_visited_count(self._require_open()),
            own=False,
            value_type="int",
            parent=self,
        )

    def add_visited(self, coord: c_coord):
        return C.route_add_visited(self._c, coord.ptr())

    def clear_visited(self):
        C.route_clear_visited(self._c)

    def append(self, other: 'c_route', nodup=False):
        if nodup:
            C.route_append_nodup(self._c, other._c)
        else:
            C.route_append(self._c, other._c)

    def insert(self, index, coord: c_coord):
        C.route_insert(self._c, index, coord.ptr())

    def remove_at(self, index):
        C.route_remove_at(self._c, index)

    def remove_value(self, coord: c_coord):
        C.route_remove_value(self._c, coord.ptr())

    def contains(self, coord: c_coord):
        return bool(C.route_contains(self._c, coord.ptr()))

    def find(self, coord: c_coord):
        output = ffi.new("size_t*")
        status = NavsysStatus(
            C.route_find_coord(
                self._require_open(), coord.ptr(), output
            )
        )
        if status is NavsysStatus.NOT_FOUND:
            return -1
        raise_for_status(status, "route_find_coord")
        return int(output[0])

    def slice(self, start, end):
        if start < 0 or end < start:
            raise ValueError("route slice requires 0 <= start <= end")
        output = ffi.new("route_t**")
        raise_for_status(
            C.route_slice_ex(
                self._require_open(), start, end, output
            ),
            "route_slice_ex",
        )
        return c_route(raw_ptr=output[0], own=True)

    def look_at(self, index):
        ptr = C.route_make_direction(self._require_open(), index)
        return c_coord(raw_ptr=ptr, own=True) if ptr != ffi.NULL else None

    def calc_average_facing(self, history):
        return RouteDir(C.route_calc_average_facing(self._c, history))

    def calc_average_dir(self, history):
        return C.route_calc_average_dir(self._c, history)

    def get_direction_by_index(self, index):
        return RouteDir(C.route_get_direction_by_index(self._c, index))

    def direction_at(self, index):
        output = ffi.new("route_dir_t*")
        status = NavsysStatus(
            C.route_fetch_direction_at(self._require_open(), index, output)
        )
        if status is NavsysStatus.NOT_FOUND:
            raise IndexError(index)
        raise_for_status(status, "route_fetch_direction_at")
        return RouteDir(output[0])

    def recent_facing(self, history):
        output = ffi.new("route_dir_t*")
        raise_for_status(
            C.route_compute_recent_facing(
                self._require_open(), history, output
            ),
            "route_compute_recent_facing",
        )
        return RouteDir(output[0])

    def recent_heading_degrees(self, history):
        output = ffi.new("double*")
        raise_for_status(
            C.route_compute_recent_heading_degrees(
                self._require_open(), history, output
            ),
            "route_compute_recent_heading_degrees",
        )
        return output[0]

    def has_changed(self, from_coord, to_coord, angle_threshold):
        return bool(C.route_has_changed(self._c, from_coord.ptr(), to_coord.ptr(), angle_threshold))

    def has_changed_with_angle(self, from_coord, to_coord, angle_threshold):
        out = ffi.new("float*")
        changed = C.route_has_changed_with_angle(self._c, from_coord.ptr(), to_coord.ptr(), angle_threshold, out)
        return bool(changed), out[0]

    def has_changed_by_index(self, index_from, index_to, angle_threshold):
        return bool(C.route_has_changed_by_index(self._c, index_from, index_to, angle_threshold))

    def has_changed_with_angle_by_index(self, index_from, index_to, angle_threshold):
        out = ffi.new("float*")
        changed = C.route_has_changed_with_angle_by_index(self._c, index_from, index_to, angle_threshold, out)
        return bool(changed), out[0]

    def update_average_vector(self, from_coord, to_coord):
        C.route_update_average_vector(self._c, from_coord.ptr(), to_coord.ptr())

    def update_average_vector_by_index(self, index_from, index_to):
        C.route_update_average_vector_by_index(self._c, index_from, index_to)

    def reconstruct_path(self, came_from: c_coord_hash, start: c_coord, goal: c_coord):
        raise_for_status(
            C.route_reconstruct_ex(
                self._require_open(),
                came_from.ptr(),
                start.ptr(),
                goal.ptr(),
            ),
            "route_reconstruct_ex",
        )
        return True

    def print(self):
        print(self.format(), end="")

    def ptr(self):
        return self._c

    def __repr__(self):
        return (
            f"c_route(len={self.coord_count()}, cost={self.total_cost():.2f}, "
            f"completion={self.completion().name})"
        )

    def __del__(self):
        self.close()

    def close(self):
        if getattr(self, "_own", False) and self._finalizer and self._finalizer.alive:
            self._finalizer()
        self._c = ffi.NULL
        self._own = False

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()

    def __len__(self):
        return self.length()

    def format(self):
        """Return the native diagnostic representation, including newline."""
        required = ffi.new("size_t*")
        raise_for_status(
            C.route_format(
                self._require_open(), ffi.NULL, 0, required
            ),
            "route_format",
        )
        output = ffi.new("char[]", required[0])
        raise_for_status(
            C.route_format(
                self._require_open(), output, required[0], required
            ),
            "route_format",
        )
        return ffi.string(output).decode("utf-8")

    def to_string(self):
        return self.format().removesuffix("\n")

    @staticmethod
    def direction_to_coord(direction: RouteDir) -> c_coord:
        output = ffi.new("coord_t*")
        raise_for_status(
            C.route_direction_fetch_vector(direction, output),
            "route_direction_fetch_vector",
        )
        return c_coord(output.x, output.y)

    @staticmethod
    def calc_direction(start: c_coord, goal: c_coord) -> RouteDir:
        output = ffi.new("route_dir_t*")
        raise_for_status(
            C.route_direction_between(start.ptr(), goal.ptr(), output),
            "route_direction_between",
        )
        return RouteDir(output[0])

    @staticmethod
    def get_direction_by_dir_coord(dxdy: c_coord):
        output = ffi.new("route_dir_t*")
        raise_for_status(
            C.route_direction_from_vector(dxdy.ptr(), output),
            "route_direction_from_vector",
        )
        return RouteDir(output[0])


class c_route_builder:
    """Opaque transactional editor for producing one canonical route."""

    def __init__(self, source=None):
        self._c = ffi.NULL
        self._finalizer = None
        output = ffi.new("route_builder_t**")
        if source is None:
            status = C.route_builder_create(output)
        else:
            status = C.route_builder_create_from_route(
                source._require_open(), output
            )
        raise_for_status(status, "route_builder_create")
        self._c = output[0]
        self._finalizer = weakref.finalize(
            self, C.route_builder_destroy, self._c
        )

    def _require_open(self):
        if self._c == ffi.NULL:
            raise ReferenceError("c_route_builder is closed")
        return self._c

    def push(self, coord: c_coord):
        raise_for_status(
            C.route_builder_push_coord(
                self._require_open(), coord.ptr()
            ),
            "route_builder_push_coord",
        )
        return self

    def insert(self, index, coord: c_coord):
        raise_for_status(
            C.route_builder_insert_coord(
                self._require_open(), index, coord.ptr()
            ),
            "route_builder_insert_coord",
        )
        return self

    def remove(self, index):
        removed = ffi.new("coord_t*")
        raise_for_status(
            C.route_builder_remove_coord(
                self._require_open(), index, removed
            ),
            "route_builder_remove_coord",
        )
        return removed.x, removed.y

    def append(self, source: c_route, policy=RouteJoinPolicy.KEEP_ALL):
        raise_for_status(
            C.route_builder_append(
                self._require_open(), source._require_open(), int(policy)
            ),
            "route_builder_append",
        )
        return self

    def assign_slice(self, source: c_route, begin, end):
        raise_for_status(
            C.route_builder_assign_slice(
                self._require_open(), source._require_open(), begin, end
            ),
            "route_builder_assign_slice",
        )
        return self

    def set_total_cost(self, total_cost):
        raise_for_status(
            C.route_builder_set_total_cost(
                self._require_open(), total_cost
            ),
            "route_builder_set_total_cost",
        )
        return self

    def set_completion(self, completion: RouteCompletion):
        raise_for_status(
            C.route_builder_set_completion(
                self._require_open(), int(completion)
            ),
            "route_builder_set_completion",
        )
        return self

    def finish(self):
        output = ffi.new("route_t**")
        raise_for_status(
            C.route_builder_finish(self._require_open(), output),
            "route_builder_finish",
        )
        return c_route(raw_ptr=output[0], own=True)

    def close(self):
        if self._finalizer and self._finalizer.alive:
            self._finalizer()
        self._c = ffi.NULL

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()


class c_route_heading_tracker:
    """Opaque normalized heading history, independent from route values."""

    def __init__(self):
        self._c = ffi.NULL
        self._finalizer = None
        output = ffi.new("route_heading_tracker_t**")
        raise_for_status(
            C.route_heading_tracker_create(output),
            "route_heading_tracker_create",
        )
        self._c = output[0]
        self._finalizer = weakref.finalize(
            self, C.route_heading_tracker_destroy, self._c
        )

    def _require_open(self):
        if self._c == ffi.NULL:
            raise ReferenceError("c_route_heading_tracker is closed")
        return self._c

    @property
    def sample_count(self):
        return C.route_heading_tracker_get_sample_count(self._require_open())

    @property
    def heading_degrees(self):
        output = ffi.new("double*")
        raise_for_status(
            C.route_heading_tracker_fetch_heading_degrees(
                self._require_open(), output
            ),
            "route_heading_tracker_fetch_heading_degrees",
        )
        return output[0]

    def observe_vector(self, vector: c_coord, threshold_degrees):
        angle = ffi.new("double*")
        changed = ffi.new("bool*")
        raise_for_status(
            C.route_heading_tracker_observe_vector(
                self._require_open(), vector.ptr(), threshold_degrees,
                angle, changed
            ),
            "route_heading_tracker_observe_vector",
        )
        return bool(changed[0]), angle[0]

    def observe(self, start: c_coord, goal: c_coord, threshold_degrees):
        angle = ffi.new("double*")
        changed = ffi.new("bool*")
        raise_for_status(
            C.route_heading_tracker_observe(
                self._require_open(), start.ptr(), goal.ptr(),
                threshold_degrees, angle, changed
            ),
            "route_heading_tracker_observe",
        )
        return bool(changed[0]), angle[0]

    def reset(self):
        raise_for_status(
            C.route_heading_tracker_reset(self._require_open()),
            "route_heading_tracker_reset",
        )

    def close(self):
        if self._finalizer and self._finalizer.alive:
            self._finalizer()
        self._c = ffi.NULL

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass

    def __enter__(self):
        self._require_open()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
