from .ffi_core import ffi, C

from .coord import c_coord
from .coord_list import c_coord_list
from .coord_hash import c_coord_hash

from .route import c_route
from .navgrid import c_navgrid

import weakref

ffi.cdef("""
/* Generated by tools/python/byul_wrapper/generate_wrapper_abi.py. */
/* Do not edit this ffi.cdef block by hand. */

/* Source: byul/navsys/route_finder/route_finder_evaluation.h */
typedef navsys_status_t (*route_finder_cost_func_ex)(
    const navgrid_t* navgrid,
    const coord_t* from,
    const coord_t* to,
    float* out_cost,
    void* userdata);

typedef navsys_status_t (*route_finder_heuristic_func_ex)(
    const coord_t* from,
    const coord_t* goal,
    float* out_estimate,
    void* userdata);

 navsys_status_t route_finder_cost_unit(
    const navgrid_t* navgrid, const coord_t* from, const coord_t* to,
    float* out_cost, void* userdata);

 navsys_status_t route_finder_cost_zero(
    const navgrid_t* navgrid, const coord_t* from, const coord_t* to,
    float* out_cost, void* userdata);

 navsys_status_t route_finder_cost_diagonal(
    const navgrid_t* navgrid, const coord_t* from, const coord_t* to,
    float* out_cost, void* userdata);

 navsys_status_t route_finder_heuristic_euclidean(
    const coord_t* from, const coord_t* goal, float* out_estimate,
    void* userdata);

 navsys_status_t route_finder_heuristic_manhattan(
    const coord_t* from, const coord_t* goal, float* out_estimate,
    void* userdata);

 navsys_status_t route_finder_heuristic_chebyshev(
    const coord_t* from, const coord_t* goal, float* out_estimate,
    void* userdata);

 navsys_status_t route_finder_heuristic_octile(
    const coord_t* from, const coord_t* goal, float* out_estimate,
    void* userdata);

 navsys_status_t route_finder_heuristic_zero(
    const coord_t* from, const coord_t* goal, float* out_estimate,
    void* userdata);

 navsys_status_t route_finder_heuristic_default(
    const coord_t* from, const coord_t* goal, float* out_estimate,
    void* userdata);

/* Source: byul/navsys/route_finder/route_finder_core.h */
typedef float (*cost_func)(
    const navgrid_t* m, const coord_t* start, const coord_t* goal,
    void* userdata);

typedef float (*heuristic_func)(
    const coord_t* start, const coord_t* goal, void* userdata);

 float default_cost(
    const navgrid_t* m, const coord_t* start, const coord_t* goal,
    void* userdata);

 float zero_cost(
    const navgrid_t* m, const coord_t* start, const coord_t* goal,
    void* userdata);

 float diagonal_cost(
    const navgrid_t* m, const coord_t* start, const coord_t* goal,
    void* userdata);

 float euclidean_heuristic(
    const coord_t* start, const coord_t* goal, void* userdata);

 float manhattan_heuristic(
    const coord_t* start, const coord_t* goal, void* userdata);

 float chebyshev_heuristic(
    const coord_t* start, const coord_t* goal, void* userdata);

 float octile_heuristic(
    const coord_t* start, const coord_t* goal, void* userdata);

 float zero_heuristic(
    const coord_t* start, const coord_t* goal, void* userdata);

 float default_heuristic(
    const coord_t* start, const coord_t* goal, void* userdata);
""")

# Diagonal cost constant (sqrt(2) approx)
DIAGONAL_COST = 1.4142135


class c_route_func_registry:
    def __init__(self):
        self._cost_funcs = {}
        self._heuristic_funcs = {}

    def register_cost(self, name: str, func):
        self._cost_funcs[name] = func

    def register_heuristic(self, name: str, func):
        self._heuristic_funcs[name] = func

    def get_cost_func(self, name: str):
        if name not in self._cost_funcs:
            raise ValueError(f"[CostFunc] Unknown function: '{name}'")
        return self._cost_funcs[name]

    def get_heuristic_func(self, name: str):
        if name not in self._heuristic_funcs:
            raise ValueError(f"[HeuristicFunc] Unknown function: '{name}'")
        return self._heuristic_funcs[name]

    def all_cost_names(self):
        return list(self._cost_funcs.keys())

    def all_heuristic_names(self):
        return list(self._heuristic_funcs.keys())


g_RouteFuncReg = c_route_func_registry()

# Cost Functions
g_RouteFuncReg.register_cost("default", C.default_cost)
g_RouteFuncReg.register_cost("zero", C.zero_cost)
g_RouteFuncReg.register_cost("diagonal", C.diagonal_cost)

# Heuristic Functions
g_RouteFuncReg.register_heuristic("euclidean", C.euclidean_heuristic)
g_RouteFuncReg.register_heuristic("manhattan", C.manhattan_heuristic)
g_RouteFuncReg.register_heuristic("chebyshev", C.chebyshev_heuristic)
g_RouteFuncReg.register_heuristic("octile", C.octile_heuristic)
g_RouteFuncReg.register_heuristic("zero", C.zero_heuristic)
g_RouteFuncReg.register_heuristic("default", C.default_heuristic)