/*
 * tools/gen_base_primes_65535.c
 *
 * Generates: byul_base_primes_65535.h
 * - primes <= 65535 (uint16_t table)
 * - AVR-friendly PROGMEM storage + unified access macro
 * - C99, no recursion
 *
 * Usage:
 *   gen_base_primes_65535 [output_path]
 *
 * Examples:
 *   ./gen_base_primes_65535 > byul_base_primes_65535.h
 *   ./gen_base_primes_65535 ../byul/number_theory/byul_base_primes_65535.h
 *
 * Build (GCC/Clang/MSVC):
 *   gcc -std=c99 -O2 -Wall -Wextra -o gen_base_primes_65535 tools/gen_base_primes_65535.c
 *   clang -std=c99 -O2 -Wall -Wextra -o gen_base_primes_65535 tools/gen_base_primes_65535.c
 *   cl /O2 /W4 tools\gen_base_primes_65535.c
 */

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void die(const char *msg)
{
    fprintf(stderr, "error: %s\n", msg);
    exit(1);
}

/* Bitset for odds only: number x (odd, x>=3) -> idx=(x-3)/2 */
static inline void bits_set_all(uint8_t *bits, size_t bytes) { memset(bits, 0xFF, bytes); }
static inline void bits_clear(uint8_t *bits, size_t idx) { bits[idx >> 3] &= (uint8_t)~(1u << (idx & 7)); }
static inline bool bits_test(const uint8_t *bits, size_t idx) { return (bits[idx >> 3] & (uint8_t)(1u << (idx & 7))) != 0; }

static size_t generate_primes_u16(uint16_t limit, uint16_t *out, size_t cap)
{
    if (limit < 2) return 0;
    size_t count = 0;

    /* Always include 2 */
    if (cap == 0) return 0;
    out[count++] = 2;

    if (limit < 3) return count;

    const uint32_t odds_count = ((uint32_t)limit - 3u) / 2u + 1u;
    const size_t bit_bytes = (size_t)((odds_count + 7u) >> 3);

    uint8_t *bits = (uint8_t *)malloc(bit_bytes);
    if (!bits) die("out of memory allocating sieve bitset");

    bits_set_all(bits, bit_bytes);

    for (uint32_t p = 3; (uint64_t)p * (uint64_t)p <= (uint64_t)limit; p += 2) {
        const size_t p_idx = (size_t)((p - 3u) >> 1);
        if (!bits_test(bits, p_idx)) continue;

        uint32_t j = p * p;
        const uint32_t step = p << 1; /* 2p */
        for (; j <= (uint32_t)limit; j += step) {
            const size_t j_idx = (size_t)((j - 3u) >> 1);
            bits_clear(bits, j_idx);
        }
    }

    for (uint32_t x = 3; x <= (uint32_t)limit; x += 2) {
        const size_t idx = (size_t)((x - 3u) >> 1);
        if (bits_test(bits, idx)) {
            if (count >= cap) break;
            out[count++] = (uint16_t)x;
        }
    }

    free(bits);
    return count;
}

static void write_header(FILE *f, const uint16_t *primes, size_t count, uint16_t limit)
{
    fprintf(f,
        "/*\n"
        " * byul_base_primes_65535.h (generated)\n"
        " *\n"
        " * Primes <= %u\n"
        " * Count: %zu\n"
        " *\n"
        " * This file is generated by tools/gen_base_primes_65535.c\n"
        " */\n"
        "\n"
        "#ifndef BYUL_BASE_PRIMES_65535_H\n"
        "#define BYUL_BASE_PRIMES_65535_H\n"
        "\n"
        "#include <stdint.h>\n"
        "\n"
        "/* AVR PROGMEM support (optional). On non-AVR, BYUL_PROGMEM is empty. */\n"
        "#if defined(__AVR__)\n"
        "  #include <avr/pgmspace.h>\n"
        "  #define BYUL_PROGMEM PROGMEM\n"
        "  static inline uint16_t byul_read_u16_progmem_(const uint16_t *p) {\n"
        "    return (uint16_t)pgm_read_word(p);\n"
        "  }\n"
        "  #define BYUL_BASE_PRIME_AT(arr, i) byul_read_u16_progmem_(&(arr)[(i)])\n"
        "#else\n"
        "  #define BYUL_PROGMEM\n"
        "  #define BYUL_BASE_PRIME_AT(arr, i) ((arr)[(i)])\n"
        "#endif\n"
        "\n"
        "/* Generated prime table (uint16_t). */\n"
        "static const uint16_t byul_base_primes_65535[] BYUL_PROGMEM = {\n",
        (unsigned)limit, count
    );

    /* Format: 12 numbers per line (readable, compact) */
    for (size_t i = 0; i < count; i++) {
        if (i % 12 == 0) fprintf(f, "  ");
        fprintf(f, "%u", (unsigned)primes[i]);
        if (i + 1 != count) fprintf(f, ", ");
        if ((i % 12 == 11) || (i + 1 == count)) fprintf(f, "\n");
    }

    fprintf(f,
        "};\n"
        "\n"
        "static const uint16_t byul_base_primes_65535_count = (uint16_t)(sizeof(byul_base_primes_65535) / sizeof(byul_base_primes_65535[0]));\n"
        "\n"
        "#endif /* BYUL_BASE_PRIMES_65535_H */\n"
    );
}

int main(int argc, char **argv)
{
    const uint16_t limit = 65535;

    /* Upper bound pi(65535) is < 7000, actual is 6542 */
    uint16_t primes[7000];
    const size_t count = generate_primes_u16(limit, primes, sizeof(primes) / sizeof(primes[0]));
    if (count == 0) die("failed to generate primes");

    /* Optional sanity check (count expected 6542) */
    if (count != 6542) {
        fprintf(stderr, "warning: expected 6542 primes <= 65535, got %zu\n", count);
    }

    FILE *out = stdout;
    if (argc >= 2) {
        out = fopen(argv[1], "wb");
        if (!out) die("failed to open output file");
    }

    write_header(out, primes, count, limit);

    if (out != stdout) {
        fclose(out);
    }
    return 0;
}
