#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
tools/gen_base_primes_65535.py

Generates: byul_base_primes_65535.h
- primes <= 65535 (uint16_t table)
- AVR-friendly PROGMEM storage + unified access macro

Usage:
  python tools/gen_base_primes_65535.py [output_path]

Examples:
  python tools/gen_base_primes_65535.py > byul_base_primes_65535.h
  python tools/gen_base_primes_65535.py ../byul/number_theory/byul_base_primes_65535.h
"""

from __future__ import annotations

import sys
import textwrap
from typing import List


def generate_primes_u16(limit: int) -> List[int]:
    """Generate primes <= limit using odd-only sieve (like the C version)."""
    if limit < 2:
        return []

    primes: List[int] = [2]
    if limit < 3:
        return primes

    odds_count = ((limit - 3) // 2) + 1
    bits = bytearray([0xFF]) * ((odds_count + 7) // 8)

    def bits_test(idx: int) -> bool:
        return (bits[idx >> 3] & (1 << (idx & 7))) != 0

    def bits_clear(idx: int) -> None:
        bits[idx >> 3] &= ~(1 << (idx & 7))

    p = 3
    while p * p <= limit:
        p_idx = (p - 3) // 2
        if bits_test(p_idx):
            j = p * p
            step = p * 2
            while j <= limit:
                j_idx = (j - 3) // 2
                bits_clear(j_idx)
                j += step
        p += 2

    x = 3
    while x <= limit:
        idx = (x - 3) // 2
        if bits_test(idx):
            primes.append(x)
        x += 2

    return primes


def write_header(primes: List[int], limit: int) -> str:
    count = len(primes)
    tool_name = sys.argv[0].replace("\\", "/")

    header = textwrap.dedent(f"""\
        /*
         * byul_base_primes_65535.h (generated)
         *
         * Primes <= {limit}
         * Count: {count}
         *
         * This file is generated by {tool_name}
         */

        #ifndef BYUL_BASE_PRIMES_65535_H
        #define BYUL_BASE_PRIMES_65535_H

        #include <stdint.h>

        /* AVR PROGMEM support (optional). On non-AVR, BYUL_PROGMEM is empty. */
        #if defined(__AVR__)
          #include <avr/pgmspace.h>
          #define BYUL_PROGMEM PROGMEM
          static inline uint16_t byul_read_u16_progmem_(const uint16_t *p) {{
            return (uint16_t)pgm_read_word(p);
          }}
          #define BYUL_BASE_PRIME_AT(arr, i) byul_read_u16_progmem_(&(arr)[(i)])
        #else
          #define BYUL_PROGMEM
          #define BYUL_BASE_PRIME_AT(arr, i) ((arr)[(i)])
        #endif

        /* Generated prime table (uint16_t). */
        static const uint16_t byul_base_primes_65535[] BYUL_PROGMEM = {{
        """)

    table_lines: List[str] = []
    for i in range(0, count, 12):
        chunk = primes[i:i + 12]
        line = ", ".join(str(p) for p in chunk)
        if i + 12 < count:
            table_lines.append(f"  {line},")
        else:
            table_lines.append(f"  {line}")

    table = "\n".join(table_lines)

    footer = textwrap.dedent("""\
        };

        static const uint16_t byul_base_primes_65535_count =
            (uint16_t)(sizeof(byul_base_primes_65535) /
                       sizeof(byul_base_primes_65535[0]));

        #define BYUL_BASE_PRIMES_PROVIDED 1

        #endif /* BYUL_BASE_PRIMES_65535_H */
        """)

    return header + table + "\n" + footer + "\n"


def main() -> int:
    limit = 65535
    primes = generate_primes_u16(limit)

    if not primes:
        print("error: failed to generate primes", file=sys.stderr)
        return 1

    if len(primes) != 6542:
        print(f"warning: expected 6542 primes <= 65535, got {len(primes)}", file=sys.stderr)

    out_text = write_header(primes, limit)

    if len(sys.argv) >= 2:
        out_path = sys.argv[1]
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(out_text)
    else:
        sys.stdout.write(out_text)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
